import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app.assist.id/login');
  await page.locator('#username').click();
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#password').click();
  await page.locator('#password').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.goto('https://app.assist.id/');
  await page.getByRole('button', { name: 'close' }).click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '987107 - Clinica Lite Assist' }).click();
  await page.locator('.jss1782.jss1783.jss1790.jss1800.jss1833 > .jss1782').click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.locator('.jss2680').click();
  await page.getByRole('button', { name: 'Billing !' }).click();
  await page.getByRole('button', { name: 'Tambah Berlangganan' }).click();
  await page.getByRole('button', { name: 'Tahun' }).click();
  await page.getByRole('option', { name: '1 Bulan' }).click();
  await page.locator('.jss2821').click();
  await page.goto('https://app.assist.id/office');
  await page.getByRole('textbox', { name: 'Search' }).fill('CL');
  await page.getByRole('textbox', { name: 'Search' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search' }).fill('CL-');
  await page.getByRole('textbox', { name: 'Search' }).press('Enter');
  await page.goto('https://app.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('CL-');
  await page.getByRole('option', { name: 'Assist stg' }).press('Escape');
  await page.locator('[data-test="input-complaint"]').fill('Test Appt RJ Prod');
  await page.goto('https://app.assist.id/layanan-tambahan');
  await page.getByRole('textbox', { name: 'Cari nama add on' }).fill('voucher');
  await page.getByRole('textbox', { name: 'Cari nama add on' }).press('Escape');
  await page.getByRole('textbox', { name: 'Cari nama add on' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari nama add on' }).fill('depos');
  await page.getByRole('textbox', { name: 'Cari nama add on' }).press('Enter');
  await page.getByRole('textbox', { name: 'Cari nama add on' }).press('Escape');
  await page.getByRole('textbox', { name: 'Cari nama add on' }).press('Escape');
  await page.getByRole('textbox', { name: 'Cari nama add on' }).press('Escape');
  await page.locator('[data-test="autocomplete-input"]').fill('AC');
  await page.goto('https://app.assist.id/layanan-tambahan');
  await page.goto('https://app.assist.id/registration');
  await page1.getByRole('button', { name: 'Katalog Harga Prosedur' }).click();
  await page1.locator('div').filter({ hasText: 'General SettingsManajemen' }).nth(5).click();
  await page1.locator('div').filter({ hasText: 'General SettingsManajemen' }).nth(5).click();
  await page1.locator('[data-test="sidebar-item-apotek"]').click();
  await page1.locator('[data-test="close-global-tooltip"]').click();
  await page1.getByRole('button', { name: 'Obat', exact: true }).click();
  await page1.locator('html').click();
  await page1.locator('div').filter({ hasText: 'Data Stok ObatTambah Data' }).nth(5).click();
  await page1.locator('div').filter({ hasText: 'Data Stok ObatTambah Data' }).nth(5).click();
  await page1.locator('[data-test="sidebar-item-settings"]').click();
  await page1.locator('[data-test="sidebar-item-settings"]').press('ControlOrMeta+f');
  await page1.locator('[data-test="sidebar-item-settings"]').press('Escape');
  await page1.locator('[data-test="sidebar-item-office"]').click();
  await page1.locator('div').filter({ hasText: 'Dashboard BPJSBaruDashboard' }).nth(5).click();
  await page1.locator('div').filter({ hasText: 'Dashboard BPJSBaruDashboard' }).nth(5).click();
  await page1.getByText('November 2033').click();
  await page1.locator('div').filter({ hasText: 'Dashboard BPJSBaruDashboard' }).nth(5).click();
  await page1.locator('[data-test="sidebar-item-settings"]').click();
  await page1.getByRole('button', { name: 'Katalog Harga Prosedur' }).click();
  await page1.locator('[data-test="sidebar-item-kasir"]').click();
  await page1.locator('[data-test="sidebar-item-profile"]').click();
  await page1.getByRole('button', { name: 'Edit' }).click();
  await page1.getByRole('button', { name: 'Metode Pembayaran' }).click();
  await page.goto('https://app.assist.id/settings');
  await page.getByRole('textbox', { name: 'Cari staff' }).fill('gesi');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('Escape');
  await page.getByText('Edit StaffNama Lengkap *').press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).fill('Gesi []');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).fill('Gesi [Acc23]');
  await page.getByRole('textbox', { name: 'Alamat Email' }).fill('anisasecondacc23@gmail.com');
  await page.getByRole('textbox', { name: 'Jabatan' }).fill('QA');
  await page.getByRole('textbox', { name: 'Nomor Hp' }).fill('0800-0000-0009  ');
  await page1.locator('.jss56.jss95.jss100').click();
  await page1.getByText('Tambah Vital SignClinica Lite').click();
  await page.getByRole('textbox').first().fill('CL-Cholecystectomy');
  await page.getByRole('textbox', { name: 'Cari ICD 9 CM' }).fill('12');
  await page.getByRole('textbox', { name: 'Nama Praktek' }).fill('');
  await page.getByRole('textbox').nth(1).fill('Rp20.0000');
  await page.locator('div:nth-child(2) > div > div:nth-child(2) > .jss1783.jss1816 > .jss62543 > .jss62578 > .jss62588').fill('CL-Hysterectomy');
  await page.locator('div:nth-child(2) > div > div:nth-child(2) > div:nth-child(2) > .jss62543 > .jss62578 > .jss62588').fill('Rp40.0000');
  await page.locator('[data-test="autocomplete-input"]').nth(5).fill('CL-');
  await page.getByRole('button', { name: 'Drag & drop files orbrowse' }).setInputFiles('Import Katalog Harga Prosedur (5).xlsx');
  await page.goto('https://app.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('CL-');
  await page.locator('[data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="quantity-input"]').fill('1');
  await page.locator('[data-test="autocomplete-input"]').fill('CL-');
  await page.goto('https://app.assist.id/apotek');
  await page.locator('[data-test="input-cari-obat"]').fill('CL-');
  await page.locator('[data-test="input-cari-obat"]').press('Enter');
  await page.locator('[data-test="input-cari-obat"]').press('Escape');
  await page.locator('input[name="barcode"]').fill('CL-M-01');
  await page.locator('input[name="medName"]').fill('CL-M-Carbamazepine');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('CLM');
  await page.getByRole('textbox', { name: 'Jenis' }).fill('Anti');
  await page.getByRole('textbox', { name: 'Satuan *' }).fill('Pil');
  await page.locator('input[name="dosage"]').fill('12mg');
  await page.locator('input[name="stockTotalObat"]').press('Shift+ArrowLeft');
  await page.locator('input[name="stockTotalObat"]').fill('300');
  await page.locator('input[name="batchNo"]').fill('BM-0123333');
  await page.locator('input[name="buyFee"]').fill('Rp3000,00');
  await page.locator('input[name="sellOtcFee"]').fill('Rp6000');
  await page.locator('input[name="barcode"]').fill('CL-M-02');
  await page.locator('input[name="medName"]').fill('CL-Memantine');
  await page.locator('input[name="medName"]').press('Alt+ArrowLeft');
  await page.locator('input[name="medName"]').press('Alt+ArrowLeft');
  await page.locator('input[name="medName"]').press('Alt+ArrowRight');
  await page.locator('input[name="medName"]').fill('CL-M-Memantine');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('Pil');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('CLM');
  await page.getByRole('textbox', { name: 'Jenis' }).fill('Ant');
  await page.getByRole('textbox', { name: 'Satuan *' }).fill('Pil');
  await page.locator('input[name="dosage"]').fill('12 ml');
  await page.locator('input[name="stockTotalObat"]').fill('0400');
  await page.locator('input[name="batchNo"]').fill('BCM-00123');
  await page.locator('input[name="buyFee"]').fill('Rp4000,00');
  await page.locator('input[name="sellOtcFee"]').fill('Rp6000');
  await page.goto('https://app.assist.id/settings');
  await page.getByRole('textbox').filter({ hasText: 'Praktek dr. Dimas Tri Anantyo' }).press('ControlOrMeta+ArrowLeft');
  await page.getByRole('textbox').filter({ hasText: 'Praktek dr. Dimas Tri Anantyo' }).press('ControlOrMeta+Shift+ArrowRight');
  await page.getByRole('textbox').filter({ hasText: 'Praktek dr. Dimas Tri Anantyo' }).fill('Klinik Clinica Lite Assist.id');
  await page.getByRole('textbox').filter({ hasText: 'Praktek dr. Dimas Tri Anantyo' }).press('Escape');
  await page.goto('https://app.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('surat');
  await page.goto('https://app.assist.id/registration');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('CL-');
  await page.locator('[data-test="input-complaint"]').fill('TEst random');
  await page.locator('[data-test="input-complaint"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('ArrowRight');
  await page.locator('[data-test="input-complaint"]').press('ArrowRight');
  await page.locator('[data-test="input-complaint"]').press('Shift+ArrowRight');
  await page.locator('[data-test="input-complaint"]').fill('Test random');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('CL-');
  await page.locator('[data-test="input-complaint"]').fill('CEk ');
  await page.locator('[data-test="input-complaint"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-complaint"]').fill('Random Cek Ranap Persalinan');
  await page.goto('https://app.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('pro');
  await page.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').fill('CL-');
  await page.locator('[data-test="input-notes-0-procedure"]').fill('Random appt');
  await page.getByRole('textbox', { name: 'Cari fitur' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('rese');
  await page.locator('[data-test="container-medicine-autocomplete-0-prescription"] [data-test="autocomplete-input"]').fill('Cl-');
  await page.locator('[data-test="input-quantity-0-prescription"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-quantity-0-prescription"]').fill('2');
  await page.locator('[data-test="autocomplete-input"]').fill('');
  await page.locator('[data-test="input-cigna-0-prescription"]').fill('random');
  await page.locator('input[name="prescriptions.0.frequency"]').fill('1');
  await page.locator('input[name="prescriptions.0.period"]').fill('2');
  await page.getByRole('textbox', { name: 'Cari fitur' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('diagn');
  await page.getByRole('textbox', { name: 'Cari fitur' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('cata');
  await page.locator('[data-test="autocomplete-input"]').fill('Cough');
  await page.getByRole('textbox', { name: 'Cari fitur' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('dia');
  await page.locator('[data-test="autocomplete-input"]').fill('Cigueh');
  await page.locator('[data-test="autocomplete-input"]').press('ControlOrMeta+a');
  await page.locator('[data-test="autocomplete-input"]').fill('Blood');
  await page.goto('https://app.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan atau obat' }).fill('cl-');
  await page1.locator('[data-test="sidebar-item-apotek"]').click();
  await page1.getByRole('button', { name: 'Obat', exact: true }).click();
  await page1.locator('.jss242.jss3882 > .jss3926').click();
  await page1.locator('[data-test="input-cari-obat"]').fill('CL-');
  await page.locator('[data-test="kasir-item-3"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-3"] [data-test="quantity-input"]').fill('6');
  await page.locator('[data-test="kasir-item-3"] [data-test="quantity-input"]').press('Enter');
  await page.locator('[data-test="kasir-item-3"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-3"] [data-test="quantity-input"]').fill('6');
  await page.locator('[data-test="kasir-item-3"] [data-test="quantity-input"]').press('Enter');
  await page1.locator('[data-test="input-cari-obat"]').press('Enter');
  await page1.locator('[data-test="input-cari-obat"]').fill('CL-');
  await page1.locator('[data-test="input-cari-obat"]').press('Enter');
  await page.getByRole('textbox', { name: 'Cari tindakan atau obat' }).fill('CL-');
  await page1.locator('input[name="stockTotalObat"]').press('Shift+ArrowLeft');
  await page1.locator('input[name="stockTotalObat"]').fill('323');
  await page1.locator('input[name="stockTotalObat"]').press('ControlOrMeta+f');
  await page1.goto('https://app.assist.id/cashier');
  await page1.locator('[data-test="input-bayar-langsung"]').fill('Rp25.0000');
  await page1.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('CL-');
  await page1.locator('[data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page1.locator('[data-test="quantity-input"]').fill('5');
  await page1.locator('[data-test="input-bayar-langsung"]').fill('Rp1.0000');
  await page1.locator('[data-test="input-bayar-langsung"]').press('Tab');
  await page1.locator('[data-test="input-dibayar-oleh-langsung"]').fill('Pasien OTC');
  await page1.goto('https://app.assist.id/office');
  await page1.getByRole('textbox', { name: 'Cari Laporan' }).fill('mor');
  await page1.getByRole('button', { name: '15', exact: true }).press('ControlOrMeta+f');
  await page1.getByRole('group', { name: 'Diagnosa' }).getByRole('textbox').fill('blood');
  await page1.locator('html').getByRole('document').press('Escape');
  await page1.getByRole('textbox', { name: 'Cari Laporan' }).fill('margin');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('CL-');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).press('Enter');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('tissue');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).press('Enter');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('');
  await page.goto('https://app.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('Tersedia, ada datanya\t\t\t\t\t \tjika blm ada pembelian, all data jadi Rp0\t\t\t\t \tCalc sesuai\t15,000\t30,000\t0.5\t50');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('Alko');
  await page.locator('[data-test="quantity-input"]').fill('01');
  await page1.locator('html').getByRole('document').press('Escape');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('Alcohol');
  await page.locator('[data-test="quantity-input"]').press('Shift+ArrowRight');
  await page.locator('[data-test="quantity-input"]').fill('1');
  await page.locator('[data-test="input-bayar-langsung"]').fill('Rp120.00');
  await page.locator('[data-test="input-dibayar-oleh-langsung"]').fill('Cek Lap Margin BHP');
  await page1.goto('https://app.assist.id/office');
  await page1.getByRole('textbox', { name: 'Cari Laporan' }).fill('margin');
  await page1.getByRole('button', { name: '15' }).press('ControlOrMeta+f');
  await page1.getByRole('button', { name: 'Filter Data' }).press('ControlOrMeta+=');
  await page1.getByRole('button', { name: 'Filter Data' }).press('ControlOrMeta+=');
  await page1.getByRole('button', { name: 'Filter Data' }).press('ControlOrMeta+f');
});