import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app.assist.id/login');
  await page.getByText('Pilih Hanya Yang TerbaikAssist.id adalah sistem informasi kesehatan terbaik').click();
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#password').click();
  await page.locator('#password').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '657399 - Klinik Tech [Clinica' }).click();
  await page.locator('[data-test="sidebar-item-registrasi"]').click();
  await page.locator('.jss1971.jss2006 > button').click();
  await page.getByRole('button').filter({ hasText: 'event' }).nth(1).click();
  await page.getByRole('button', { name: '19' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('cell', { name: '/05/2026, 00:13' }).click();
  await page.getByRole('button', { name: 'Lihat Rekam Medis' }).click();
  await page.locator('.jss3988').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.getByRole('button', { name: 'GUNAKAN AI' }).click();
  await page.getByRole('menuitem', { name: 'Tambah Catatan Dokter' }).click();
  await page.getByRole('menuitem', { name: 'Tambah Catatan Dokter' }).press('Escape');
  await page.locator('.jss3596 > div:nth-child(2) > div').click();
  await page.locator('[data-test="emrAddBtn"]').click();
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('pro');
  await page.getByRole('menuitem', { name: 'Tambah Prosedur' }).click();
  await page.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').click();
  await page.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').fill('KT-');
  await page.getByText('KT-Leukapheresis').click();
  await page.getByRole('button').nth(4).click();
  await page.getByRole('option', { name: '-' }).press('Escape');
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('button').first().click();
  await page.locator('.jss4167').click();
  await page.locator('[data-test="sidebar-item-message-center"]').click();
  await page.getByRole('listitem', { name: 'Targeted SMS' }).click();
  await page.getByRole('listitem', { name: 'Ikhtisar' }).click();
  await page.getByRole('listitem', { name: 'Whatsapp' }).click();
  await page.locator('[data-test="sidebar-item-office"]').click();
  await page.getByRole('button', { name: 'Keuangan' }).click();
  await page.getByRole('button', { name: 'Laporan' }).click();
  await page.locator('[data-test="sidebar-item-akreditasi"]').click();
  await page.locator('.jss1970.jss1971.jss1994 > div > div:nth-child(2)').click();
  await page.getByRole('button', { name: 'LENGKAPI' }).first().click();
  await page.getByRole('columnheader', { name: 'Status' }).click();
  await page.getByRole('cell', { name: 'BELUM SELESAI' }).first().click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('Cat 08.jpg');
  await page.getByRole('button', { name: 'SIMPAN' }).click();
  await page.getByRole('heading', { name: '> Standar.1.1' }).click();
  await page.getByRole('cell', { name: 'Tersedia visi, misi, dan' }).click();
  await page.getByRole('checkbox', { name: 'Selesai' }).check();
  await page.getByRole('button', { name: 'SIMPAN' }).click();
  await page.getByRole('heading', { name: '> Standar.1.1' }).click();
  await page.getByText('Akreditasi > BAB1 > Standar.1').click();
  await page.locator('#kamarmedis-content').getByRole('heading', { name: 'Akreditasi' }).click();
  await page.getByText('Lengkapi berkas-berkas yang').click();
  await page.locator('.jss1970.jss1971.jss1994 > div > div:nth-child(2)').click();
  await page.getByRole('button', { name: 'LENGKAPI' }).nth(1).click();
  await page.getByRole('cell', { name: 'BELUM SELESAI' }).first().click();
  await page.locator('#gambar').click();
  await page.locator('#gambar').setInputFiles('Cat 04.jpg');
  await page.locator('div:nth-child(4) > .jss1971.jss2008 > div > div:nth-child(2) > .jss1970 > div:nth-child(2)').click();
  await page.locator('#dokumenBukti').click();
  await page.locator('#dokumenBukti').setInputFiles('Cat 08.jpg');
  await page.locator('div:nth-child(4) > .jss1971.jss2008 > div > div:nth-child(2) > .jss1970 > div:nth-child(2) > ul > li > div > svg:nth-child(5) > g > path').click();
  await page.locator('#dokumenBukti').click();
  await page.locator('#dokumenBukti').setInputFiles('Cat 10.jpg');
  await page.getByRole('checkbox', { name: 'Selesai' }).check();
  await page.getByRole('button', { name: 'SIMPAN' }).click();
  await page.locator('#kamarmedis-content').getByRole('heading', { name: 'Akreditasi' }).click();
  await page.locator('[data-test="sidebar-item-pks"]').click();
  await page.locator('[data-test="sidebar-item-pertanyaan"]').click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.getByRole('button', { name: 'Medical Check Up' }).click();
  await page.getByText('Katalog Medical Check UpTambah Katalog').click();
  await page.getByRole('button', { name: 'Tambah Katalog' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('KT-Radiosurgery');
  await page.getByRole('button', { name: 'Tambah MCU' }).click();
  await page.locator('div').filter({ hasText: /^Tambah MCU$/ }).click();
  await page.getByText('Tidak pakai nilai').nth(1).click();
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('Radio 01');
  await page.locator('.jss1971.jss2009 > div > div:nth-child(2)').first().click();
  await page.locator('.jss1971.jss2009 > div > div:nth-child(2)').first().click();
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('Rp2.0000');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('Radio 02');
  await page.locator('.jss6737.jss6722.jss6743').click();
  await page.locator('.jss6737.jss6722.jss6743').fill('Result Rad 01');
  await page.locator('.jss6813').click();
  await page.getByText('Result Rad').dblclick();
  await page.getByText('Result Rad').click();
  await page.locator('.jss6737.jss6722.jss6743').click();
  await page.locator('.jss6737.jss6722.jss6743').fill('Result Rad 02');
  await page.locator('.jss6813 > g > path').click();
  await page.getByRole('checkbox', { name: 'Set sebagai nilai normal' }).first().check();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('option', { name: '<' }).click();
  await page.locator('input[name="max"]').click();
  await page.locator('input[name="max"]').fill('100');
  await page.locator('div:nth-child(6) > .jss1970 > div:nth-child(2)').click();
  await page.locator('div:nth-child(6) > .jss1970 > div:nth-child(2)').click();
  await page.locator('input[name="Satuan"]').fill('Scale');
  await page.locator('.jss1970.jss1994 > div:nth-child(3)').click();
  await page.locator('.jss1970.jss1994 > div:nth-child(3)').click();
  await page.locator('[data-test="autocomplete-input"]').fill('KT-');
  await page.getByText('KT-Nyla').click();
  await page.locator('div:nth-child(6) > .jss1971.jss2009 > div > div:nth-child(2) > .jss1970 > div:nth-child(2) > .jss6692 > .jss6727 > .jss6737').click();
  await page.locator('.jss6727.jss6714.jss6718.jss6736.jss6721.jss6729 > .jss6737').fill('Rp5.0000');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('cell', { name: 'Rp70.000' }).click();
  await page.locator('[data-test="sidebar-item-registrasi"]').click();
  await page.locator('[data-test="menu-laboratorium"]').click();
  await page.getByRole('button', { name: 'Pendaftaran Baru' }).click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('KTC-');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('TC-');
  await page.getByRole('button', { name: 'TC-Campbell 21-04-2007,' }).click();
  await page.getByRole('button', { name: 'Rawat Jalan' }).click();
  await page.locator('.jss18897').click();
  await page.getByRole('button', { name: 'Umum' }).nth(1).click();
  await page.getByRole('option', { name: 'Lab' }).click();
  await page.getByRole('button', { name: 'Pilih MCU' }).click();
  await page.getByRole('checkbox', { name: 'Radio 01' }).check();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button').filter({ hasText: 'event' }).click();
  await page.getByRole('menu').click();
  await page.getByRole('heading', { name: '18' }).click();
  await page.getByRole('menu').click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('[data-test="input-complaint"]').click();
  await page.locator('[data-test="input-complaint"]').fill('TEst Poli Lab');
  await page.locator('[data-test="input-complaint"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('ArrowRight');
  await page.locator('[data-test="input-complaint"]').press('ArrowRight');
  await page.locator('[data-test="input-complaint"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-complaint"]').fill('TEst Poli Lab');
  await page.locator('[data-test="input-complaint"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-complaint"]').fill('Test Poli Lab');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('[data-test="menu-rawat-jalan-lab"]').click();
  await page.locator('[data-test="menu-laboratorium"]').click();
  await page.locator('[data-test="menu-rawat-jalan-lab"]').click();
  await page.locator('[data-test="menu-laboratorium"]').click();
  await page.locator('[data-test="input-nama-pasien-filter"]').click();
  await page.locator('div').filter({ hasText: 'RegistrationKlinik Tech [' }).nth(4).click();
  await page.locator('[data-test="sidebar-item-apotek"]').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.locator('[data-test="sidebar-item-kasir"]').click();
  await page.locator('[data-test="button-tutup-buku"]').click();
  await page.locator('div:nth-child(6) > .jss2308.jss33849 > .jss2308').click();
  await page.locator('.jss2308.jss2379.jss33854').first().click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('columnheader', { name: 'Keterangan' }).click();
  await page.getByText('Tutup BukuPembayaranExportDari TanggalSampai TanggalFilterPreview Ranap').click();
  await page.getByRole('button', { name: 'Pembayaran', description: 'Klik ikon ini untuk membuat pembayaran baru, contoh : pembelian obat langsung di apotek', exact: true }).click();
  await page.locator('[data-test="add-racikan-button"]').click();
  await page.locator('textarea[name="prescriptions.0.cigna"]').click();
  await page.locator('textarea[name="prescriptions.0.cigna"]').fill('-');
  await page.getByRole('button', { name: '+ Tambah Resep Racikan' }).click();
  await page.getByRole('textbox', { name: 'Nama Obat' }).click();
  await page.getByRole('textbox', { name: 'Nama Obat' }).fill('KT');
  await page.getByRole('button', { name: 'KT-M-Ezetimibe (10 mg) KTM' }).click();
  await page.locator('input[name="prescriptions.0.materialPrescript.0.numerator"]').click();
  await page.locator('input[name="prescriptions.0.materialPrescript.0.numerator"]').fill('1');
  await page.locator('input[name="prescriptions.0.materialPrescript.0.numerator"]').click();
  await page.locator('input[name="prescriptions.0.materialPrescript.0.denominator"]').click();
  await page.locator('input[name="prescriptions.0.materialPrescript.0.denominator"]').fill('1');
  await page.getByRole('button', { name: '+ Tambah Resep Racikan' }).click();
  await page.getByRole('textbox', { name: 'Nama Obat' }).click();
  await page.getByRole('textbox', { name: 'Nama Obat' }).fill('KT');
  await page.getByRole('button', { name: 'KT-M-Cinnarizine (20 mg) KTM' }).click();
  await page.locator('input[name="prescriptions.0.materialPrescript.1.numerator"]').click();
  await page.locator('input[name="prescriptions.0.materialPrescript.1.numerator"]').fill('1');
  await page.locator('input[name="prescriptions.0.materialPrescript.1.denominator"]').click();
  await page.locator('input[name="prescriptions.0.materialPrescript.1.denominator"]').fill('1');
  await page.locator('input[name="prescriptions.0.quantity"]').click();
  await page.getByRole('textbox', { name: 'Satuan' }).click();
  await page.getByRole('textbox', { name: 'Satuan' }).fill('Pil');
  await page.locator('#downshift-28-item-0').getByText('Pil').click();
  await page.getByText('Signatura (Keterangan)--Ketik').click();
  await page.locator('input[name="prescriptions.0.quantity"]').click();
  await page.locator('input[name="prescriptions.0.quantity"]').fill('2');
  await page.locator('textarea[name="prescriptions.0.materialPrescript.1.note"]').click();
  await page.locator('textarea[name="prescriptions.0.materialPrescript.1.note"]').fill('random');
  await page.locator('button:nth-child(7)').first().click();
  await page.locator('input[name="prescriptions.0.materialPrescript.0.numerator"]').click();
  await page.locator('input[name="prescriptions.0.materialPrescript.0.numerator"]').press('Shift+ArrowLeft');
  await page.locator('input[name="prescriptions.0.materialPrescript.0.numerator"]').fill('2');
  await page.locator('input[name="prescriptions.0.materialPrescript.1.numerator"]').click();
  await page.locator('input[name="prescriptions.0.materialPrescript.1.denominator"]').click();
  await page.locator('input[name="prescriptions.0.materialPrescript.1.denominator"]').click();
  await page.locator('input[name="prescriptions.0.materialPrescript.1.denominator"]').press('Shift+ArrowLeft');
  await page.locator('input[name="prescriptions.0.materialPrescript.1.denominator"]').fill('3');
  await page.locator('div').filter({ hasText: /^Keterangan tambahanrandomrandom$/ }).first().click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Iya' }).click();
  await page.locator('[data-test="autocomplete-input"]').click();
  await page.locator('[data-test="autocomplete-input"]').fill('Radn');
  await page.locator('[data-test="autocomplete-input"]').press('ControlOrMeta+a');
  await page.locator('[data-test="autocomplete-input"]').fill('Random');
  await page.locator('[data-test="autocomplete-input"]').press('ControlOrMeta+a');
  await page.locator('[data-test="autocomplete-input"]').fill('TC-');
  await page.getByRole('button', { name: 'TC-Chandler 21-04-2014,' }).click();
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).click();
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('pro');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('KT');
  await page.getByRole('button', { name: 'KT-M-Ezetimibe (10 mg) Stock' }).click();
  await page.locator('.jss34610').first().click();
  await page.locator('tr:nth-child(3) > td:nth-child(4) > .jss34589 > .jss34609 > .jss34610').click();
  await page.locator('.jss34932').click();
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('1');
  await page.getByRole('textbox', { name: 'Nama Deposit' }).fill('Racik > Med > DP');
  await page.getByRole('textbox').nth(4).fill('Rp10.0000');
  await page.getByRole('textbox').nth(4).press('Alt+ArrowLeft');
  await page.getByRole('textbox').nth(4).press('ArrowRight');
  await page.getByRole('textbox').nth(4).press('ArrowRight');
  await page.getByRole('textbox').nth(4).press('Shift+ArrowRight');
  await page.getByRole('textbox').nth(4).press('ArrowRight');
  await page.getByRole('textbox').nth(4).press('Shift+ArrowLeft');
  await page.getByRole('textbox').nth(4).press('Shift+ArrowLeft');
  await page.getByRole('textbox').nth(4).fill('Rp250.000');
  await page.getByRole('textbox', { name: 'Nama Deposit' }).fill('Racik > Med > DP > Pros');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('KT-');
  await page.locator('[data-test="kasir-item-2"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-2"] [data-test="quantity-input"]').fill('1');
  await page.getByRole('textbox', { name: 'Nama Deposit' }).press('ControlOrMeta+ArrowRight');
  await page.locator('[data-test="input-bayar-langsung"]').fill('Rp160.0000');
  await page.locator('[data-test="input-dibayar-oleh-langsung"]').fill('Chan');
  await page.goto('https://app.assist.id/office');
  await page.locator('input[name="invoiceNo"]').fill('INV-T-01');
  await page.locator('input[name="itemName"]').fill('Wifi');
  await page.getByRole('textbox').nth(2).fill('Rp. 25.0000');
  await page.locator('textarea[name="freeText"]').fill('Random notes, test Prod');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('margin');
  await page.goto('https://app.assist.id/apotek');
  await page.locator('[data-test="search-bahan-habis-pakai"]').fill('TC-');
  await page.locator('[data-test="search-bahan-habis-pakai"]').press('Enter');
  await page.locator('[data-test="search-bahan-habis-pakai"]').fill('KT');
  await page.locator('[data-test="search-bahan-habis-pakai"]').press('Enter');
  await page.locator('[data-test="input-barcode"]').fill('KT-B-01');
  await page.locator('[data-test="input-nama-barang"]').fill('Tissue');
  await page.locator('[data-test="input-nama-barang"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-nama-barang"]').fill('KT-Tissue');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('KTM');
  await page.getByRole('textbox', { name: 'Jenis' }).fill('Anti');
  await page.getByRole('textbox', { name: 'Satuan *' }).fill('');
  await page.locator('[data-test="input-stok-barang"]').fill('0300');
  await page.getByRole('textbox', { name: 'Satuan *' }).fill('Pil');
  await page.locator('[data-test="input-dosage"]').fill('S');
  await page.locator('[data-test="input-batch-no"]').fill('BM-01923');
  await page.locator('[data-test="input-harga-beli"]').fill('Rp4000,00');
  await page.locator('[data-test="input-harga-beli"]').press('Tab');
  await page.locator('[data-test="input-harga-otc"]').fill('Rp1.0000');
  await page.locator('[data-test="depot-item-1"] [data-test="input-stok-depot"]').fill('0200');
  await page.locator('[data-test="depot-item-2"] [data-test="input-stok-depot"]').fill('0100');
  await page.goto('https://app.assist.id/office');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill(',argo');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('marg');
  await page.goto('https://app.assist.id/cashier');
  await page.locator('[data-test="autocomplete-input"]').fill('TC-');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('BHP');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('kT');
  await page.locator('[data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="quantity-input"]').fill('1');
  await page.locator('[data-test="input-bayar-langsung"]').fill('Rp2.0000');
  await page.locator('[data-test="input-dibayar-oleh-langsung"]').fill('random ');
  await page.locator('[data-test="input-dibayar-oleh-langsung"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-dibayar-oleh-langsung"]').fill('cek margin');
  await page.locator('html').getByRole('document').press('Escape');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('marg');
  await page.goto('https://app.assist.id/cashier');
  await page.locator('html').getByRole('document').press('Escape');
  await page.locator('html').getByRole('document').press('Escape');
  await page.goto('https://app.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('surat');
  await page.locator('[data-test="input-nama-dokter"]').fill('Dr Random');
  await page.locator('[data-test="input-nama-dokter"]').press('Tab');
  await page.locator('[data-test="input-pemberi-informasi"]').fill('Random passeby');
  await page.locator('[data-test="input-pemberi-informasi"]').press('ArrowLeft');
  await page.locator('[data-test="input-pemberi-informasi"]').press('ArrowLeft');
  await page.locator('[data-test="input-pemberi-informasi"]').fill('Random passerby');
  await page.locator('[data-test="input-pemberi-informasi"]').press('Tab');
  await page.locator('[data-test="input-penerima-informasi"]').fill('Random person');
  await page.locator('[data-test="input-penerima-informasi"]').press('Tab');
  await page.locator('[data-test="input-diagnosis"]').fill('Cough fever');
  await page.locator('[data-test="input-diagnosis"]').press('Tab');
  await page.locator('[data-test="input-dasar-diagnosis"]').fill('Random');
  await page.locator('[data-test="input-dasar-diagnosis"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-dasar-diagnosis"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-tindakan-kedokteran"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-indikasi-tindakan"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-tindakan-kedokteran"]').fill('Random');
  await page.locator('[data-test="input-indikasi-tindakan"]').fill('Random');
  await page.locator('[data-test="input-tata-cara"]').fill('Random');
  await page.locator('[data-test="input-risiko"]').fill('Random');
  await page.locator('[data-test="input-tujuan"]').fill('Random');
  await page.locator('[data-test="input-komplikasi"]').fill('Random');
  await page.locator('[data-test="input-prognosis"]').fill('Random');
  await page.locator('[data-test="input-alternatif-resiko"]').fill('Random');
  await page.locator('[data-test="input-nama-penanggungjawab-section2"]').fill('Wali 1');
  await page.locator('[data-test="input-alamat-penanggung-jawab"]').fill('Alamat Wali');
  await page.locator('[data-test="input-bukti-diri-ktp"]').fill('Jndrfq3e32432rewf');
  await page.locator('[data-test="input-no-tlp-penanggung-jawab"]').fill('09709urijfjwehfw983r');
  await page.locator('[data-test="input-tindakan-medis-text-1"]').fill('Random ijosferf90i-09-=');
  await page.locator('[data-test="input-saksi-name"]').fill('Saksi 1');
  await page.getByRole('textbox', { name: 'Masukkan nama' }).fill('Rnadom Other');
  await page.goto('https://app.assist.id/layanan-tambahan');
  await page.getByRole('textbox').first().fill('KT-Disc-Marleigh');
  await page.getByRole('textbox').nth(1).fill('Rp. 0,000');
  await page.getByRole('textbox').nth(1).press('ArrowLeft');
  await page.getByRole('textbox').nth(1).press('ArrowLeft');
  await page.getByRole('textbox').nth(1).press('ArrowLeft');
  await page.getByRole('textbox').nth(1).press('Shift+ArrowLeft');
  await page.getByRole('textbox').nth(1).fill('Rp. 1.0000,00');
  await page.getByRole('textbox').nth(3).fill('Desc Disc');
  await page.goto('https://app.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('KT-');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').fill('01');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('01');
  await page.locator('[data-test="kasir-item-2"] [data-test="quantity-input"]').fill('01');
  await page.goto('https://app.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('pro');
  await page.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').fill('KT-');
  await page.locator('[data-test="autocomplete-input"]').fill('Abdo');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('resep');
  await page.locator('[data-test="container-medicine-autocomplete-0-prescription"] [data-test="autocomplete-input"]').fill('KT');
  await page.locator('[data-test="container-medicine-autocomplete-0-prescription"] [data-test="autocomplete-input"]').press('ArrowDown');
  await page.locator('[data-test="container-medicine-autocomplete-0-prescription"] [data-test="autocomplete-input"]').press('Enter');
  await page.locator('body').press('Enter');
  await page.locator('[data-test="input-cigna-0-prescription"]').fill('-');
  await page.locator('[data-test="input-quantity-0-prescription"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-quantity-0-prescription"]').fill('2');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('bahan');
  await page.locator('[data-test="autocomplete-input"]').fill('KT');
  await page.locator('[data-test="autocomplete-input"]').press('ArrowDown');
  await page.locator('[data-test="autocomplete-input"]').press('Enter');
  await page.locator('body').press('Tab');
  await page.locator('[data-test="input-itemName-0-disposable"]').press('Tab');
  await page.locator('[data-test="button-clear-itemName-0-disposable"]').press('Tab');
  await page.locator('[data-test="input-quantity-0-disposable"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-quantity-0-disposable"]').fill('2');
  await page.goto('https://app.assist.id/cashier');
  await page.locator('[data-test="kasir-item-2"]').getByRole('button', { name: 'KT-Disc-Marleigh' }).press('Escape');
  await page.goto('https://app.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('pros');
  await page.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').fill('KT-');
  await page.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').press('ArrowDown');
  await page.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').press('Enter');
  await page.goto('https://app.assist.id/settings');
  await page.locator('[data-test="sidebar-item-settings"]').press('ControlOrMeta+f');
  await page.goto('https://app.assist.id/office');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('mor');
  await page.goto('https://app.assist.id/emr');
});