import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.getByRole('img', { name: 'placeholder' }).click();
  await page.locator('div').nth(4).click();
  await page.getByText('Username/EmailPasswordLoginLupa password?V.3.43.0').click();
  await page.locator('div').filter({ hasText: /^Username\/Email$/ }).click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('[data-test="input-password"]').click();
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.goto('https://dev-essensial.assist.id/');
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: 'Baru (Pemilik)' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('Gael []');
  await page.getByRole('textbox').press('ArrowLeft');
  await page.getByRole('textbox').fill('Gael [Clinica Pro]');
  await page.getByRole('textbox').press('Enter');
  await page.getByRole('radio', { name: 'tahun', exact: true }).check();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('10');
  await page.getByRole('spinbutton').press('Enter');
  await page.getByRole('spinbutton').dblclick();
  await page.getByRole('spinbutton').fill('20');
  await page.getByRole('spinbutton').press('Enter');
  await page.getByRole('radio', { name: 'Iya' }).check();
  await page.getByRole('radio', { name: 'Sudah Akreditasi' }).check();
  await page.getByText('Apakah faskes memiliki apotek?').click();
  await page.getByRole('radio', { name: 'Punya apotek (bisa jual untuk' }).check();
  await page.getByRole('radiogroup').filter({ hasText: 'IyaTidak' }).getByLabel('Iya').check();
  await page.getByRole('radiogroup').filter({ hasText: 'IyaTidak' }).getByLabel('Iya').check();
  await page1.locator('body').click();
  await page.getByText('Upload Logo (Optional)').click();
  await page.getByText('Upload Logo (Optional)Click').click();
  await page.locator('body').setInputFiles('icons8-starfish-96.png');
  await page.locator('div').filter({ hasText: 'InformasiNama fasilitas' }).nth(1).click();
  await page.locator('.jss1712').click();
  await page.locator('input[name="kodePos"]').fill('2343');
  await page.locator('input[name="namaJalan"]').fill('Jl Gael no 25');
  await page.locator('input[name="npwpName"]').fill('NPWP Gael');
  await page.locator('input[name="npwp"]').fill('908098098');
  await page.locator('input[name="npwpAddress"]').fill('Alamat NPWP Gael');
  await page.goto('https://dev-essensial.assist.id/');
  await page.locator('div').filter({ hasText: 'Syarat & KetentuanMohon baca' }).nth(1).press('ControlOrMeta+-');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-jabatan"]').fill('QA');
  await page.locator('[data-test="input-email"]').fill('anisasecondacc23@gmail.com');
  await page.locator('[data-test="input-nomor-hp"]').fill('0800-0000-0000  ');
  await page.locator('[data-test="input-nama-lengkap"]').fill('Gesi [Ac24');
  await page.locator('[data-test="input-nama-lengkap"]').press('ArrowLeft');
  await page.locator('[data-test="input-nama-lengkap"]').press('ArrowLeft');
  await page.locator('[data-test="input-nama-lengkap"]').press('ArrowLeft');
  await page.locator('[data-test="input-nama-lengkap"]').press('ArrowRight');
  await page.locator('[data-test="input-nama-lengkap"]').fill('Gesi [Acc24');
  await page.locator('[data-test="input-email"]').fill('anisasecondacc24@gmail.com');
  await page.locator('[data-test="input-jabatan"]').fill('QA');
  await page.locator('[data-test="input-nomor-hp"]').fill('0800-0000-0000  ');
  await page.locator('[data-test="input-nama-hak-akses"]').fill('All Access \'26 Pro');
  await page.locator('[data-test="input-nama"]').fill('GL-Yasmin');
  await page.getByRole('button', { name: 'Upload Photo Profile' }).setInputFiles('A Cat 01.jpg');
  await page.locator('[data-test="input-telepon"]').fill('08000000000');
  await page.locator('[data-test="input-email"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-email"]').fill('anisasecondacc24@gmail.com');
  await page.locator('[data-test="input-noKTP"]').fill('23424242423');
  await page.locator('[data-test="input-registrasiNomor"]').fill('23rwefwfcw34r2');
  await page.locator('[data-test="input-registrasiSIPNomor"]').fill('2wfrewdtf43');
  await page.locator('[data-test="autocomplete-input"]').fill('Sp');
  await page.locator('.jss2499.jss2486.jss2490.jss2500.jss2487.jss2504.jss5523 > .jss2509').first().fill('08:00_');
  await page.locator('.jss2499.jss2486.jss2490.jss2500.jss2487.jss2504.jss5523 > .jss2509').first().press('ControlOrMeta+a');
  await page.locator('.jss2499.jss2486.jss2490.jss2501 > .jss2509').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(3) > .jss5267 > .jss2499 > .jss2509').fill('08:00');
  await page.locator('div:nth-child(4) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(3) > .jss5267 > .jss2499 > .jss2509').fill('08:00');
  await page.locator('div:nth-child(5) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(3) > .jss5267 > .jss2499 > .jss2509').fill('08:00');
  await page.locator('div:nth-child(6) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(3) > .jss5267 > .jss2499 > .jss2509').fill('08:00');
  await page.locator('div:nth-child(7) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(3) > .jss5267 > .jss2499 > .jss2509').fill('08:00');
  await page.locator('div:nth-child(8) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(3) > .jss5267 > .jss2499 > .jss2509').fill('08:00');
  await page.locator('.jss2055 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').first().fill('22:00_');
  await page.locator('.jss2055 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').first().press('ControlOrMeta+a');
  await page.locator('.jss2499.jss2486.jss2490.jss2501 > .jss2509').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').fill('22:00');
  await page.locator('div:nth-child(4) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').fill('22:00');
  await page.locator('div:nth-child(5) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').fill('22:00');
  await page.locator('div:nth-child(6) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').fill('22:00');
  await page.locator('div:nth-child(7) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').fill('22:00');
  await page.locator('div:nth-child(8) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').fill('22:00');
  await page.getByRole('textbox', { name: 'Nama Praktek' }).fill('GL');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Jayda');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Gl-Jayda');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('Alt+ArrowLeft');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('GL-Jayda');
  await page.locator('[data-test="input-nama-ibu"]').fill('Jayda Ibu');
  await page.locator('[data-test="input-no-telepon"]').fill('9089123');
  await page.locator('[data-test="input-no-telepon"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-no-telepon"]').fill('0808080808080');
  await page.locator('input[name="address"]').fill('Chiguayante');
  await page.locator('input[name="address"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('input[name="address"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('input[name="address"]').fill('Jl Chiguayante');
  await page.locator('input[name="address"]').press('ControlOrMeta+ArrowRight');
  await page.locator('input[name="address"]').fill('Jl Chiguayante no 8234');
  await page.locator('input[name="postcode"]').fill('34535');
  await page.locator('button').filter({ hasText: 'Pilih Foto' }).setInputFiles('A Cat 07.png');
  await page.locator('[data-test="input-complaint"]').fill('Sample random');
  await page.goto('https://dev-essensial.assist.id/registration');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('GL-Horne');
  await page.locator('[data-test="input-tempat-lahir"]').fill('Mora');
  await page.locator('input[name="address"]').fill('JL Mora no 345');
  await page3.locator('[data-test="sidebar-item-settings"]').click();
  await page3.getByText('Bridging Satu SehatBridging').click();
  await page3.getByRole('button', { name: 'Printing Template' }).click();
  await page3.getByRole('button', { name: 'Kamar Inap' }).click();
  await page3.locator('[data-test="btn-addRoom"]').click();
  await page3.locator('html').getByRole('document').click();
  await page3.locator('[data-test="input-nameRoom"]').click();
  await page3.locator('[data-test="input-nameRoom"]').fill('GL-R-Fuldatal');
  await page3.locator('#select-type').click();
  await page3.locator('#select-type').click();
  await page3.locator('.jss1679.jss1680').click();
  await page3.locator('[data-test="input-jumlahKamar"]').fill('90');
  await page3.locator('[data-test="input-jumlahKamar"]').press('Tab');
  await page3.locator('[data-test="input-jumlahBed"]').fill('70');
  await page3.locator('[data-test="input-price"]').fill('Rp20.0000');
  await page3.locator('[data-test="input-kodeKamar"]').fill('GL-F');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Horn');
  await page.goto('https://dev-essensial.assist.id/registration');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Horne');
  await page.locator('[data-test="input-complaint"]').fill('Rananp sample');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('GL-Faulkner');
  await page.locator('[data-test="input-tempat-lahir"]').fill('Unzenberg');
  await page.locator('input[name="address"]').fill('JL Unzenberg no 23423');
  await page.locator('input[name="postcode"]').fill('23423');
  await page.locator('[data-test="input-complaint"]').fill('sample ranap persalinan');
});
