import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app.assist.id/login');
  await page.locator('div').filter({ hasText: /^Username\/Email$/ }).click();
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#password').click();
  await page.locator('#password').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '- Clinica Assist (QA)' }).click();
  await page.locator('html').click();
  await expect(page.locator('html')).toBeVisible();
  await page.locator('html').click();
  await page.goto('https://app.assist.id/login');
  await expect(page.getByRole('img', { name: 'placeholder' })).toBeVisible();
  await page.locator('#username').click();
  await page.getByRole('img', { name: 'placeholder' }).click();
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#password').click();
  await page.locator('#password').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '- Clinica Assist (QA)' }).click();
  await page.locator('div').filter({ hasText: 'DashboardClinica Assist' }).nth(5).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.getByRole('button', { name: 'Billing !' }).click();
  await page.locator('[data-test="sidebar-item-profile"]').click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').click();
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').press('ArrowRight');
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').fill('Clinica Assist [Clinica]');
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-deskripsi"]').click();
  await page.locator('[data-test="input-deskripsi"]').fill('Deskripsi');
  await page.locator('[data-test="button-simpan-informasi-dasar"]').click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '- Klinik Tech (QA)' }).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.getByRole('button', { name: 'Billing !' }).click();
  await page.locator('[data-test="sidebar-item-profile"]').click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').click();
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').fill('Klinik Tech []');
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').press('ArrowLeft');
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').fill('Klinik Tech [Clinica Pro]');
  await page.locator('[data-test="input-deskripsi"]').click();
  await page.locator('[data-test="input-deskripsi"]').fill('Deskripsi');
  await page.locator('[data-test="button-simpan-informasi-dasar"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.goto('https://app.assist.id/profile');
  await page.locator('div').nth(1).click();
  await page.locator('div').filter({ hasText: 'ProfileKlinik Tech [Clinica' }).nth(4).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.getByRole('button', { name: 'Billing !' }).click();
  await page.getByRole('button', { name: 'Tambah Berlangganan' }).click();
  await page.getByRole('button', { name: 'Tahun' }).click();
  await page.getByRole('option', { name: '1 Bulan' }).click();
  await page.locator('.jss917').click();
  await page.locator('.jss917').click();
  await page.goto('https://app.assist.id/settings');
  await page.getByRole('textbox').first().fill('KT-Pericardiocentesis');
  await page.getByRole('textbox', { name: 'Nama Praktek' }).fill(' ');
  await page.locator('input[name="nama"]').fill('KT-Nyla');
  await page.locator('input[name="telepon"]').fill('081371075995');
  await page.locator('input[name="noKTP"]').fill('91982942342342');
  await page.getByRole('button', { name: 'Upload Photo Profile' }).setInputFiles('House.jpg');
  await page.locator('input[name="registrasiNomor"]').fill('35435435345');
  await page.locator('input[name="registrasiSIPNomor"]').fill('3543535');
  await page.locator('.jss354.jss341.jss345.jss355.jss342.jss359.jss2948 > .jss364').first().fill('08:00_');
  await page.locator('.jss354.jss341.jss345.jss355.jss342.jss359.jss2948 > .jss364').first().press('ControlOrMeta+a');
  await page.locator('.jss354.jss341.jss345.jss356 > .jss364').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss2143 > .jss354 > .jss364').fill('08:00');
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss2143 > .jss354 > .jss364').fill('08:00');
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss2143 > .jss354 > .jss364').fill('08:00');
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss2143 > .jss354 > .jss364').fill('08:00');
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss2143 > .jss354 > .jss364').fill('08:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss2143 > .jss354 > .jss364').fill('08:00');
  await page.locator('.jss55 > div:nth-child(5) > .jss2143 > .jss354 > .jss364').first().fill('23:00_');
  await page.locator('.jss55 > div:nth-child(5) > .jss2143 > .jss354 > .jss364').first().press('ControlOrMeta+a');
  await page.locator('.jss354.jss341.jss345.jss356 > .jss364').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss2143 > .jss354 > .jss364').fill('23:00');
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss2143 > .jss354 > .jss364').fill('23:00');
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss2143 > .jss354 > .jss364').fill('23:00');
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss2143 > .jss354 > .jss364').fill('23:00');
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss2143 > .jss354 > .jss364').fill('23:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss2143 > .jss354 > .jss364').fill('23:00');
  await page.getByRole('textbox', { name: 'Search Name, STR or SIP' }).fill('KT');
  await page.getByRole('textbox', { name: 'Search Name, STR or SIP' }).press('Escape');
  await page.getByRole('textbox', { name: 'Search Name, STR or SIP' }).fill('KT-');
  await page.getByRole('textbox', { name: 'Search Name, STR or SIP' }).press('Escape');
  await page.getByRole('textbox', { name: 'Search Name, STR or SIP' }).press('Escape');
  await page.getByRole('textbox', { name: 'Nama Praktek' }).fill('KT-');
  await page.getByRole('textbox').first().fill('KT-Leukapheresis');
  await page.getByRole('textbox').nth(1).press('Shift+ArrowLeft');
  await page.getByRole('textbox').nth(1).fill('Rp40.0000');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('kt');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.getByRole('textbox').first().fill('KT-Abdominoplasty');
  await page.getByRole('textbox', { name: 'Nama Praktek' }).fill('KT');
  await page.getByRole('textbox').nth(1).press('Shift+ArrowRight');
  await page.getByRole('textbox').nth(1).fill('Rp50.0000');
  await page.locator('div:nth-child(2) > div > div:nth-child(2) > .jss56.jss89 > .jss4275 > .jss4310 > .jss4320').fill('KT-Tonsillectomy');
  await page.getByRole('textbox', { name: 'Nama Praktek' }).nth(1).fill('Nay');
  await page.locator('div:nth-child(2) > div > div:nth-child(2) > div:nth-child(2) > .jss4275 > .jss4310 > .jss4320').press('Shift+ArrowLeft');
  await page.locator('.jss4310.jss4297.jss4301.jss4319.jss4304.jss4312 > .jss4320').fill('Rp60.0000');
  await page.getByRole('textbox', { name: 'Nama Praktek' }).nth(1).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Nama Praktek' }).nth(1).fill('KT');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('ControlOrMeta+Shift+ArrowRight');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('kt');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.getByRole('textbox').first().fill('KT-');
  await page.locator('[data-test="autocomplete-input"]').fill('KT-');
  await page.getByRole('textbox').first().fill('KT-Leu + Tonsil');
  await page.getByRole('textbox').first().press('Alt+ArrowLeft');
  await page.getByRole('textbox').first().press('Alt+ArrowLeft');
  await page.getByRole('textbox').first().press('Alt+ArrowLeft');
  await page.getByRole('textbox').first().press('ControlOrMeta+ArrowRight');
  await page.getByRole('textbox').first().fill('KT-Leu + Tonsil []');
  await page.getByRole('textbox').first().press('ArrowLeft');
  await page.getByRole('textbox').first().fill('KT-Leu + Tonsil [2x1]');
  await page.getByRole('textbox').nth(4).press('Shift+ArrowLeft');
  await page.getByRole('textbox').nth(4).fill('02');
  await page.locator('div:nth-child(5) > .jss56.jss94 > .jss55 > div:nth-child(2) > .jss4889 > .jss4924 > .jss4934').fill('01');
  await page.getByRole('textbox').nth(1).press('Shift+ArrowLeft');
  await page.getByRole('textbox').nth(1).fill('7.0000');
  await page.getByRole('textbox').nth(1).press('Tab');
  await page.getByRole('textbox').nth(1).fill('70.00');
  await page.getByRole('textbox').nth(1).press('Tab');
  await page.getByRole('textbox').nth(2).press('Shift+ArrowRight');
  await page.getByRole('textbox').nth(2).fill('Rp100.0000');
  await page.locator('div:nth-child(2) > div > div:nth-child(2) > .jss55.jss79 > .jss56.jss91 > .jss4889 > .jss4924 > .jss4934').fill('KT-');
  await page.locator('[data-test="autocomplete-input"]').fill('KT-');
  await page.locator('div:nth-child(2) > div > div:nth-child(2) > .jss55.jss79 > .jss56.jss91 > .jss4889 > .jss4924 > .jss4934').fill('KT-Abdo+Tonsil [1x1]');
  await page.locator('div:nth-child(2) > div > div:nth-child(2) > .jss55.jss79 > .jss56.jss91 > .jss4889 > .jss4924 > .jss4934').press('ArrowLeft');
  await page.locator('.jss4924.jss4911.jss4915.jss4933.jss4918.jss4926 > .jss4934').fill('KT-Paket-Abdo+Tonsil [1x1]');
  await page.locator('div:nth-child(2) > div > div:nth-child(2) > .jss55.jss79 > div:nth-child(4) > .jss56.jss94 > .jss55 > div:nth-child(2) > .jss4889 > .jss4924 > .jss4934').fill('01');
  await page.locator('div:nth-child(2) > div > div:nth-child(2) > .jss55.jss79 > div:nth-child(5) > .jss56.jss94 > .jss55 > div:nth-child(2) > .jss4889 > .jss4924 > .jss4934').fill('1');
  await page.locator('div:nth-child(2) > div > div:nth-child(2) > .jss55.jss79 > div:nth-child(2) > .jss4889 > .jss4924 > .jss4934').fill('90.0000');
  await page.locator('div:nth-child(2) > div > div:nth-child(2) > .jss55.jss79 > div:nth-child(3) > .jss4889 > .jss4924 > .jss4934').fill('Rp090.0000');
  await page.locator('div:nth-child(2) > div > div:nth-child(2) > .jss55.jss79 > div:nth-child(2) > .jss4889 > .jss4924 > .jss4934').fill('9.00');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('k');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('kt');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.locator('div:nth-child(17) > div:nth-child(3) > .jss2143 > .jss354 > #commission').press('Shift+ArrowLeft');
  await page.locator('.jss354.jss341.jss345.jss363.jss348.jss356 > #commission').fill('10%');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('kt');
  await page.locator('div:nth-child(17) > div:nth-child(2) > .jss2143 > .jss354 > .jss3766 > #select').selectOption('price');
  await page.locator('div:nth-child(17) > div:nth-child(3) > .jss2143 > .jss354 > #commission').press('Shift+ArrowRight');
  await page.locator('.jss354.jss341.jss345.jss363.jss348.jss356 > #commission').fill('Rp1.0000');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('kt');
  await page.goto('https://app.assist.id/login');
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#password').fill('12345678');
  await page.goto('https://app.assist.id/settings');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('kt');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('kt-');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.goto('https://app.assist.id/settings');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('kt-');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.goto('https://app.assist.id/apotek');
  await page.locator('input[name="barcode"]').fill('KT-M-01');
  await page.locator('input[name="medName"]').fill('KT-M-Ezetimibe');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('KTM');
  await page.getByRole('textbox', { name: 'Satuan *' }).fill('Pil');
  await page.getByRole('textbox', { name: 'Jenis' }).fill('Anti');
  await page.locator('input[name="dosage"]').fill('10 mg');
  await page.locator('input[name="stockTotalObat"]').press('Shift+ArrowLeft');
  await page.locator('input[name="stockTotalObat"]').fill('300');
  await page.locator('input[name="batchNo"]').fill('234535');
  await page.locator('input[name="batchNo"]').press('ControlOrMeta+a');
  await page.locator('input[name="batchNo"]').fill('BM-0012');
  await page.locator('input[name="buyFee"]').fill('Rp2000,00');
  await page.locator('input[name="buyFee"]').press('Tab');
  await page.getByRole('button').nth(4).press('Tab');
  await page.locator('input[name="sellNormalFee"]').press('Tab');
  await page.getByRole('button').nth(5).press('Tab');
  await page.locator('.jss9291.jss9278.jss9282.jss9300.jss9285.jss9293 > .jss9301').fill('Rp5000');
  await page.locator('.jss9291.jss9278.jss9282.jss9300.jss9285.jss9293 > .jss9301').press('Tab');
  await page.locator('input[name="sellOtcFee"]').fill('Rp1.0000');
  await page.getByRole('cell', { name: 'Nama Depot *   Apotek 1 Type' }).locator('[data-test="input-stok-depot"]').press('Shift+ArrowLeft');
  await page.getByRole('cell', { name: 'Nama Depot *   Apotek 1 Type' }).locator('[data-test="input-stok-depot"]').fill('200');
  await page.getByRole('row', { name: 'Nama Depot *   Gudang Type' }).locator('[data-test="input-stok-depot"]').press('Shift+ArrowLeft');
  await page.getByRole('row', { name: 'Nama Depot *   Gudang Type' }).locator('[data-test="input-stok-depot"]').fill('3000');
  await page.locator('input[name="barcode"]').fill('KT-M-02');
  await page.locator('input[name="medName"]').fill('KT-M-Cinnarizine');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('KTM');
  await page.getByRole('textbox', { name: 'Jenis' }).fill('Ant');
  await page.getByRole('textbox', { name: 'Satuan *' }).fill('Pil');
  await page.locator('input[name="dosage"]').fill('20 mg');
  await page.locator('input[name="stockTotalObat"]').press('Shift+ArrowLeft');
  await page.locator('input[name="stockTotalObat"]').fill('04000');
  await page.locator('input[name="batchNo"]').fill('BM0234234');
  await page.locator('input[name="buyFee"]').fill('Rp30.00,00');
  await page.locator('input[name="buyFee"]').press('Tab');
  await page.getByRole('button').nth(3).press('Tab');
  await page.locator('input[name="sellNormalFee"]').press('Tab');
  await page.getByRole('button').nth(4).press('Tab');
  await page.locator('tr:nth-child(4) > .jss10220 > div > div > div:nth-child(3) > .jss9742 > .jss9291 > .jss9301').fill('Rp5000');
  await page.locator('tr:nth-child(4) > .jss10220 > div > div > div:nth-child(3) > .jss9742 > .jss9291 > .jss9301').press('Tab');
  await page.locator('input[name="sellOtcFee"]').fill('Rp9000');
  const download1Promise = page.waitForEvent('download');
  await page.locator('[data-test="input-cari-obat"]').fill('KT-');
  const download1 = await download1Promise;
  await page.getByRole('button', { name: 'Drag & drop files orbrowse' }).setInputFiles('Import Harga Obat (4).xlsx');
  await page.goto('https://app.assist.id/cashier');
  await page.locator('[data-test="autocomplete-input"]').fill('TC');
  await page.getByRole('textbox', { name: 'Nama Deposit' }).fill('DP Cek Topup');
  await page.getByRole('textbox').nth(4).fill('Rp10.0000');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('KT-');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').press('Shift+ArrowUp');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').fill('0/');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').fill('1');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').press('ArrowDown');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').press('Tab');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('01');
  await page.locator('input[name="tuslahFee"]').fill('Rp2.00');
  await page.locator('input[name="tuslahFee"]').press('Tab');
  await page.locator('input[name="embalaseFee"]').fill('Rp1000');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('KT');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').fill('01');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('01');
  await page.locator('[data-test="autocomplete-input"]').fill('KT-');
  await page.locator('[data-test="autocomplete-input"]').press('ControlOrMeta+a');
  await page.locator('[data-test="autocomplete-input"]').fill('TC');
  await page.getByRole('textbox', { name: 'Nama Deposit' }).fill('DP opup');
  await page.getByRole('textbox', { name: 'Nama Deposit' }).press('Alt+ArrowLeft');
  await page.getByRole('textbox', { name: 'Nama Deposit' }).fill('DP Topup');
  await page.getByRole('textbox').nth(4).fill('Rp1.000.00');
  await page.locator('[data-test="input-bayar-langsung"]').fill('Rp60.0000');
  await page.locator('[data-test="input-dibayar-oleh-langsung"]').fill('Item baru DP');
  await page.locator('[data-test="autocomplete-input"]').fill('TC-');
  await page.getByRole('textbox', { name: 'Nama Deposit' }).fill('DP Topup ');
  await page.getByRole('textbox').nth(4).press('Shift+ArrowRight');
  await page.getByRole('textbox').nth(4).fill('Rp2.0000');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('KT-');
  await page.locator('[data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="quantity-input"]').fill('1');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('KT-');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('01');
  await page.locator('[data-test="autocomplete-input"]').fill('TC-');
  await page.getByRole('textbox', { name: 'Nama Deposit' }).fill('DP ');
  await page.getByRole('textbox').nth(4).fill('Rp1.0000');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('KT-');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').fill('01');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('1');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('Kt-');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('1');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').fill('01');
  await page.getByRole('textbox', { name: 'Nama Deposit' }).fill('DP Pro');
  await page.getByRole('textbox').nth(4).fill('Rp1.0000');
  await page.goto('https://app.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ControlOrMeta+t');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('TC-');
  await page.locator('[data-test="input-complaint"]').fill('Sample');
  await page.goto('https://app.assist.id/registration');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('KT-');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('TC-');
  await page.locator('[data-test="input-complaint"]').fill('Test Ranap');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('TC-');
  await page.locator('[data-test="input-complaint"]').fill('SampleAppt Ranap Persalian');
  await page.locator('[data-test="input-complaint"]').press('ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('ArrowLeft');
  await page.locator('[data-test="input-complaint"]').fill('SampleAppt Ranap Persalinan');
  await page.goto('https://app.assist.id/settings');
  await page.getByRole('textbox', { name: 'Cari Pasien (Nama Lengkap' }).fill('TC-');
  await page.goto('https://app.assist.id/emr');
  await page.locator('[data-test="autocomplete-input"]').fill('Fever with red dots on skin');
  await page.locator('[data-test="autocomplete-input"]').press('ControlOrMeta+a');
  await page.locator('[data-test="autocomplete-input"]').fill('Cough for weeks');
  await page.goto('https://app.assist.id/settings');
  await page.locator('html').getByRole('document').click();
  await page.goto('https://app.assist.id/settings');
  await page.locator('#mainLayoutContainer').click();
  await page.goto('https://app.assist.id/');
  await page.getByRole('img', { name: 'Belanja Obat Termurah' }).click();
  await page.getByRole('img', { name: 'Belanja Obat Termurah' }).click();
  await page.getByRole('button', { name: 'close' }).click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '657399 - Klinik Tech [Clinica' }).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="sidebar-item-emr"]').click();
  await page.getByRole('button', { name: 'GUNAKAN AI' }).click();
  await page.getByRole('button', { name: 'GUNAKAN AI' }).click();
  await page.locator('[data-test="autocomplete-input"]').fill('Batuk seminggu');
});