import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#username').press('Tab');
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.getByText('Username/EmailPasswordLoginLupa password?').click();
  await page.locator('[data-test="login-btn"]').click();
  await page.goto('https://dev-essensial.assist.id/');
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '000101 - Klinik Assist.id [' }).click();
  await page.goto('https://dev-essensial.assist.id/');
  await page.getByRole('button').nth(5).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.locator('[data-test="input-search-staff"]').click();
  await page.locator('[data-test="input-search-staff"]').fill('gesi');
  await page.locator('.jss2909 > .jss1896 > div > .jss2266').first().click();
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('Escape');
  await page.locator('tr:nth-child(2) > td:nth-child(6) > .jss1896 > div > .jss2266').first().click();
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('Escape');
  await page.locator('tr:nth-child(3) > td:nth-child(6) > .jss1896 > div > .jss2266').first().click();
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('Escape');
  await page.getByText('Manajemen StaffLast Update:').click();
  await page.locator('[data-test="button-add-staff"]').click();
  await page.locator('[data-test="input-nama-lengkap"]').fill('Gesi [Acc24');
  await page.locator('[data-test="input-email"]').click();
  await page.locator('[data-test="input-email"]').fill('anisasecondacc24@gmail.com');
  await page.locator('div:nth-child(2) > .jss1897.jss1930.jss3740 > div:nth-child(2) > .jss2891').click();
  await page.locator('[data-test="input-jabatan"]').fill('QA');
  await page.locator('#tanggal-lahir').click();
  await page.getByRole('heading', { name: '2026' }).click();
  await page.getByRole('button', { name: '1998' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Pilih Tipe Akses' }).click();
  await page.locator('#menu-').getByText('All Open [April \'26]').click();
  await page.locator('[data-test="input-nomor-hp"]').click();
  await page.locator('[data-test="input-nomor-hp"]').fill('0800-0000-0000  ');
  await page.locator('div').filter({ hasText: 'Simpan' }).nth(2).click();
  await page.locator('[data-test="button-simpan-staff"]').click();
  await page.locator('[data-test="input-nama-praktek"]').click();
  await page.locator('[data-test="input-nama-praktek"]').fill(' ');
  await page.getByRole('menuitem', { name: 'E-Rosie Howell' }).click();
  await page.locator('[data-test="button-simpan-staff"]').click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '001680 - Wall [Clinica Lite' }).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.locator('[data-test="button-add-staff"]').click();
  await page.locator('.jss6030').click();
  await page.locator('[data-test="input-jabatan"]').fill('QA');
  await page.locator('[data-test="input-email"]').fill('anisasecondacc24@gmail.com');
  await page.locator('[data-test="input-nomor-hp"]').fill('0800-0000-000   ');
  await page.locator('[data-test="input-nama-praktek"]').fill('WL');
  await page.goto('https://dev-essensial.assist.id/office');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('mar');
  await page.getByRole('button', { name: 'Filter Data' }).press('Escape');
  await page.locator('button').filter({ hasText: 'event' }).first().press('Escape');
  await page.locator('[data-test="input-nama-barang"]').fill('WL-HP-Abocath');
  await page.locator('[data-test="input-stok-barang"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-stok-barang"]').fill('400');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('WLM');
  await page.getByRole('textbox', { name: 'Jenis' }).fill('Ant');
  await page.getByRole('textbox', { name: 'Satuan *' }).fill('Sachet');
  await page.locator('[data-test="input-dosage"]').fill('S');
  await page.locator('[data-test="input-batch-no"]').fill('BCH012');
  await page.locator('[data-test="input-harga-beli"]').fill('Rp2.0000,00');
  await page.locator('[data-test="input-harga-otc"]').fill('Rp400.00');
  await page.locator('[data-test="input-harga-beli"]').press('ArrowRight');
  await page.locator('[data-test="input-harga-beli"]').press('Shift+ArrowRight');
  await page.locator('[data-test="input-harga-beli"]').fill('Rp2.000,00');
  await page.locator('[data-test="input-harga-otc"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-harga-otc"]').fill('Rp4.000');
  await page.locator('[data-test="input-nama-barang"]').fill('WL-HP-Lancet');
  await page.locator('[data-test="input-stok-barang"]').fill('0200');
  await page.locator('[data-test="input-dosage"]').fill('M');
  await page.getByRole('textbox', { name: 'Jenis' }).fill('Anti');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('WLM');
  await page.locator('[data-test="input-batch-no"]').fill('BCH10092');
  await page.locator('[data-test="input-harga-beli"]').fill('Rp30.00,00');
  await page.locator('[data-test="input-harga-otc"]').fill('Rp50.00');
  await page.getByRole('textbox', { name: 'Satuan *' }).fill('Sache');
  await page.goto('https://dev-essensial.assist.id/office');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('marg');
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('HP');
  await page.locator('[data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="quantity-input"]').fill('2');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('HP');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').press('Shift+ArrowRight');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('3');
  await page.locator('[data-test="input-bayar-langsung"]').fill('Rp250.00');
  await page.locator('[data-test="input-dibayar-oleh-langsung"]').fill('Sample random');
  await page.goto('https://dev-essensial.assist.id/office');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('morbid');
  await page.locator('html').getByRole('document').press('Escape');
  await page.goto('https://dev-essensial.assist.id/registration');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('WL-');
  await page.locator('[data-test="input-complaint"]').fill('Cek morbid pasien Ranap');
  await page.goto('https://dev-essensial.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('ca');
  await page.locator('[data-test="input-subjectives"]').fill('Subjek 01');
  await page.locator('[data-test="input-leher-modal"]').fill('Norm');
  await page.locator('[data-test="input-leher-modal"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-leher-modal"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-mata-kiri-modal"]').fill('Norm');
  await page.locator('[data-test="input-tenggorokan-modal"]').fill('Norm');
  await page.locator('[data-test="input-tulang-belakang-modal"]').fill('Norm');
  await page.locator('[data-test="input-ekstrimitas-modal"]').fill('Norm');
  await page.locator('[data-test="input-anus-modal"]').fill('Norm');
  await page.locator('[data-test="input-anus-modal"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-anus-modal"]').fill('');
  await page.locator('[data-test="input-paru-modal"]').fill('Norm');
  await page.locator('[data-test="autocomplete-input"]').fill('Fev');
  await page.locator('[data-test="input-plans"]').fill('PLan 01');
  await page.locator('[data-test="input-catatan-bebas"]').fill('Random');
  await page.locator('[data-test="autocomplete-input"]').fill('Coug');
  await page.getByRole('textbox', { name: 'Cari Diagnosa Sekunder' }).fill('sne');
  await page.getByRole('textbox', { name: 'Tambah Prosedur' }).fill('wl-');
  await page.getByRole('textbox', { name: 'Tambah Prosedur' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Tambah Prosedur' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Tambah Prosedur' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Tambah Prosedur' }).fill('WL-');
  await page.getByRole('textbox', { name: 'Tambah Prosedur' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Tambah Prosedur' }).fill('W');
  await page.getByRole('textbox').fill('Random');
  await page.getByRole('textbox').press('ControlOrMeta+a');
  await page.getByRole('textbox').press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Tambah Obat' }).fill('Random');
  await page.getByRole('textbox', { name: 'Tambah Obat' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Tambah Obat' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Tambah Obat' }).fill('WL');
  await page.getByRole('textbox').first().fill('Random');
  await page.getByRole('textbox').filter({ hasText: /^$/ }).fill('Random');
  await page.goto('https://dev-essensial.assist.id/office');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('mor');
  await page.goto('https://dev-essensial.assist.id/registration');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('WL-Alvarez');
  await page.locator('[data-test="input-nama-ibu"]').fill('Lukhovitsy Ibu');
  await page.locator('input[name="address"]').fill('Jl. Lukhovitsy no 23242');
  await page.locator('input[name="postcode"]').fill('324234');
  await page.locator('[data-test="input-complaint"]').fill('cek morbid ranap persalinan');
  await page.goto('https://dev-essensial.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('dia');
  await page.locator('[data-test="autocomplete-input"]').fill('Blood');
  await page.locator('[data-test="autocomplete-input"]').press('ArrowUp');
  await page.locator('[data-test="autocomplete-input"]').press('ArrowDown');
  await page.locator('[data-test="autocomplete-input"]').press('ArrowDown');
  await page.locator('[data-test="autocomplete-input"]').press('ArrowDown');
  await page.locator('[data-test="autocomplete-input"]').fill('Skin');
  await page1.getByRole('button', { name: 'Laporan' }).click();
  await page1.locator('button').filter({ hasText: 'Keuangan' }).click();
  await page1.getByRole('button', { name: 'Operasional' }).click();
  await page1.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page1.getByRole('textbox', { name: 'Cari Laporan' }).click();
  await page1.getByRole('textbox', { name: 'Cari Laporan' }).fill('morbi');
  await page1.getByRole('heading', { name: 'Laporan Morbid' }).click();
  await page1.getByRole('button', { name: '5', exact: true }).click();
  await page1.getByRole('option', { name: '10' }).click();
  await page.getByRole('textbox', { name: 'Cari Diagnosa Sekunder' }).fill('coug');
  await page.getByRole('textbox', { name: 'Tambah Prosedur' }).fill('');
  await page1.getByText('Rows per page:101-3 of').click();
  await page1.locator('html').getByRole('document').press('Escape');
  await page1.locator('[data-test="sidebar-item-settings"]').click();
  await page1.getByRole('button', { name: 'Katalog Harga Prosedur' }).click();
  await page.getByRole('textbox', { name: 'Tambah Prosedur' }).fill('WL-P-Master');
  await page.getByRole('textbox', { name: 'Tambah Prosedur' }).press('Enter');
  await page.getByRole('textbox', { name: 'Tambah Prosedur' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Tambah Prosedur' }).fill('');
  await page.getByRole('textbox').fill('Random');
  await page.getByRole('textbox', { name: 'Tambah Obat' }).fill('WL-');
  await page.getByRole('textbox').first().fill('Random');
  await page.getByRole('textbox').first().press('ControlOrMeta+a');
  await page.getByRole('textbox').filter({ hasText: 'Random' }).press('ControlOrMeta+c');
  await page.getByRole('textbox').filter({ hasText: /^$/ }).fill('Random');
  await page1.locator('[data-test="sidebar-item-office"]').click();
  await page1.getByRole('button', { name: 'Laporan' }).click();
  await page1.locator('button').filter({ hasText: 'Keuangan' }).click();
  await page1.getByRole('button', { name: 'Operasional' }).click();
  await page1.getByRole('textbox', { name: 'Cari Laporan' }).click();
  await page1.getByRole('textbox', { name: 'Cari Laporan' }).fill('mor');
  await page1.locator('div').filter({ hasText: /^Laporan Morbid$/ }).nth(1).click();
  await page1.locator('div').filter({ hasText: 'Laporan MorbidShow' }).nth(2).click();
  await page1.locator('tr:nth-child(5) > td:nth-child(32)').click();
  await page1.locator('div').filter({ hasText: 'Laporan MorbidShow' }).nth(2).click();
  await page1.locator('div').filter({ hasText: 'Laporan MorbidShow' }).nth(2).click();
  await page1.locator('div').filter({ hasText: 'Laporan MorbidShow' }).nth(2).click();
  await page1.locator('div').filter({ hasText: 'Laporan MorbidShow' }).nth(2).click();
  await page1.locator('div').filter({ hasText: 'Laporan MorbidShow' }).nth(2).click();
  await page1.locator('html').getByRole('document').press('Escape');
  await page1.locator('[data-test="sidebar-item-settings"]').click();
  await page1.getByRole('button', { name: 'Surat Menyurat' }).click();
  await page1.getByText('Wall [Clinica Lite V2]Jl Wall').click();
  await page1.locator('[data-test="input-letterNumber"]').click();
  await page1.locator('[data-test="input-letterNumber"]').fill('1234447777');
  await page1.locator('[data-test="parent-autocomplete-cariPasien"] [data-test="autocomplete-input"]').click();
  await page1.locator('[data-test="parent-autocomplete-cariPasien"] [data-test="autocomplete-input"]').fill('WL-');
  await page1.getByRole('button', { name: 'WL-Dominik' }).click();
  await page1.locator('div').filter({ hasText: /^\+ Diagnosa$/ }).nth(1).click();
  await page1.locator('[data-test="parent-autocomplete-diagnosa-1780630260790"] [data-test="autocomplete-input"]').fill('Rando');
  await page1.locator('[data-test="parent-autocomplete-diagnosa-1780630260790"] [data-test="autocomplete-input"]').press('ControlOrMeta+a');
  await page1.locator('[data-test="parent-autocomplete-diagnosa-1780630260790"] [data-test="autocomplete-input"]').fill('Cov');
  await page1.getByRole('menuitem', { name: 'U07.1 COVID-19, virus' }).click();
  await page1.locator('[data-test="parent-autocomplete-diagnosa-1780630261889"] [data-test="autocomplete-input"]').click();
  await page1.locator('[data-test="parent-autocomplete-diagnosa-1780630261889"] [data-test="autocomplete-input"]').fill('Co');
  await page1.getByText('A04.2 Enteroinvasive').click();
  await page1.getByRole('menuitem', { name: 'A04.2 Enteroinvasive' }).click();
  await page1.locator('[data-test="input-diagnosa-1780630261889"]').click();
  await page1.locator('[data-test="input-hari"]').click();
  await page1.locator('[data-test="input-hari"]').fill('4');
  await page1.getByRole('textbox', { name: 'Sampai' }).click();
  await page1.locator('div:nth-child(3) > div:nth-child(5)').first().click();
  await page1.getByRole('button', { name: 'OK' }).click();
  await page1.getByRole('button', { name: 'Digital Signature' }).click();
  await page1.getByRole('textbox', { name: 'Dokter yang memeriksa' }).click();
  await page1.getByRole('textbox', { name: 'Dokter yang memeriksa' }).fill('Random dokter');
  await page1.getByRole('button', { name: 'Print/Cetak' }).nth(1).click();
  await page1.locator('html').getByRole('document').click();
  await page1.goto('https://dev-essensial.assist.id/emr');
  await page1.getByRole('textbox', { name: 'Cari Pasien / No MR / No Ktp' }).fill('Dominik');
  await page1.locator('html').getByRole('document').click();
  await page1.locator('html').getByRole('document').click();
  await page1.locator('div:nth-child(3) > .jss4342').click();
  await page1.getByRole('button', { name: '3 star' }).nth(2).click();
  await page1.getByRole('button').first().click();
  await page1.locator('.jss4185 > .jss454').first().press('Escape');
  await page1.locator('div').filter({ hasText: /^Nomor HP$/ }).click();
  await page1.locator('div').filter({ hasText: 'WL-DominikMR00000002 · Laki' }).nth(5).click();
  await page1.getByText('+Tambah DiagnosaPrint Rekam').click();
  await page1.getByText('TimelineRecordCPPT').click();
  await page1.getByRole('button', { name: '04 Jun 2026 Poli Umum dengan' }).click();
  await page1.locator('.jss4154').click();
  await page1.locator('body').press('Escape');
  await page1.getByRole('cell', { name: 'Surat Keterangan Sakit' }).click();
  await page1.getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page1.locator('body').press('Escape');
  await page1.getByRole('cell', { name: '-06-2026' }).nth(1).click();
  await page1.locator('div').filter({ hasText: 'SemuaWL-Dominik' }).nth(5).click();
  await page1.locator('[data-test="sidebar-item-registrasi"]').click();
  await page1.locator('div').filter({ hasText: /^Rawat Jalan Poli$/ }).nth(3).click();
  await page1.locator('div').filter({ hasText: /^Rawat Jalan Poli$/ }).nth(3).click();
  await page1.locator('.jss56.jss91 > button').click();
  await page1.getByRole('button').filter({ hasText: 'event' }).nth(1).click();
  await page1.getByRole('button', { name: '2' }).first().click();
  await page1.getByRole('button', { name: 'OK' }).click();
  await page1.locator('button').filter({ hasText: 'event' }).first().press('Escape');
  await page1.getByRole('button').filter({ hasText: 'event' }).nth(1).press('Escape');
  await page1.locator('[data-test="sidebar-item-rawat-jalan"]').click();
  await page1.locator('div').filter({ hasText: 'Seluruh Dokterdr. WL-Issac' }).nth(5).click();
  await page1.locator('body').press('Escape');
  await page1.locator('#add11030').click();
  await page1.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('WL-');
  await page1.getByRole('button', { name: 'WL-Dominik 03-06-2004,' }).click();
  await page1.locator('[data-test="input-complaint"]').click();
  await page1.locator('[data-test="input-complaint"]').fill('cek Surat');
  await page1.getByRole('button', { name: 'Simpan' }).click();
  await page1.getByRole('button', { name: 'WL-Dominik' }).first().click();
  await page1.getByRole('button', { name: 'confirmed' }).click();
  await page1.getByRole('button', { name: 'waiting' }).click();
  await page1.getByRole('button', { name: 'waiting' }).click();
  await page1.getByRole('button', { name: 'engaged' }).click();
  await page1.getByRole('button', { name: 'waiting' }).click();
  await page1.getByRole('textbox', { name: 'Alasan Batal' }).fill('random again');
  await page1.getByRole('textbox', { name: 'Cari fitur' }).fill('surat');
  await page1.locator('[data-test="input-nama-dokter"]').fill('Dokter random');
  await page1.locator('[data-test="input-nama-dokter"]').press('Tab');
  await page1.locator('[data-test="input-pemberi-informasi"]').fill('Tersedia di EMR Engaged');
  await page1.locator('[data-test="input-pemberi-informasi"]').press('ControlOrMeta+a');
  await page1.locator('[data-test="input-pemberi-informasi"]').fill('Random');
  await page1.locator('[data-test="input-pemberi-informasi"]').press('ControlOrMeta+a');
  await page1.locator('[data-test="input-pemberi-informasi"]').press('ControlOrMeta+c');
  await page1.locator('[data-test="input-pemberi-informasi"]').press('ControlOrMeta+c');
  await page1.locator('[data-test="input-penerima-informasi"]').fill('Random');
  await page1.locator('[data-test="input-diagnosis"]').fill('Random');
  await page1.locator('[data-test="input-dasar-diagnosis"]').fill('Random');
  await page1.locator('[data-test="input-tindakan-kedokteran"]').fill('Random');
  await page1.locator('[data-test="input-indikasi-tindakan"]').fill('Random');
  await page1.locator('[data-test="input-tata-cara"]').fill('Random');
  await page1.locator('[data-test="input-tujuan"]').fill('Random');
  await page1.locator('[data-test="input-risiko"]').fill('Random');
  await page1.locator('[data-test="input-komplikasi"]').fill('Random');
  await page1.locator('[data-test="input-prognosis"]').fill('Random');
  await page1.locator('[data-test="input-alternatif-resiko"]').fill('Random');
  await page1.locator('[data-test="input-nama-penanggungjawab-section2"]').fill('Random');
  await page1.locator('[data-test="input-alamat-penanggung-jawab"]').fill('Random');
  await page1.locator('[data-test="input-bukti-diri-ktp"]').fill('Random');
  await page1.locator('[data-test="input-no-tlp-penanggung-jawab"]').fill('12432424324');
  await page1.locator('[data-test="input-tindakan-medis-text-1"]').fill('Random');
  await page1.locator('[data-test="input-saksi-name"]').fill('random');
  await page1.getByRole('textbox', { name: 'Masukkan nama' }).fill('Random');
  await page1.goto('https://dev-essensial.assist.id/cashier');
  await page1.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('wl-');
  await page1.getByRole('button').nth(4).press('Escape');
  await page1.goto('https://dev-essensial.assist.id/cashier');
  await page1.getByRole('textbox', { name: 'Cari tindakan atau obat' }).fill('wl-');
  const page2Promise = page1.waitForEvent('popup');
  await page1.goto('https://dev-essensial.assist.id/layanan-tambahan');
  const page2 = await page2Promise;
  await page2.goto('https://dev-adv-report.assist.id/login');
  await page2.locator('.w-full.pt-4').click();
  await page2.getByRole('img', { name: 'Dashboard metrics preview' }).click();
  await page2.locator('body').press('Escape');
  await page2.locator('body').press('Escape');
  await page2.locator('body').press('Escape');
  await page.goto('https://dev-essensial.assist.id/layanan-tambahan');
  await page.getByRole('textbox', { name: 'Cari nama add on' }).fill('ai');
  await page.locator('html').getByRole('document').press('Escape');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('cata');
  await page.locator('li').filter({ hasText: 'Tambah Catatan Dokter' }).press('Escape');
  await page.locator('[data-test="emrAddBtn"]').press('ControlOrMeta+f');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('pro');
  await page.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').fill('WL-');
  await page.locator('[data-test="autocomplete-input"]').fill('Anti');
  await page.goto('https://dev-essensial.assist.id/assist-universe');
  await page.getByText('Selamat datang di Assist').click();
  await page.getByRole('button', { name: 'Skip' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('img', { name: 'Solusi 4' }).click({
    button: 'right'
  });
  await page.getByRole('img', { name: 'Solusi 4' }).click({
    button: 'right'
  });
  await page.getByRole('img', { name: 'Solusi 4' }).click({
    button: 'right'
  });
  await page.locator('body').press('ControlOrMeta+ ');
  await page.locator('body').press('ControlOrMeta+ArrowDown');
  await page.locator('div').filter({ hasText: 'Tambah Vital Sign' }).nth(5).click();
  await page.locator('[data-test="sidebar-item-registrasi"]').click();
  await page.locator('.jss55.jss56.jss77').click();
  await page.locator('div').filter({ hasText: /^Export$/ }).first().click();
  await page.locator('#mainLayoutContainer').click();
  await page.locator('#mainLayoutContainer').click();
  await page.getByRole('option', { name: 'Semua Metode Pembayaran' }).press('Escape');
  await page.getByRole('option', { name: 'Asuransi' }).click();
  await page.getByText('Asuransi').press('Escape');
});