import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app.assist.id/login');
  await page.getByRole('img', { name: 'placeholder' }).click();
  await page.getByRole('img', { name: 'Assist.id' }).click();
  await page.locator('div').filter({ hasText: /^Username\/Email$/ }).click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#password').click();
  await page.locator('#password').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.getByRole('dialog').getByRole('button').click();
  await page.getByRole('img', { name: 'Coba Zesta Gratis Sekarang!' }).click();
  await page.getByRole('button', { name: 'close' }).click();
  await page.locator('[data-test="sidebar-item-rawat-jalan"]').click();
  await page.locator('[data-test="sidebar-item-registrasi"]').click();
  await page.locator('#mainLayoutContainer').click();
  await page.locator('.jss1947').click();
  await page.goto('https://app.assist.id/settings');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('CC-');
  await page.getByRole('button', { name: 'Drag & drop files orbrowse' }).setInputFiles('Import Katalog Harga Prosedur (6).xlsx');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('cc');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('cc-');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.goto('https://app.assist.id/cashier');
  await page.getByRole('spinbutton').fill('2');
  await page.getByRole('textbox', { name: 'Satuan' }).fill('Pil');
  await page.locator('textarea[name="prescriptions.0.cigna"]').fill('Sample Racik Kasir');
  await page.getByRole('textbox', { name: 'Nama Obat' }).fill('');
  await page.locator('input[name="prescriptions.0.materialPrescript.0.numerator"]').fill('1');
  await page.locator('input[name="prescriptions.0.materialPrescript.0.denominator"]').fill('2');
  await page.locator('textarea[name="prescriptions.0.materialPrescript.0.note"]').fill('random racik');
  await page.getByRole('textbox', { name: 'Nama Obat' }).fill(' ');
  await page.locator('input[name="prescriptions.0.materialPrescript.1.numerator"]').fill('3');
  await page.locator('input[name="prescriptions.0.materialPrescript.1.numerator"]').press('Tab');
  await page.locator('input[name="prescriptions.0.materialPrescript.1.denominator"]').fill('1');
  await page.locator('textarea[name="prescriptions.0.materialPrescript.1.note"]').fill('random');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('cc');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('1');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('CC-');
  await page.locator('[data-test="kasir-item-2"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-2"] [data-test="quantity-input"]').fill('1');
  await page.locator('[data-test="input-bayar-langsung"]').fill('Rp30.0000');
  await page.locator('[data-test="input-dibayar-oleh-langsung"]').fill('Random pasien OTC');
  await page.goto('https://app.assist.id/settings');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('cc');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('cc-');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.locator('#select').first().press('ControlOrMeta+f');
  await page.locator('div:nth-child(34) > div:nth-child(3) > .jss9641 > .jss4331 > #commission').press('Shift+ArrowLeft');
  await page.locator('.jss4331.jss4318.jss4322.jss4340.jss4325.jss4333 > #commission').fill('20%');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('cc-');
  await page.locator('div:nth-child(34) > div:nth-child(2) > .jss9641 > .jss4331 > .jss9710 > #select').selectOption('price');
  await page.locator('.jss4331.jss4318.jss4322.jss4340.jss4325.jss4333 > #commission').fill('Rp');
  await page.locator('div:nth-child(34) > div:nth-child(3) > .jss9641 > .jss4331 > #commission').fill('Rp10.0000');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('cc-');
  await page.goto('https://app.assist.id/office');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('margi');
  await page.getByRole('button', { name: 'Filter Data' }).press('Escape');
  await page.locator('html').getByRole('document').press('Escape');
  await page.goto('https://app.assist.id/office');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('morbi');
  await page.goto('https://app.assist.id/accreditation');
  await page.locator('#gambar').setInputFiles('1776227313000_Cat 07.jpg');
  await page.locator('#dokumenBukti').setInputFiles('1778007998130_Cat 11.jpg');
  await page.goto('https://app.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('surat');
  await page.locator('[data-test="input-nama-dokter"]').fill('Random notes');
  await page.locator('[data-test="input-nama-dokter"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-nama-dokter"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-pemberi-informasi"]').fill('Random notes');
  await page.locator('[data-test="input-penerima-informasi"]').fill('Random notes');
  await page.locator('[data-test="input-diagnosis"]').fill('Random notes');
  await page.locator('[data-test="input-dasar-diagnosis"]').fill('Random notes');
  await page.locator('[data-test="input-tindakan-kedokteran"]').fill('Random notes');
  await page.locator('[data-test="input-indikasi-tindakan"]').fill('Random notes');
  await page.locator('[data-test="input-tata-cara"]').fill('Random notes');
  await page.locator('[data-test="input-tujuan"]').fill('Random notes');
  await page.locator('[data-test="input-risiko"]').fill('Random notes');
  await page.locator('[data-test="input-prognosis"]').fill('Random notes');
  await page.locator('[data-test="input-komplikasi"]').fill('Random notes');
  await page.locator('[data-test="input-alternatif-resiko"]').fill('Random notes');
  await page.locator('[data-test="input-nama-penanggungjawab-section2"]').fill('Giova');
  await page.locator('[data-test="input-alamat-penanggung-jawab"]').fill('Random alamat');
  await page.locator('[data-test="input-bukti-diri-ktp"]').fill('23424');
  await page.locator('[data-test="input-no-tlp-penanggung-jawab"]').fill('2342342dfsserw');
  await page.locator('[data-test="input-tindakan-medis-text-1"]').fill('Random notes');
  await page.locator('[data-test="input-saksi-name"]').fill('Saksi 23');
  await page.goto('https://app.assist.id/registration');
  await page.getByRole('dialog').getByRole('button').click();
  await page.locator('#mainLayoutContainer').click();
  await page.locator('[data-test="sidebar-item-emr"]').click();
  await page.getByRole('textbox', { name: 'Cari Pasien / No MR / No Ktp' }).click();
  await page.getByRole('textbox', { name: 'Cari Pasien / No MR / No Ktp' }).fill('Giova');
  await page.getByRole('button', { name: 'CC-Giovanna 21-04-1970,' }).click();
  await page.locator('section').filter({ hasText: '22Mei 2026Poli Umum dengan dr' }).click();
  await page.goto('https://app.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('CC-');
  await page.locator('[data-test="input-complaint"]').fill('random add Surat di REgs');
  await page.locator('[data-test="input-complaint"]').press('ArrowLeft');
  await page.locator('[data-test="input-complaint"]').fill('random add Surat di eRgs');
  await page.locator('[data-test="input-complaint"]').press('ControlOrMeta+ArrowRight');
  await page.locator('[data-test="input-complaint"]').press('ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-complaint"]').fill('random add Surat di regs');
  await page.locator('[data-test="input-complaint"]').press('ArrowRight');
  await page.locator('[data-test="input-complaint"]').fill('random add Surat di regis');
});