import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#username').press('Tab');
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="input-password"]').press('Enter');
  await page.locator('[data-test="login-btn"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: 'Baru (Pemilik)' }).click();
  await page.goto('https://dev-essensial.assist.id/wizard');
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('Pure annisa.ghaisani@assist.id');
  await page.getByRole('textbox').press('ControlOrMeta+z');
  await page.getByRole('textbox').fill('Pure Nixon []');
  await page.getByRole('textbox').press('ArrowLeft');
  await page.getByRole('textbox').fill('Pure Nixon [Privata]');
  await page.getByRole('textbox').press('Enter');
  await page.getByRole('radio', { name: 'Dibawah satu tahun.' }).check();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('3');
  await page.getByRole('spinbutton').press('Enter');
  await page.getByRole('radio', { name: 'Iya' }).check();
  await page.getByText('Sudah Akreditasi').click();
  await page.getByRole('radio', { name: 'Punya apotek (bisa jual untuk' }).check();
  await page.getByRole('radiogroup').filter({ hasText: 'IyaTidak' }).getByLabel('Iya').check();
  await page.getByRole('radiogroup').filter({ hasText: 'IyaTidak' }).getByLabel('Iya').check();
  await page.getByText('Upload Logo (Optional)').click();
  await page.getByRole('img', { name: 'Pic here' }).click();
  await page.locator('body').setInputFiles('icons8-windy-weather-100.png');
  await page.locator('#select-selectedFaskesType').click();
  await page.getByRole('option', { name: 'Klinik Pratama' }).click();
  await page.getByRole('button', { name: 'Klinik Pratama' }).click();
  await page.getByRole('option', { name: 'Klinik Utama' }).click();
  await page.locator('#select-selectedProvince').click();
  await page.getByRole('option', { name: 'Sumatera Barat' }).click();
  await page.locator('#select-selectedKabupaten').click();
  await page.getByRole('option', { name: 'Kab. Sijunjung' }).click();
  await page.locator('#select-selectedKecamatan').click();
  await page.getByRole('option', { name: 'Koto Tujuh' }).click();
  await page.locator('input[name="kodePos"]').click();
  await page.locator('input[name="kodePos"]').fill('23424');
  await page.locator('input[name="namaJalan"]').click();
  await page.locator('input[name="namaJalan"]').fill('Jl Nixon no1232432');
  await page.locator('input[name="namaJalan"]').click();
  await page.locator('input[name="namaJalan"]').click();
  await page.locator('input[name="namaJalan"]').fill('Jl Nixon no1232432');
  await page.locator('input[name="namaJalan"]').press('Alt+ArrowLeft');
  await page.locator('input[name="namaJalan"]').press('ArrowRight');
  await page.locator('input[name="namaJalan"]').press('ArrowRight');
  await page.locator('input[name="namaJalan"]').fill('Jl Nixon no.1232432');
  await page.locator('input[name="npwpName"]').click();
  await page.locator('input[name="npwpName"]').fill('NPWP Nixon');
  await page.locator('input[name="npwpName"]').press('Tab');
  await page.locator('input[name="npwp"]').fill('2342323424');
  await page.locator('input[name="npwp"]').press('Tab');
  await page.locator('input[name="npwpAddress"]').fill('Alamat Nixon');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.goto('https://dev-essensial.assist.id/wizard');
});