import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('div').filter({ hasText: /^Username\/Email$/ }).click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('[data-test="input-password"]').click();
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="input-password"]').press('Enter');
  await page.locator('[data-test="login-btn"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '001587 - Pure Blair [Clinica' }).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.locator('[data-test="button-add-staff"]').click();
  await page.locator('[data-test="input-nama-lengkap"]').fill('Gesi [Griffith]');
  await page.locator('[data-test="input-jabatan"]').click();
  await page.locator('[data-test="input-jabatan"]').fill('QA');
  await page.locator('[data-test="input-jabatan"]').click();
  await page.locator('[data-test="input-email"]').click();
  await page.locator('[data-test="input-email"]').fill('griffithwhales@gmail.com');
  await page.getByRole('button').nth(1).click();
  await page.getByRole('heading', { name: '2026' }).click();
  await page.getByRole('button', { name: '1996' }).click();
  await page.getByRole('heading', { name: '1996' }).click();
  await page.getByRole('button', { name: '1997' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Nama Lengkap *Tanggal Lahir *Jabatan *Tipe Akses *Pilih Tipe AksesAlamat Email').click();
  await page.getByRole('button', { name: 'Pilih Tipe Akses' }).click();
  await page.locator('#menu-').getByText('All Access \'').click();
  await page.locator('[data-test="input-nomor-hp"]').click();
  await page.locator('[data-test="input-nomor-hp"]').fill('0801-2308-123   ');
  await page.locator('[data-test="input-nama-praktek"]').click();
  await page.locator('[data-test="input-nama-praktek"]').fill('nas');
  await page.getByRole('menuitem', { name: 'PB-Nash' }).click();
  await page.locator('[data-test="input-nama-lengkap"]').click();
  await page.locator('[data-test="input-nama-lengkap"]').press('ArrowLeft');
  await page.locator('[data-test="input-nama-lengkap"]').fill('Gesi [Griffith | Nash]');
  await page.locator('[data-test="button-simpan-staff"]').click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.locator('#btnAccount').click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
  await page.locator('div').filter({ hasText: /^Username\/Email$/ }).click();
  await page.locator('#username').fill('griffithwhales@gmail.com');
  await page.locator('#username').click();
  await page.locator('[data-test="input-password"]').click();
  await page.locator('[data-test="input-password"]').click();
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="input-password"]').press('Enter');
  await page.locator('[data-test="login-btn"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '- Pure Blair [Clinica] (QA)' }).click();
  await page.getByRole('button', { name: 'Nanti Saja' }).click();
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).click();
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).fill('Nanti saja');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.locator('[data-test="input-search-staff"]').click();
  await page.locator('[data-test="input-search-staff"]').fill('sudah berhasil invited ke klinik tujuan');
  await page.locator('[data-test="input-search-staff"]').press('Enter');
});