import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').click();
  await page.locator('#username').fill('anisasecondacc24@gmail.com');
  await page.locator('[data-test="input-password"]').click();
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="input-password"]').press('Enter');
  await page.locator('[data-test="login-btn"]').click();
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('.jss218.jss236 > .jss403').click();
  await page.getByRole('button', { name: 'close' }).click();
  await page.getByRole('button', { name: 'Tambah Berlangganan' }).click();
  await page.getByRole('button', { name: 'Tahun' }).click();
  await page.getByRole('option', { name: '1 Bulan' }).click();
  await page.getByRole('button', { name: 'Clinica Lite' }).click();
  await page.getByRole('option', { name: 'Clinica Lite' }).press('ControlOrMeta+f');
  await page.getByRole('option', { name: 'Clinica Lite' }).click();
  await page.getByRole('button', { name: 'Lanjutkan Pembayaran' }).click();
  await page.getByText('Bayar BillingApakah Anda').click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.getByRole('link', { name: 'banklogo BCA virtual account' }).click();
  await page.getByText('Copy').click();
  await page1.locator('html').click();
  await page.getByText('Copy').click();
  await page1.locator('#inputMerchantId').click();
  await page1.locator('#inputMerchantId').fill('22646207665397678440124');
  await page1.getByRole('button', { name: 'Inquire' }).click();
  await page1.getByRole('button', { name: 'Pay' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Nanti Saja' }).click();
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).click();
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).fill('n');
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).fill('nANTI');
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).fill('Nanti saja');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.getByRole('button', { name: 'Billing !' }).click();
});