import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#username').press('Tab');
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.locator('div').filter({ hasText: 'Ganti Password Akun Anda Dulu' }).nth(1).click();
  await page.locator('.jss480.jss474.jss932').click();
  await page.getByRole('button', { name: 'close' }).click();
  await page.getByRole('button').nth(5).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.getByRole('button').nth(5).click();
  await page.getByRole('button').nth(5).click();
  await page.getByText('Bridging Satu SehatBridging').click();
  await page.locator('[data-test="sidebar-item-akreditasi"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '- Nash [Schedula V2] (Pemilik)' }).click();
  await page.locator('div').nth(1).click();
  await page.goto('https://dev-essensial.assist.id/');
  await page.locator('html').click();
  await expect(page.locator('html').getByRole('document')).toBeVisible();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.locator('.slick-list').click();
  await page.locator('[data-test="sidebar-item-layananTambahn"]').click();
  await page.locator('div').filter({ hasText: 'AssistMe(Online Appointment)' }).nth(5).click();
  await page.locator('div').filter({ hasText: 'AssistMe(Online Appointment)' }).nth(5).click();
  await page.locator('div').filter({ hasText: 'AssistMe(Online Appointment)' }).nth(5).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('#mainLayoutContainer').click();
  await page.locator('div').filter({ hasText: /^Rawat Jalan$/ }).first().click();
  await page.getByRole('button', { name: 'Info Tenaga Medis' }).click();
  await page.getByRole('button', { name: 'Info Tenaga Medis' }).click();
  await page.getByRole('button', { name: 'Info Tenaga Medis' }).click();
  await page.getByRole('button', { name: 'Info Tenaga Medis' }).click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.locator('#mainLayoutContainer').click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.getByRole('button', { name: 'General Settings' }).click();
  await page.getByRole('heading', { name: 'Rawat Jalan' }).click();
  await page.locator('div').filter({ hasText: 'General Settings > Rawat' }).nth(5).click();
  await page.locator('div').filter({ hasText: 'Tambah Vital Sign' }).nth(5).click();
  await page.locator('div').filter({ hasText: 'SettingsNash [Schedula V2]' }).nth(4).click();
  await page.locator('.jss430.jss432').first().click();
  await page.locator('div').filter({ hasText: 'General SettingsManajemen' }).nth(5).click();
  await page.getByRole('button', { name: 'General Settings' }).click();
  await page.locator('div').filter({ hasText: /^General Settings$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Rawat Jalan$/ }).nth(2).click();
  await page.locator('[data-test="expandSetting-Poli"]').click();
  await page.locator('[data-test="input-prefixAntrean-0"]').click();
  await page.locator('[data-test="input-prefixAntrean-0"]').fill('um');
  await page.locator('[data-test="input-prefixAntrean-1"]').click();
  await page.locator('[data-test="input-prefixAntrean-1"]').fill('lb');
  await page.locator('[data-test="input-prefixAntrean-2"]').click();
  await page.locator('[data-test="input-prefixAntrean-2"]').fill('gW');
  await page.locator('[data-test="input-prefixAntrean-2"]').press('CapsLock');
  await page.locator('[data-test="input-prefixAntrean-3"]').click();
  await page.locator('[data-test="input-prefixAntrean-3"]').fill('');
  await page.locator('div').filter({ hasText: 'General SettingsManajemen' }).nth(5).dblclick();
  await page.getByRole('button', { name: 'General Settings' }).click();
  await page.getByText('General SettingsRawat Jalan').click();
  await page.getByRole('heading', { name: 'Rawat Jalan' }).click();
  await page.locator('[data-test="expandSetting-Poli"]').click();
  await page.locator('[data-test="input-prefixAntrean-0"]').click();
  await page.locator('[data-test="input-prefixAntrean-0"]').fill('uM');
  await page.locator('[data-test="input-prefixAntrean-0"]').press('Tab');
  await page.locator('[data-test="button-deletePoli-0"]').press('Tab');
  await page.getByRole('button', { name: 'Lab' }).press('Tab');
  await page.locator('[data-test="input-prefixAntrean-1"]').fill('lB');
  await page.getByText('Nama PoliUmumKode AntrianNama').click();
  await page.locator('[data-test="input-prefixAntrean-2"]').click();
  await page.locator('[data-test="input-prefixAntrean-2"]').fill('gW');
  await page.locator('[data-test="input-prefixAntrean-3"]').click();
  await page.locator('[data-test="input-prefixAntrean-3"]').fill('kC');
  await page.locator('.jss1878 > div > div').click();
  await page.locator('[data-test="input-prefixAntrean-3"]').click();
  await page.locator('[data-test="input-prefixAntrean-3"]').fill('kc33');
  await page.getByText('Kode Antrian tidak boleh').dblclick();
  await page.getByText('Nama PoliUmumKode AntrianNama').click();
  await page.locator('[data-test="input-prefixAntrean-3"]').click();
  await page.locator('[data-test="input-prefixAntrean-3"]').fill('kce3');
  await page.getByText('Kode Antrian tidak boleh').click();
  await page.locator('.jss430.jss432').first().click();
  await page.locator('[data-test="button-simpanRawatJalan"]').click();
  await page.getByRole('heading', { name: 'General Settings' }).click();
  await page.getByRole('heading', { name: 'Rawat Jalan' }).click();
  await page.getByRole('button', { name: 'Info Tenaga Medis' }).click();
  await page.getByRole('button', { name: 'Info Tenaga Medis' }).click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.getByText('Manajemen StaffLast Update:').click();
  await page.locator('#mainLayoutContainer').click();
  await page.getByRole('cell').filter({ hasText: /^$/ }).nth(1).click();
  await page.locator('.jss2441').click();
  await page.locator('.jss2441').dblclick();
  await page.locator('[data-test="input-nama-lengkap"]').fill('Agung');
  await page.locator('[data-test="input-email"]').fill('muhammad.sholihhudin@assist.id');
  await page.locator('[data-test="input-jabatan"]').fill('IT');
  await page.locator('[data-test="input-nomor-hp"]').fill('0800-0000-234 ');
  await page.locator('html').getByRole('document').press('Escape');
  await page.locator('[data-test="input-namaProsedur-0"]').fill('NS-https://house.fandom.com/wiki/Percutaneous_transhepatic_cholangiogram');
  await page.locator('[data-test="input-namaProsedur-0"]').press('Shift+ArrowRight');
  await page.locator('[data-test="input-namaProsedur-0"]').fill('NS-Percutaneous Transhepatic_cholangiogram');
  await page.locator('[data-test="input-namaProsedur-0"]').press('Alt+ArrowRight');
  await page.locator('[data-test="input-namaProsedur-0"]').press('Alt+ArrowRight');
  await page.locator('[data-test="input-namaProsedur-0"]').press('Alt+ArrowRight');
  await page.locator('[data-test="input-namaProsedur-0"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-namaProsedur-0"]').press('ArrowRight');
  await page.locator('[data-test="input-namaProsedur-0"]').press('ArrowRight');
  await page.locator('[data-test="input-namaProsedur-0"]').press('ArrowRight');
  await page.locator('[data-test="input-namaProsedur-0"]').press('ArrowRight');
  await page.locator('[data-test="input-namaProsedur-0"]').press('ArrowRight');
  await page.locator('[data-test="input-namaProsedur-0"]').press('ArrowRight');
  await page.locator('[data-test="input-namaProsedur-0"]').fill('NS-Percutaneous Transhepatic Cholangiogram');
  await page.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').fill('Ns');
  await page.locator('[data-test="input-namaProsedur-1"]').fill('NS-Embolectomy');
  await page.locator('[data-test="parent-autocomplete-namaPraktek-1"]').getByRole('textbox', { name: 'Nama Praktek' }).fill('Ns');
  await page.locator('[data-test="input-hargaProsedur-1"]').fill('Rp20.0000');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('[data-test="input-hargaProsedur-0"]').fill('Rp30.0000');
  const download = await downloadPromise;
  await page.getByRole('button', { name: 'Drag & drop files orbrowse' }).setInputFiles('Import Katalog Harga Prosedur.xlsx');
  await page.getByRole('menuitem', { name: 'Edit data prosedur' }).press('Escape');
  await page.getByRole('button', { name: 'Settings' }).nth(3).press('Escape');
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('ns-');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').fill('1');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('2');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.getByRole('button', { name: 'Katalog Harga Prosedur' }).press('Escape');
  await page.locator('[data-test="input-namaProsedur-0"]').fill('NS-Hemispherectomy');
  await page.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').fill('Ns-');
  await page.locator('[data-test="input-hargaProsedur-0"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-hargaProsedur-0"]').fill('Rp40.0000');
  await page.locator('[data-test="input-packageName-0"]').fill('NS-Paket-');
  await page.locator('[data-test="autocomplete-input"]').fill('Ns-');
  await page.locator('[data-test="input-packageName-0"]').fill('NS-Paket-Percu + Embo');
  await page.locator('[data-test="input-procedureQuantity-0-0"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-procedureQuantity-0-0"]').fill('2');
  await page.locator('[data-test="input-procedureQuantity-0-1"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-procedureQuantity-0-1"]').fill('1');
  await page.locator('[data-test="input-packageDuration-0"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-packageDuration-0"]').fill('9.0000');
  await page.locator('[data-test="input-packagePrice-0"]').fill('Rp100.0000');
  await page.locator('[data-test="input-defaultCommissionType"]').selectOption('percent');
  await page.locator('[data-test="input-commissionValue-0"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-commissionValue-0"]').fill('1%');
  await page.locator('[data-test="input-defaultCommissionType"]').selectOption('percent');
  await page.locator('[data-test="input-defaultCommissionType"]').selectOption('price');
  await page.locator('[data-test="input-defaultCommissionValue"]').press('Shift+ArrowRight');
  await page.locator('[data-test="input-defaultCommissionValue"]').fill('Rp2.0000');
  await page.locator('[data-test="input-defaultCommissionValue"]').press('ArrowLeft');
  await page.locator('[data-test="input-defaultCommissionValue"]').press('ArrowRight');
  await page.locator('[data-test="input-defaultCommissionValue"]').fill('Rp20.00');
  await page.goto('https://dev-essensial.assist.id/bantuanDanSaran');
  await page.getByRole('textbox', { name: 'Masukkan judul pertanyaan' }).fill('Halo, random');
  await page.getByRole('textbox', { name: 'Masukkan judul pertanyaan' }).press('Alt+ArrowLeft');
  await page.getByRole('textbox', { name: 'Masukkan judul pertanyaan' }).press('ControlOrMeta+Shift+ArrowRight');
  await page.getByRole('textbox', { name: 'Masukkan judul pertanyaan' }).fill('Halo, saya dari Schedula');
  await page.locator('.ql-editor').fill('Random, cek masuk ke panela atau tidak');
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('ns-');
  await page.locator('[data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="quantity-input"]').fill('2');
  await page.locator('[data-test="input-bayar-langsung"]').fill('Rp65.0000');
  await page.locator('[data-test="input-dibayar-oleh-langsung"]').fill('pasien random');
  await page.locator('html').getByRole('document').press('Escape');
  await page.goto('https://dev-essensial.assist.id/office');
  await page.locator('input[name="invoiceNo"]').fill('INV-NS-01');
  await page.locator('input[name="itemName"]').fill('Sapu');
  await page.getByRole('textbox').nth(2).fill('Rp. 3.0000');
  await page.getByRole('textbox').nth(3).fill('Pel');
  await page.getByRole('textbox').nth(4).fill('Rp. 5.0000');
  await page.locator('textarea[name="freeText"]').fill('Random input, harusnya tidak bisa kan ya?');
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('ns-');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Ns-');
  await page.getByRole('textbox', { name: 'Cari Prosedur' }).fill('Ns-');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.getByRole('option', { name: 'Owner' }).press('Escape');
  await page.locator('[data-test="input-commissionType-0"]').selectOption('price');
  await page.locator('[data-test="input-commissionValue-0"]').fill('Rp2.0000');
  await page.locator('[data-test="input-commissionValue-0"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-commissionValue-0"]').fill('Rp150.00');
  const page1Promise = page.waitForEvent('popup');
  await page.goto('https://dev-essensial.assist.id/settings');
  const page1 = await page1Promise;
  await page1.goto('https://dev-adv-report.assist.id/login');
  await page1.getByText('Advanced ReportingPantau').click();
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('ns');
  await page.locator('[data-test="discount-value-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="discount-value-input"]').fill('1000');
  await page.locator('[data-test="discount-value-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="discount-value-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="discount-value-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="discount-value-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="discount-value-input"]').fill('20');
  await page.locator('[data-test="discount-value-input"]').press('Enter');
  await page.locator('[data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="quantity-input"]').fill('1');
  await page.locator('[data-test="discount-value-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="discount-value-input"]').fill('20');
  await page.locator('[data-test="input-dibayar-oleh-langsung"]').fill('random pasien');
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('ns-');
  const page2Promise = page.waitForEvent('popup');
  await page.goto('https://dev-essensial.assist.id/layanan-tambahan');
  const page2 = await page2Promise;
  await page.goto('https://dev-essensial.assist.id/layanan-tambahan');
});