import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').click();
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('[data-test="input-password"]').click();
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: 'Baru (Pemilik)' }).click();
  await page.getByRole('heading', { name: 'Informasi' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('Nash');
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('Nash []');
  await page.getByRole('textbox').press('ArrowLeft');
  await page.getByRole('textbox').fill('Nash [Schedula V2]');
  await page.locator('path').nth(2).click();
  await page.getByRole('radio', { name: 'Dibawah satu tahun.' }).check();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('1');
  await page.locator('.jss1315.jss1514').click();
  await page.getByText('Tidak').click();
  await page.getByRole('radio', { name: 'Sudah Akreditasi' }).check();
  await page.getByRole('radio', { name: 'Punya apotek (bisa jual untuk' }).check();
  await page.getByRole('radiogroup').filter({ hasText: 'IyaTidak' }).getByLabel('Tidak').check();
  await page.locator('input[name="kodePos"]').fill('1234211');
  await page.locator('input[name="namaJalan"]').fill('Jl Baristepe');
  await page.locator('input[name="namaJalan"]').press('Enter');
  await page.locator('input[name="npwpName"]').fill('NPWP Baristepe');
  await page.locator('input[name="npwpName"]').press('ArrowLeft');
  await page.locator('input[name="npwpName"]').press('ArrowLeft');
  await page.locator('input[name="npwpName"]').fill('NPWPNash');
  await page.locator('input[name="npwpName"]').press('ArrowRight');
  await page.locator('input[name="npwpName"]').fill('NPWP Nash');
  await page.locator('input[name="npwp"]').fill('235345345');
  await page.locator('input[name="npwp"]').press('Tab');
  await page.locator('input[name="npwpAddress"]').fill('Baristepe');
  await page.locator('input[name="npwpAddress"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('input[name="npwpAddress"]').press('ControlOrMeta+a');
  await page.locator('input[name="npwpAddress"]').fill('Alamat NPWP');
  await page.goto('https://app.sandbox.midtrans.com/snap/v4/redirection/8b6626a7-1e01-4590-9ba5-022876d8f1da#/payment-list');
  await page.getByRole('link', { name: 'banklogo BCA virtual account' }).click();
  await page1.goto('https://simulator.sandbox.midtrans.com/bca/va/index');
  await page.getByText('Copy').click();
  await page1.locator('#inputMerchantId').click();
  await page1.locator('#inputMerchantId').fill('22646207675685620888299');
  await page1.getByRole('button', { name: 'Inquire' }).click();
  await page1.getByRole('button', { name: 'Pay' }).click();
  await page.getByRole('button', { name: 'Check status' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Nanti Saja' }).click();
  await page.locator('html').getByRole('document').click();
  await page.locator('.jss921 > div > div').first().click();
  await page.getByRole('img', { name: 'kaget' }).click();
  await page.locator('div').filter({ hasText: 'Varian produk Anda telah' }).nth(5).click();
  await page.getByRole('button', { name: 'Selanjutnya' }).click();
  await page.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('div').filter({ hasText: /^Rawat Jalan$/ }).first().click();
  await page.locator('[data-test="sidebar-item-layananTambahn"]').click();
  await page.locator('.jss1187').click();
  await page.locator('div').filter({ hasText: /^Syarat dan Ketentuan$/ }).nth(1).click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('button').click();
  await page.locator('.jss1217 > .jss243').click();
  await page.locator('div:nth-child(2) > .jss430 > .jss240.jss1202 > .jss240.jss234.jss1207 > span > .jss240').click();
  await page.locator('.jss240.jss1202.jss1303 > .jss240.jss234.jss1207 > span > .jss240').first().click();
  await page.getByRole('heading', { name: 'Frequently Asked Questions' }).click();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('heading', { name: 'Frequently Asked Questions' }).getByRole('button').click();
  await page.locator('.jss56.jss91').click();
  await page.getByRole('img', { name: 'mainImg' }).click();
  await page.locator('html').getByRole('document').press('ArrowRight');
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').press('Escape');
  await page.getByRole('img', { name: 'secondImg' }).nth(1).click();
  await page.locator('html').getByRole('document').press('Escape');
  await page.getByRole('img', { name: 'secondImg' }).nth(2).click();
  await page.locator('html').getByRole('document').press('Escape');
  await page.locator('.jss1187').click();
  await page.locator('div').filter({ hasText: /^Syarat dan Ketentuan$/ }).nth(1).click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('button').click();
  await page.getByText('Booking Cepat & Praktis di AssistMe: Tak perlu antre lama, buat janji dengan').click();
  await page.locator('.slick-list').click();
  await page.locator('[data-test="sidebar-item-rawat-jalan"]').click();
  await page.getByRole('button', { name: '+ Tambah Data Tenaga Medis' }).click();
  await page.getByRole('heading', { name: 'Estimasi Waktu' }).click();
  await page.locator('.jss56.jss88 > div:nth-child(3)').click();
  await page.getByText('Tambah Tenaga MedisUpload').click();
  await page.getByText('Tambah Tenaga MedisUpload').click();
  await page.locator('.jss2353').click();
  await page.locator('[data-test="input-nama"]').click();
  await page.locator('[data-test="input-nama"]').fill('SC-Ruiz');
  await page.locator('[data-test="input-nama"]').click();
  await page.locator('[data-test="input-nama"]').click();
  await page.locator('[data-test="input-nama"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('[data-test="input-nama"]').press('Alt+Shift+ArrowRight');
  await page.locator('[data-test="input-nama"]').fill('NS-Ruiz');
  await page.locator('[data-test="input-telepon"]').click();
  await page.locator('[data-test="input-telepon"]').fill('081371075995');
  await page.getByRole('button', { name: 'Upload Photo Profile' }).click();
  await page.getByRole('button', { name: 'Upload Photo Profile' }).setInputFiles('A Cat 01.jpg');
  await page.locator('[data-test="input-email"]').click();
  await page.locator('[data-test="input-email"]').click();
  await page.locator('[data-test="input-email"]').fill('annisa.ghaisani@assist.id');
  await page.locator('div').filter({ hasText: /^Nomor KTP$/ }).nth(1).click();
  await page.locator('[data-test="input-noKTP"]').fill('23424234523');
  await page.getByText('Nama Lengkap (Tanpa Gelar) *Jenis Kelamin *Laki-lakiNomor HPAlamat EmailNomor').click();
  await page.locator('.jss55.jss56.jss78 > div:nth-child(3)').first().click();
  await page.locator('.jss55.jss56.jss78 > div:nth-child(3)').first().click();
  await page.locator('.jss2477').click();
  await page.locator('[data-test="input-registrasiNomor"]').click();
  await page.locator('[data-test="input-registrasiNomor"]').fill('23424242');
  await page.locator('[data-test="checkbox-isSTRActiveForever"]').check();
  await page.locator('div:nth-child(6) > .jss1922').click();
  await page.getByRole('option', { name: 'Persatuan Dokter Gigi' }).click();
  await page.locator('[data-test="input-registrasiSIPNomor"]').click();
  await page.locator('[data-test="input-registrasiSIPNomor"]').fill('23424242');
  await page.locator('[data-test="datepicker-registrasiSIPTanggal"]').getByRole('textbox').click();
  await page.getByRole('heading', { name: '2026' }).click();
  await page.getByRole('button', { name: '2029' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('.jss56.jss89 > .jss1922').click();
  await page.getByRole('option', { name: 'Dr. rer. med.' }).click();
  await page.locator('[data-test="autocomplete-input"]').click();
  await page.locator('[data-test="autocomplete-input"]').fill('Sp');
  await page.getByText('Sp.Epid').click();
  await page.getByText('Sp.Epid').click();
  await page.getByRole('menuitem', { name: 'Sp.Epid' }).click();
  await page.locator('.jss56.jss87 > .jss1922 > .jss1964 > .jss1944 > .jss1945').first().click();
  await page.getByRole('option', { name: 'Dokter Hewan' }).click();
  await page.locator('div:nth-child(12) > .jss1922 > .jss1964 > .jss1944 > .jss1945').click();
  await page.getByRole('option', { name: 'Dokter Hewan Spesialis Penyakit Hewan Kesayangan Unggas' }).click();
  await page.locator('.jss1945.jss1948.jss1949').click();
  await page.locator('.jss1945.jss1948.jss1949').click();
  await page.getByText('Upload Photo ProfilePanduan FotoNama Lengkap (Tanpa Gelar) *Jenis Kelamin *Laki').click();
  await page.locator('.jss480.jss467.jss471.jss481.jss468.jss485.jss2046').first().click();
  await page.getByRole('menu').click();
  await page.getByRole('menu').click();
  await page.getByRole('menu').click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button').filter({ hasText: 'event' }).first().click();
  await page.getByRole('menu').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('menu').click();
  await page.getByRole('heading', { name: '18' }).click();
  await page.getByRole('menu').first().click();
  await page.getByRole('heading', { name: '18' }).click();
  await page.getByRole('menu').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('08:00_');
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').press('ControlOrMeta+a');
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').press('ControlOrMeta+c');
  await page.locator('.jss480.jss467.jss471.jss481.jss468.jss485.jss2046 > .jss490').first().click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').press('ControlOrMeta+a');
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('08:0008:00');
  await page.getByText('Jam Mulai').nth(2).click();
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('08:0008:00');
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('08:00');
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('08:00');
  await page.locator('.jss55.jss56.jss78.jss95.jss2242 > div:nth-child(7)').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').dblclick();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('08:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('08:00');
  await page.locator('.jss55 > div:nth-child(5) > .jss1401 > .jss480 > .jss490').first().click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('23:00_');
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').press('ControlOrMeta+a');
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('23:00');
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('23:00');
  await page.getByText('Jam Selesai event').nth(4).click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').dblclick();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('23:00');
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('23:00');
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('23:0023:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('23:00');
  await page.locator('.jss55.jss56.jss78.jss95.jss2242 > div:nth-child(7)').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').dblclick();
  await page.getByText(':00000510152025303540455055ClearCancelOK').click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1401 > .jss480 > .jss490').click();
  await page.locator('.jss480.jss467.jss471.jss482 > .jss490').fill('23:00');
  await page.locator('[data-test="button-save"]').click();
  await page.locator('div').filter({ hasText: 'Konfirmasi PenyimpananBatas' }).nth(5).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByText('Filter+ Tambah Data Tenaga MedisEdit ProfilNS-RuizMasa berlaku SIP tersisa 1096').click();
  await page.locator('.jss55.jss56.jss79').click();
  await page.locator('[data-test="sidebar-item-rawat-jalan"]').click();
  await page.locator('[data-test="sidebar-item-registrasi"]').click();
  await page.locator('[data-test="sidebar-item-rawat-jalan"]').click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.getByRole('button', { name: 'Info Tenaga Medis' }).click();
  await page.getByRole('button', { name: 'Edit Profil' }).click();
  await page.getByRole('button', { name: 'Dokter Hewan', exact: true }).click();
  await page.getByRole('option', { name: 'Dokter', exact: true }).click();
  await page.locator('div:nth-child(12) > .jss4580 > .jss4622 > .jss4602 > .jss4603').click();
  await page.getByRole('option', { name: 'Dokter Spesialis Anak' }).click();
  await page.locator('div').filter({ hasText: 'Estimasi WaktuEstimasi Lama' }).nth(5).click();
  await page.locator('div').filter({ hasText: 'Estimasi WaktuEstimasi Lama' }).nth(5).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('[data-test="button-save"]').click();
  await page.locator('[data-test="sidebar-item-rawat-jalan"]').click();
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('button', { name: 'Selanjutnya' }).click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Selanjutnya' }).click();
  await page.getByRole('checkbox').first().check();
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('checkbox').nth(2).check();
  await page.getByRole('checkbox').nth(3).check();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('img', { name: 'No Patient' }).click();
  await page.getByRole('button', { name: '5' }).click();
  await page.locator('div').filter({ hasText: /^Pesan$/ }).click();
  await page.locator('.jss1231').click();
  await page.locator('.jss1231').click();
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-nama"]').fill('NS-Collins');
  await page.locator('[data-test="input-telepon"]').fill('081371075995');
  await page.locator('[data-test="input-email"]').fill('annisa.ghaisani@assist.id');
  await page.getByRole('button', { name: 'Upload Photo Profile' }).setInputFiles('A Cat 02.jpg');
  await page.locator('[data-test="input-noKTP"]').fill('');
  await page.locator('[data-test="input-registrasiNomor"]').fill('234242');
  await page.locator('[data-test="input-registrasiSIPNomor"]').fill('232432');
  await page.locator('.jss1417.jss1404.jss1408.jss1418.jss1405.jss1422.jss2415 > .jss1427').first().fill('08:00_');
  await page.locator('.jss1417.jss1404.jss1408.jss1418.jss1405.jss1422.jss2415 > .jss1427').first().press('ControlOrMeta+a');
  await page.locator('.jss1417.jss1404.jss1408.jss1419 > .jss1427').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss2149 > .jss1417 > .jss1427').fill('08:00');
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss2149 > .jss1417 > .jss1427').fill('08:00');
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss2149 > .jss1417 > .jss1427').fill('08:00');
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss2149 > .jss1417 > .jss1427').fill('08:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss2149 > .jss1417 > .jss1427').fill('08:00');
  await page.locator('.jss55 > div:nth-child(5) > .jss2149 > .jss1417 > .jss1427').first().fill('23:00_');
  await page.locator('.jss55 > div:nth-child(5) > .jss2149 > .jss1417 > .jss1427').first().press('ControlOrMeta+a');
  await page.locator('.jss1417.jss1404.jss1408.jss1419 > .jss1427').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss2149 > .jss1417 > .jss1427').fill('23:00');
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss2149 > .jss1417 > .jss1427').fill('23:00');
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss2149 > .jss1417 > .jss1427').fill('23:00');
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss2149 > .jss1417 > .jss1427').fill('23:00');
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss2149 > .jss1417 > .jss1427').fill('23:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss2149 > .jss1417 > .jss1427').fill('23:00');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.locator('div').filter({ hasText: 'Dr. rer. med. NS-Ruiz Sp.Epid' }).nth(5).click();
  await page.locator('body').press('Escape');
  await page.locator('div').filter({ hasText: /^Judul 123Isi 123111128 Mei 2026 \| 11:45Lihat lebih detail$/ }).nth(1).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.locator('body').press('Escape');
  await page.locator('[data-test="sidebar-item-registrasi"]').click();
  await page.locator('#mainLayoutContainer').click();
  await page.locator('[data-test="menu-rawat-jalan-poli"]').click();
  await page.locator('div').filter({ hasText: 'Pendaftaran Baru' }).nth(5).click();
  await page.getByRole('button', { name: 'Pendaftaran Baru' }).click();
  await page.locator('html').getByRole('document').click();
  await page.getByText('Daftar KunjunganTanda * wajib').click();
  await page.getByRole('button', { name: 'Batal' }).click();
  await page.locator('div').filter({ hasText: 'Rawat Jalan PoliAntriCepat' }).nth(5).click();
  await page.locator('#mainLayoutContainer').click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('div').filter({ hasText: /^Rawat Jalan$/ }).nth(2).click();
  await page.getByRole('button', { name: 'Info Tenaga Medis' }).click();
  await page.getByRole('button', { name: 'Edit Profil' }).nth(1).click();
  await page.getByRole('button', { name: 'Dokter Spesialis Kedokteran' }).click();
  await page.getByRole('option', { name: 'Dokter Umum' }).click();
  await page.locator('.jss15959.jss15962.jss15963').click();
  await page.locator('div').filter({ hasText: 'Estimasi WaktuEstimasi Lama' }).nth(5).click();
  await page.locator('[data-test="button-save"]').click();
  await page.locator('#mainLayoutContainer').click();
  await page.getByRole('button', { name: '+ Tambah Data Tenaga Medis' }).click();
  await page.getByText('Nama Lengkap (Tanpa Gelar) *Jenis Kelamin *Laki-lakiNomor HPAlamat EmailNomor').click();
  await page.locator('[data-test="input-nama"]').click();
  await page.locator('[data-test="input-nama"]').fill('NS-Kinsley');
  await page.locator('[data-test="input-telepon"]').click();
  await page.getByRole('button', { name: 'Laki-laki' }).click();
  await page.getByRole('option', { name: 'Perempuan' }).click();
  await page.locator('[data-test="input-telepon"]').click();
  await page.locator('[data-test="input-telepon"]').fill('081371075995');
  await page.locator('[data-test="input-email"]').click();
  await page.locator('[data-test="input-email"]').fill('annisa.ghaisani@assist.id');
  await page.locator('[data-test="input-noKTP"]').click();
  await page.locator('[data-test="input-email"]').fill('annisa.ghaisani@assist.id234');
  await page.locator('[data-test="input-noKTP"]').fill('325423422424324');
  await page.locator('[data-test="input-email"]').click();
  await page.locator('[data-test="input-email"]').fill('annisa.ghaisani@assist.id');
  await page.getByRole('img', { name: 'Profile' }).click();
  await page.getByRole('button', { name: 'Upload Photo Profile' }).click();
  await page.getByRole('button', { name: 'Upload Photo Profile' }).setInputFiles('A Cat 06.png');
  await page.locator('.jss1294.jss1281.jss1285.jss1295.jss1282.jss1299.jss16597 > .jss1304').first().click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('08:00_');
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').press('ControlOrMeta+a');
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss15766 > .jss1294 > .jss1304').click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('08:00');
  await page.getByText('Jam Mulai').nth(2).click();
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss15766 > .jss1294 > .jss1304').click();
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss15766 > .jss1294 > .jss1304').click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('08:00');
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss15766 > .jss1294 > .jss1304').click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('08:00');
  await page.locator('.jss55.jss56.jss78.jss95.jss16793 > div:nth-child(6)').click();
  await page.locator('.jss55.jss56.jss78.jss95.jss16793 > div:nth-child(6)').click();
  await page.locator('.jss55.jss56.jss78.jss95.jss16793 > div:nth-child(6)').click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss15766 > .jss1294 > .jss1304').click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('08:00');
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss15766 > .jss1294 > .jss1304').click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('08:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss15766 > .jss1294 > .jss1304').click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('08:00');
  await page.locator('.jss55 > div:nth-child(5) > .jss15766 > .jss1294 > .jss1304').first().click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('22:00_');
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').press('ControlOrMeta+a');
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss15766 > .jss1294 > .jss1304').click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('22:00');
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss15766 > .jss1294 > .jss1304').click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('22:00');
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss15766 > .jss1294 > .jss1304').click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('22:00');
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss15766 > .jss1294 > .jss1304').click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('22:00');
  await page.locator('.jss55.jss56.jss78.jss95.jss16793 > div:nth-child(8)').click();
  await page.locator('.jss55.jss56.jss78.jss95.jss16793 > div:nth-child(8)').click();
  await page.locator('.jss55.jss56.jss78.jss95.jss16793 > div:nth-child(8)').click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss15766 > .jss1294 > .jss1304').click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('22:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss15766 > .jss1294 > .jss1304').click();
  await page.locator('.jss1294.jss1281.jss1285.jss1296 > .jss1304').fill('22:00');
  await page.locator('#select-registrasiLembaga').click();
  await page.getByRole('option', { name: 'Konsil Kedokteran Indonesia' }).click();
  await page.locator('[data-test="input-registrasiNomor"]').click();
  await page.locator('[data-test="input-registrasiNomor"]').click();
  await page.locator('[data-test="input-registrasiNomor"]').fill('23424');
  await page.locator('[data-test="checkbox-isSTRActiveForever"]').check();
  await page.locator('.jss55.jss56.jss78 > div:nth-child(6)').first().click();
  await page.getByRole('option', { name: 'Ikatan Dokter Indonesia (IDI)' }).click();
  await page.locator('[data-test="input-registrasiSIPNomor"]').click();
  await page.locator('[data-test="input-registrasiSIPNomor"]').fill('234242');
  await page.locator('[data-test="datepicker-registrasiSIPTanggal"]').click();
  await page.getByRole('button', { name: '19' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('[data-test="datepicker-registrasiSIPTanggal"]').getByRole('textbox').click();
  await page.getByRole('heading', { name: '2026' }).click();
  await page.getByRole('button', { name: '2031' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('#select-gelarDepan').click();
  await page.getByRole('option', { name: 'dr.', exact: true }).click();
  await page.locator('.jss56.jss87 > .jss16473 > .jss16515 > .jss16495 > .jss16496').first().click();
  await page.getByRole('option', { name: 'Dokter Gigi' }).click();
  await page.locator('div:nth-child(12) > .jss16473 > .jss16515 > .jss16495 > .jss16496').click();
  await page.locator('div:nth-child(12) > .jss16473 > .jss16515 > .jss16495 > .jss16496').dblclick();
  await page.locator('[data-test="button-save"]').click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Billing !' }).click();
  await page.getByRole('tab', { name: 'Request Faktur Pajak !' }).click();
  await page.getByRole('button', { name: 'General Settings' }).click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.locator('.jss17951 > .jss55 > div > .jss352').first().click();
  await page.locator('#tanggal-lahir').click();
  await page.getByRole('heading', { name: '2026' }).click();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('button', { name: '1990' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('textbox', { name: 'Nomor Pegawai' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('.jss17951 > .jss55 > div > .jss352').first().click();
  await page.locator('.jss18413').click();
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.locator('div').filter({ hasText: 'Dr. rer. med. NS-Ruiz Sp.Epid' }).nth(5).click();
  await page.locator('.jss402 > div > div').first().click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  const page2Promise = page.waitForEvent('popup');
  await page.locator('#btnQuestion').click();
  const page2 = await page2Promise;
  await page.getByRole('button').nth(3).click();
  await page.locator('.jss1092').click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button').nth(3).click();
  await page.locator('.jss1102').click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('div').filter({ hasText: /^General Settings$/ }).nth(2).click();
  await page.getByRole('heading', { name: 'Rawat Jalan' }).click();
  await page.locator('[data-test="expandSetting-Poli"]').click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.getByRole('button', { name: 'Info Tenaga Medis' }).click();
  await page.getByRole('button', { name: '+ Tambah Data Tenaga Medis' }).click();
  await page.getByRole('button', { name: '+ Tambah Data Tenaga Medis' }).click();
  await page.getByRole('button', { name: '+ Tambah Data Tenaga Medis' }).click();
  await page.locator('#mainLayoutContainer').click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.locator('#mainLayoutContainer').click();
  await page.locator('[data-test="button-add-staff"]').click();
  await page.locator('[data-test="input-nama-lengkap"]').click();
  await page.locator('[data-test="input-nama-lengkap"]').fill('Gesi');
  await page.locator('[data-test="input-email"]').click();
  await page.locator('[data-test="input-email"]').fill('anisasecondacc24@gmail.com');
  await page.locator('[data-test="input-jabatan"]').click();
  await page.locator('[data-test="input-jabatan"]').fill('QA');
  await page.getByText('Nama Lengkap *Tanggal Lahir *Jabatan *Tipe Akses *Pilih Tipe AksesAlamat Email').click();
  await page.getByRole('button', { name: 'Pilih Tipe Akses' }).click();
  await page.locator('div').filter({ hasText: /^Owner$/ }).nth(2).click();
  await page.locator('.jss1317.jss1320.jss1796').click();
  await page.getByRole('heading', { name: '2026' }).click();
  await page.getByRole('button', { name: '1996' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('[data-test="input-nomor-hp"]').click();
  await page.locator('[data-test="input-nomor-hp"]').fill('0813-7107-5995  ');
  await page.locator('[data-test="button-simpan-staff"]').click();
  await page.locator('div').filter({ hasText: 'Konfirmasi PenyimpananBatas' }).nth(5).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.locator('#mainLayoutContainer').click();
  await page.getByRole('button', { name: 'Katalog Paket Prosedur' }).click();
  await page.locator('[data-test="sidebar-item-rawat-jalan"]').click();
  await page.locator('div').filter({ hasText: 'Dr. rer. med. NS-Ruiz Sp.Epid' }).nth(5).click();
  await page.locator('#add21245').click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('NS-Maynard');
  await page.locator('[data-test="input-tempat-lahir"]').fill('Senerchia');
  await page.locator('input[name="address"]').fill('Jl Senerchia no 213');
  await page.locator('input[name="postcode"]').fill('234352');
  await page.locator('[data-test="input-complaint"]').click();
  await page.locator('[data-test="input-complaint"]').fill('random appt');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('div').filter({ hasText: 'Dr. rer. med. NS-Ruiz Sp.Epid' }).nth(5).click();
  await page.locator('[data-test="sidebar-item-registrasi"]').click();
  await page.locator('.jss56.jss92 > button').click();
  await page.locator('[data-test="menu-rawat-jalan-poli"]').click();
  await page.locator('.jss56.jss91 > button').click();
  await page.getByRole('button').filter({ hasText: 'event' }).nth(1).click();
  await page.getByRole('button', { name: '31' }).click();
  await page.getByText('27 28 29 30 1 2 3 4 5 6 7 8 9').click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button').filter({ hasText: 'event' }).nth(1).click();
  await page.getByRole('button', { name: '31' }).click();
  await page.getByText('TodayCancelOK').click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('div').filter({ hasText: 'Faktur Pajak tidak dapat' }).nth(4).click();
  await page.locator('div').filter({ hasText: 'Rawat Jalan PoliAntriCepat' }).nth(5).click();
  await page.locator('#kamarmedis-content').click();
  await page.getByRole('button', { name: 'Pendaftaran Baru' }).click();
  await page.getByText('Tipe PasienPasien Non Rujuk').click();
  await page.locator('.jss64836').click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('NS-Aarya');
  await page.getByRole('button', { name: 'new' }).click();
  await page.locator('div:nth-child(3) > .jss65671 > .jss65555 > div').first().click();
  await page.locator('.jss65553.jss65554').click();
  await page.getByRole('button', { name: 'Laki - laki' }).click();
  await page.getByRole('button', { name: 'Laki - laki' }).click();
  await page.locator('[data-test="input-tempat-lahir"]').fill('Saint-Mammes');
  await page.locator('input[name="address"]').fill('Jl Saint-Mammes no 2345');
  await page.locator('input[name="postcode"]').fill('457546');
  await page3.locator('html').getByRole('document').click();
  await page3.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click();
  await page3.locator('[data-test="sidebar-item-settings"]').click();
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.locator('[data-test="autocomplete-input"]').fill('NAsh');
  await page.locator('[data-test="autocomplete-input"]').press('ControlOrMeta+a');
  await page.locator('[data-test="autocomplete-input"]').fill('NS-');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('pro');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).press('Escape');
  await page.goto('https://dev-essensial.assist.id/profile');
  await page.locator('[data-test="input-nitku"]').fill('12313');
  await page.locator('[data-test="input-deskripsi"]').fill('1231');
  await page.locator('[data-test="input-nomor-telepon"]').fill('07611234');
  await page.locator('[data-test="input-visi"]').fill('Visi Utama');
  await page.locator('[data-test="input-misi"]').fill('Misi Utama');
  await page.getByRole('textbox', { name: 'Pribadi, Contoh: Tunai' }).fill('');
  await page.getByRole('textbox', { name: 'Perusahaan' }).fill(' pt');
  await page.getByRole('textbox', { name: 'Perusahaan' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Perusahaan' }).fill('Pt');
  await page.locator('[data-test="autocomplete-metode-pembayaran-asuransi"] [data-test="autocomplete-input"]').fill(' ');
  await page.getByRole('textbox', { name: 'Perusahaan' }).fill('Pt');
  await page.locator('[data-test="autocomplete-metode-pembayaran-asuransi"] [data-test="autocomplete-input"]').press('ControlOrMeta+a');
  await page.locator('[data-test="autocomplete-metode-pembayaran-asuransi"] [data-test="autocomplete-input"]').fill('Asurans');
  await page.locator('[data-test="autocomplete-metode-pembayaran-debit"] [data-test="autocomplete-input"]').fill('');
  await page.locator('[data-test="autocomplete-metode-pembayaran-kredit"] [data-test="autocomplete-input"]').fill('Kre');
  await page.locator('[data-test="autocomplete-metode-pembayaran-debit"] [data-test="autocomplete-input"]').fill('De');
  await page.getByRole('textbox', { name: 'Click to insert description' }).nth(2).fill('Desc');
  await page.getByRole('textbox', { name: 'Click to insert description' }).nth(2).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Click to insert description' }).nth(2).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Click to insert description' }).first().fill('Desc');
  await page.goto('https://dev-essensial.assist.id/office');
});