import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').click();
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#username').press('Enter');
  await page.locator('[data-test="input-password"]').click();
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.getByText('Username/EmailPasswordpassword wajib diisiLoginLupa password?').click();
  await page.locator('[data-test="login-btn"]').click();
  await page.locator('.jss428.jss422.jss880').click();
  await page.getByRole('button', { name: 'close' }).click();
  await page.locator('div').filter({ hasText: 'DashboardKlinik Pcare &' }).nth(4).click({
    button: 'right'
  });
  await page.locator('[data-test="sidebar-item-emr"]').click();
  await page.locator('.jss1520').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '000101 - Klinik Assist.id [' }).click();
  await page.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button').nth(5).click();
  await page.getByRole('button').nth(5).click();
  await page.getByRole('button').nth(5).click();
  await page.locator('[data-test="sidebar-item-registrasi"]').click();
  await page.locator('.jss2879.jss2914 > button').click();
  await page.getByRole('button').filter({ hasText: 'event' }).nth(1).click();
  await page.getByRole('button', { name: '5', exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('[data-test="input-search-patient"]').click();
  await page.locator('[data-test="input-search-patient"]').fill('PRO');
  await page.getByRole('rowheader', { name: '/05/2026, 13:00' }).click();
  await page.getByRole('button', { name: 'Lihat Rekam Medis' }).click();
  await page.locator('.jss4435 > div:nth-child(2) > div').click();
  await page.locator('.jss4435 > div:nth-child(2) > div').dblclick();
  await page.locator('[data-test="emrAddBtn"]').click();
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('rujuk');
  await page.getByText('Tambah Rujukan Terintegrasi').click();
  await page.getByRole('button', { name: 'Rujukan Eksternal Lab' }).click();
  await page.locator('html').getByRole('document').click();
  await page.locator('#select-prodiaOutlet').click();
  await page.getByRole('textbox', { name: 'Cari Cabang Prodia' }).click();
  await page.getByRole('textbox', { name: 'Cari Cabang Prodia' }).fill('cideng');
  await page.getByRole('option', { name: 'CIDENG, [Jakarta Pusat]' }).click();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('heading', { name: 'Rujukan External Lab' }).getByRole('button').click();
  await page.locator('.jss5107').click();
  await page.locator('[data-test="emrAddBtn"]').click();
  await page.locator('.jss5652').click();
  await page.locator('[data-test="sidebar-item-kasir"]').click();
  await page.locator('[data-test="start-date-picker"]').getByRole('textbox').click();
  await page.getByRole('button', { name: '1', exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Tutup BukuPembayaranExportDari TanggalSampai TanggalFilterPreview Ranap').click();
  await page.locator('[data-test="button-filter"]').click();
  await page.getByRole('button', { name: 'Next Page' }).click();
  await page.locator('.jss5931').click();
  await page.locator('#mainLayoutContainer').click();
  await page.locator('.jss5931').click();
  await page.getByRole('button', { name: 'Lunas' }).first().click();
  await page.locator('.jss6284').click();
  await page.locator('[data-test="search-kasir-input"]').fill('pengantar');
  await page.locator('[data-test="search-kasir-input"]').press('ControlOrMeta+a');
  await page.locator('[data-test="search-kasir-input"]').fill('');
});