import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('[data-test="input-password"]').click();
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '001654 - Pure Atkins [Privata' }).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.getByRole('button', { name: 'Billing !' }).click();
  await page.getByRole('button', { name: 'Tambah Berlangganan' }).click();
  await page.getByRole('button', { name: 'Clinica Pro' }).click();
  await page.locator('.jss2846.jss2847').click();
  await page.getByRole('button', { name: 'Tahun' }).click();
  await page.getByRole('option', { name: '3 Bulan' }).click();
  await page.getByRole('button', { name: 'Clinica Pro' }).click();
  await page.locator('.jss2846.jss2847').click();
  await page.getByRole('button', { name: 'Lanjutkan Pembayaran' }).click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.getByRole('link', { name: 'banklogo BCA virtual account' }).click();
  await page1.goto('https://simulator.sandbox.midtrans.com/bca/va/index');
  await page.getByText('Virtual account number', { exact: true }).click();
  await page.getByText('Copy').click();
  await page1.getByRole('form').locator('div').filter({ hasText: 'Virtual Account Number' }).click();
  await page1.locator('#inputMerchantId').press('ControlOrMeta+c');
  await page1.locator('#inputMerchantId').fill('22646207681381675117492');
  await page1.getByRole('button', { name: 'Inquire' }).click();
  await page1.getByRole('button', { name: 'Pay' }).click();
  await page.getByRole('button', { name: 'Check status' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('html').click();
  await page1.goto('https://uat-panela.assist.id/login');
  await expect(page1.getByRole('textbox', { name: 'Masukkan username anda' })).toBeVisible();
  await page1.getByRole('textbox', { name: 'Masukkan username anda' }).click();
  await page1.getByRole('textbox', { name: 'Masukkan username anda' }).fill('annisa.ghaisani@assist.id');
  await page1.locator('div').nth(1).click();
  await page1.getByRole('textbox', { name: 'Masukkan password anda' }).click();
  await page1.getByRole('textbox', { name: 'Masukkan password anda' }).fill('12345678');
  await page1.getByRole('textbox', { name: 'Masukkan password anda' }).press('Enter');
  await page1.getByRole('button', { name: 'Sign In' }).click();
  await page1.getByRole('button', { name: 'Berlangganan' }).click();
  await page1.getByRole('button', { name: 'RME' }).click();
  await page1.getByRole('textbox', { name: 'Pencarian', exact: true }).click();
  await page1.getByRole('textbox', { name: 'Pencarian', exact: true }).fill('atkins');
  await page1.getByRole('button', { name: 'Filter', exact: true }).click();
  await page1.getByRole('cell').filter({ hasText: /^$/ }).click();
  await page1.getByText('Ubah Produk').click();
  await page1.locator('div').filter({ hasText: 'Ubah Produk Faskes Pure' }).nth(1).press('ControlOrMeta+f');
  await page1.locator('div').filter({ hasText: 'Ubah Produk Faskes Pure' }).nth(1).press('ControlOrMeta+f');
  await page1.getByRole('radio', { name: 'privataUnlimited' }).check();
  await page1.getByRole('textbox', { name: 'Masukkan alasan ubah produk' }).click();
  await page1.getByRole('textbox', { name: 'Masukkan alasan ubah produk' }).fill('Test Privata unlimited');
  await page1.getByRole('textbox', { name: 'Masukkan alasan ubah produk' }).click();
  await page1.getByRole('textbox', { name: 'Masukkan alasan ubah produk' }).press('Alt+ArrowLeft');
  await page1.getByRole('textbox', { name: 'Masukkan alasan ubah produk' }).press('Shift+ArrowRight');
  await page1.getByRole('textbox', { name: 'Masukkan alasan ubah produk' }).fill('Test Privata Unlimited');
  await page1.getByRole('button', { name: 'Ubah' }).click();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('button', { name: 'Nanti Saja' }).click();
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).click();
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).fill('Nanti saja');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('[data-test="sidebar-item-office"]').click();
  await page.locator('[data-test="sidebar-item-message-center"]').click();
  await page.locator('[data-test="sidebar-item-profile"]').click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').click();
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').press('ArrowRight');
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').press('ArrowLeft');
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').press('ArrowLeft');
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').press('ArrowRight');
  await page.locator('[data-test="input-nama-fasilitas-kesehatan"]').fill('Pure Atkins [Privata Unlimited]');
  await page.locator('[data-test="input-alamat-npwp-ktp"]').click();
  await page.locator('[data-test="input-alamat-npwp-ktp"]').fill('Alamat NPWP Atkins');
  await page.locator('div:nth-child(13) > .jss1421').click();
  await page.locator('[data-test="input-deskripsi"]').fill('Desc NPWP Atkins');
  await page.locator('[data-test="input-deskripsi"]').dblclick();
  await page.locator('[data-test="input-deskripsi"]').fill('Desc NPWP');
  await page.locator('[data-test="input-deskripsi"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-deskripsi"]').press('Alt+Shift+ArrowRight');
  await page.locator('[data-test="input-deskripsi"]').fill('Desc Atknis');
  await page.locator('[data-test="input-nitku"]').click();
  await page.locator('[data-test="input-nitku"]').fill('Nitku Atkins');
  await page.locator('[data-test="button-simpan-informasi-dasar"]').click();
  await page.goto('https://dev-essensial.assist.id/profile');
  await page.locator('[data-test="sidebar-item-message-center"]').click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.getByRole('button', { name: 'Billing !' }).click();
  await page.getByRole('button', { name: 'Tambah Berlangganan' }).click();
  await page.getByRole('button', { name: 'Tahun' }).click();
  await page.getByRole('option', { name: '1 Bulan' }).click();
  await page.getByText('1 BulanGunakan kode voucher ?').click();
  await page.getByRole('heading', { name: 'Check Out Privata Unlimited' }).getByRole('button').click();
  await page.getByRole('heading', { name: 'Check Out Privata Unlimited' }).getByRole('button').click();
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-nama"]').fill('PAT-Salga');
  await page.locator('[data-test="input-telepon"]').fill('081371075995e24');
  await page.locator('[data-test="input-email"]').fill('anisasecondacc24@gmail.com');
  await page.locator('[data-test="input-noKTP"]').fill('8978567890');
  await page.getByRole('button', { name: 'Upload Photo Profile' }).setInputFiles('Cat 03.jpg');
  await page.locator('[data-test="input-registrasiNomor"]').fill('124533r24');
  await page.locator('[data-test="input-registrasiSIPNomor"]').fill('23r4534542');
  await page.locator('.jss392.jss379.jss383.jss393.jss380.jss397.jss1834 > .jss402').first().fill('08:00_');
  await page.locator('.jss392.jss379.jss383.jss393.jss380.jss397.jss1834 > .jss402').first().press('ControlOrMeta+a');
  await page.locator('.jss392.jss379.jss383.jss394 > .jss402').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1165 > .jss392 > .jss402').fill('08:00');
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1165 > .jss392 > .jss402').fill('08:00');
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1165 > .jss392 > .jss402').fill('08:00');
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1165 > .jss392 > .jss402').fill('08:00');
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1165 > .jss392 > .jss402').fill('08:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1165 > .jss392 > .jss402').fill('08:00');
  await page.locator('.jss55 > div:nth-child(5) > .jss1165 > .jss392 > .jss402').first().fill('20:00_');
  await page.locator('.jss55 > div:nth-child(5) > .jss1165 > .jss392 > .jss402').first().press('ControlOrMeta+a');
  await page.locator('.jss392.jss379.jss383.jss394 > .jss402').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1165 > .jss392 > .jss402').fill('20:00');
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1165 > .jss392 > .jss402').fill('20:00');
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1165 > .jss392 > .jss402').fill('20:00');
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1165 > .jss392 > .jss402').fill('20:00');
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1165 > .jss392 > .jss402').fill('20:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1165 > .jss392 > .jss402').fill('20:00');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PAT-Lawson');
  await page.locator('[data-test="input-tempat-lahir"]').fill('Bataszek');
  await page.locator('input[name="address"]').fill('Jl Bataszek no 2345');
  await page.locator('input[name="postcode"]').fill('256');
  await page.locator('[data-test="input-complaint"]').fill('Cek Validasi Vavrian Schedula Unlimited');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PAT-');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-namaKatalogMcu-0"]').fill('PAT-Electronystagmography');
  await page.locator('[data-test="input-namaMcu-0"]').fill('Electronystagmography');
  await page.locator('[data-test="input-namaMcu-0"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-namaMcu-0"]').fill('01-Elec');
  await page.locator('[data-test="input-namaMcu-1"]').fill('Elec');
  await page.locator('[data-test="input-harga-0"]').press('Shift+ArrowRight');
  await page.locator('[data-test="input-harga-0"]').fill('Rp30.0000');
  await page.locator('[data-test="input-harga-1"]').fill('Rp2.0000');
  await page.locator('[data-test="input-namaMcu-1"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('[data-test="input-namaMcu-1"]').fill('02-Elec');
  await page.locator('[data-test="input-keterangan-1"]').fill('Elec Res 01');
  await page.locator('[data-test="input-keterangan-1"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-keterangan-1"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-keterangan-1"]').fill('Elec Res 02');
  await page.locator('[data-test="input-min-0"]').fill('2');
  await page.locator('[data-test="input-max-0"]').fill('5');
  await page.locator('[data-test="input-satuan-0"]').fill('Scale');
  await page.locator('[data-test="autocomplete-input"]').fill('PAT-');
  await page.locator('[data-test="autocomplete-input"]').press('ControlOrMeta+a');
  await page.locator('[data-test="autocomplete-input"]').fill('');
  await page.goto('https://dev-essensial.assist.id/apotek');
  await page.getByText('Tambah Data Obat BaruBarcodeNama Obat *Kategori Obat *Dosis mg/ml *Stok').press('Escape');
  await page.getByRole('button', { name: 'Tambah Data Obat' }).press('Escape');
  await page.locator('input[name="barcode"]').fill('PAT-M-01');
  await page.locator('input[name="barcode"]').press('Tab');
  await page.locator('input[name="medName"]').fill('PAT-Montelukast');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('PAT');
  await page.getByRole('textbox', { name: 'Jenis' }).fill('Anti');
  await page.getByRole('textbox', { name: 'Satuan *' }).fill('Pil');
  await page.locator('input[name="dosage"]').fill('10 mg');
  await page.locator('input[name="stockTotalObat"]').fill('0200');
  await page.locator('input[name="batchNo"]').fill('BCH-00123');
  await page.locator('input[name="buyFee"]').fill('Rp3000,00');
  await page.locator('tr:nth-child(4) > .jss85237 > div > div > div:nth-child(3) > .jss83647 > .jss392 > .jss402').fill('Rp5000');
  await page.locator('input[name="sellOtcFee"]').fill('Rp6000');
  await page.locator('[data-test="parent-autocomplete-nama-depot"] [data-test="autocomplete-input"]').fill('');
  await page.locator('input[name="barcode"]').fill('PAT-M-02');
  await page.locator('input[name="barcode"]').press('Tab');
  await page.locator('input[name="medName"]').fill('PAT-Fluoxetine (Prozac)');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('PAT');
  await page.getByRole('textbox', { name: 'Jenis' }).fill('Anti');
  await page.getByRole('textbox', { name: 'Satuan *' }).fill('Ampule');
  await page.locator('input[name="dosage"]').fill('10 ml');
  await page.locator('input[name="stockTotalObat"]').fill('0300');
  await page.locator('input[name="batchNo"]').fill('BCH-018243');
  await page.locator('input[name="buyFee"]').fill('Rp4000,00');
  await page.locator('input[name="buyFee"]').press('Tab');
  await page.locator('tr:nth-child(4) > .jss85237 > div > div > div:nth-child(3) > .jss83647 > .jss392 > .jss402').fill('Rp2.3423');
  await page.locator('tr:nth-child(4) > .jss85237 > div > div > div:nth-child(3) > .jss83647 > .jss392 > .jss402').press('ControlOrMeta+a');
  await page.locator('.jss392.jss379.jss383.jss401.jss386.jss394 > .jss402').fill('Rp6000');
  await page.locator('.jss392.jss379.jss383.jss401.jss386.jss394 > .jss402').press('Tab');
  await page.locator('input[name="sellOtcFee"]').fill('Rp1.0000');
  await page.goto('https://dev-essensial.assist.id/profile');
  await page.getByRole('textbox', { name: 'Perusahaan' }).fill('PT');
  await page.locator('[data-test="autocomplete-metode-pembayaran-debit"] [data-test="autocomplete-input"]').fill('Debit');
  await page.locator('[data-test="autocomplete-metode-pembayaran-asuransi"] [data-test="autocomplete-input"]').press('ControlOrMeta+a');
  await page.locator('[data-test="autocomplete-metode-pembayaran-asuransi"] [data-test="autocomplete-input"]').fill('');
  await page.locator('[data-test="autocomplete-metode-pembayaran-kredit"] [data-test="autocomplete-input"]').fill('Kredi');
  const downloadPromise = page.waitForEvent('download');
  await page.goto('https://dev-essensial.assist.id/apotek');
  const download = await downloadPromise;
  await page2.getByRole('button', { name: 'Show in Finder' }).click();
  await page2.getByRole('link', { name: '5e5c400b-198a-440a-b00d-' }).click();
  await page.getByRole('button', { name: 'Drag & drop files orbrowse' }).setInputFiles('Import Harga Obat (3).xlsx');
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('PAT-');
  await page.locator('[data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="quantity-input"]').fill('1');
  await page.getByText('Perhatian!Anda Telah').press('ControlOrMeta+-');
  await page.locator('#cashAddBtn').press('ControlOrMeta+=');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-namaProsedur-0"]').fill('PAT-Rancho Los Amigos Scale');
  await page.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').fill('');
  await page.locator('[data-test="input-namaProsedur-0"]').fill('PAT-Rancho Los Amigos Scale');
  await page.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').fill('Sal');
  await page.locator('[data-test="input-hargaProsedur-0"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-hargaProsedur-0"]').fill('Rp3.000.00');
  await page.locator('[data-test="input-namaProsedur-1"]').fill('PAT-Cholecystectomy');
  await page.locator('[data-test="parent-autocomplete-namaPraktek-1"]').getByRole('textbox', { name: 'Nama Praktek' }).fill('Sal');
  await page.locator('[data-test="input-hargaProsedur-1"]').fill('Rp40.0000');
  await page.locator('[data-test="input-namaProsedur-2"]').fill('PAT-Negative room pressure');
  await page.locator('[data-test="parent-autocomplete-namaPraktek-2"]').getByRole('textbox', { name: 'Nama Praktek' }).fill('Salga');
  await page.locator('[data-test="input-hargaProsedur-2"]').press('Shift+ArrowRight');
  await page.locator('[data-test="input-hargaProsedur-2"]').fill('Rp50.0000');
  await page.locator('[data-test="input-packageName-0"]').fill('PAT-Paket-');
  await page.locator('[data-test="autocomplete-input"]').fill('PAT-');
  await page.locator('[data-test="input-packageName-0"]').fill('PAT-Paket-[Chloe + Negative] 2x2');
  await page.locator('[data-test="input-procedureQuantity-0-0"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-procedureQuantity-0-0"]').fill('2');
  await page.locator('[data-test="input-procedureQuantity-0-1"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-procedureQuantity-0-1"]').fill('2');
  await page.locator('[data-test="input-packagePrice-0"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-packagePrice-0"]').fill('Rp150.0000');
  await page.locator('[data-test="input-packageName-1"]').fill('Pass');
  await page.locator('[data-test="input-packageName-0"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-packageName-0"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-packageName-0"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-packageName-1"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-packageName-1"]').fill('PAT-Paket-[Chloe + Negative] 2x2');
  await page.locator('[data-test="input-packageName-1"]').press('ArrowLeft');
  await page.locator('[data-test="input-packageName-1"]').press('ArrowLeft');
  await page.locator('[data-test="input-packageName-1"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-packageName-1"]').fill('PAT-Paket-[Chloe + Negative] 1x2');
  await page.locator('[data-test="input-packageName-1"]').press('ControlOrMeta+ArrowRight');
  await page.locator('[data-test="autocomplete-input"]').fill('PAT-');
  await page.locator('[data-test="input-procedureQuantity-1-0"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-procedureQuantity-1-0"]').fill('1');
  await page.locator('[data-test="input-procedureQuantity-1-1"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-procedureQuantity-1-1"]').fill('2');
  await page.locator('[data-test="input-packageDuration-0"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-packageDuration-0"]').fill('6000');
  await page.locator('[data-test="input-packageDuration-1"]').fill('5000');
  await page.locator('[data-test="input-packagePrice-1"]').press('Shift+ArrowRight');
  const download1Promise = page.waitForEvent('download');
  await page.locator('[data-test="input-packagePrice-1"]').fill('Rp75.0000');
  const download1 = await download1Promise;
  await page2.getByRole('link', { name: '4ea1d1d6-39f6-468b-affe-' }).click();
  await page2.getByRole('row', { name: 'Today 4ea1d1d6-39f6-468b-affe' }).getByLabel('Show in Finder').click();
  await page.getByRole('button', { name: 'Drag & drop files orbrowse' }).setInputFiles('Import Katalog Harga Prosedur (2).xlsx');
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('PAT');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').fill('1');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('1');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-defaultCommissionType"]').selectOption('percent');
  await page.locator('[data-test="input-defaultCommissionValue"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-defaultCommissionValue"]').fill('10%');
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').fill('anisasecondacc24@gmail.com');
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="input-password"]').press('Enter');
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').fill('anisasecondacc24@gmail.com');
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="input-password"]').press('Enter');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PAT-');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.getByRole('button', { name: 'Info Tenaga Medis' }).press('Escape');
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').fill('griffithwhale');
  await page.locator('#username').press('ControlOrMeta+a');
  await page.locator('#username').fill('anisasecondacc23@gmail.com');
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.goto('https://dev-essensial.assist.id/');
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).fill('nantii!!');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-nama"]').fill('PAT-Lainey');
  await page.locator('[data-test="input-telepon"]').fill('08121312314122');
  await page.locator('[data-test="input-noKTP"]').fill('23432452424');
  await page.locator('.jss124160.jss124147.jss124151.jss124161.jss124148.jss124165.jss125714 > .jss124170').first().fill('08:00_');
  await page.locator('.jss124160.jss124147.jss124151.jss124161.jss124148.jss124165.jss125714 > .jss124170').first().press('ControlOrMeta+a');
  await page.locator('.jss124160.jss124147.jss124151.jss124161.jss124148.jss124165.jss125714 > .jss124170').first().press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('anisasecondacc23@gmail.com');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').press('ControlOrMeta+a');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').fill('08:00_');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').press('Shift+ArrowLeft');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').press('ControlOrMeta+c');
  await page.locator('div:nth-child(4) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('anisasecondacc23@gmail.com');
  await page.locator('div:nth-child(5) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('anisasecondacc23@gmail.com');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').first().press('ControlOrMeta+a');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').first().fill('08:00_');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').first().press('Shift+ArrowLeft');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').press('Shift+ArrowLeft');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').press('Shift+ArrowLeft');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').press('ControlOrMeta+Shift+ArrowRight');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').fill('08:00_');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').press('ControlOrMeta+a');
  await page.locator('div:nth-child(6) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('div:nth-child(7) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('div:nth-child(8) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('.jss123840 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').first().fill('2300');
  await page.locator('div:nth-child(3) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(4) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(5) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(6) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(7) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(8) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('.jss123840 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').first().fill('2300');
  await page.locator('div:nth-child(3) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(4) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(5) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(6) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(7) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(8) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('.jss124160.jss124147.jss124151.jss124161.jss124148.jss124165.jss126283 > .jss124170').first().fill('0800');
  await page.locator('div:nth-child(3) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('div:nth-child(4) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('div:nth-child(5) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('div:nth-child(6) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('div:nth-child(7) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('div:nth-child(8) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('[data-test="input-nama"]').fill('PAT-Emory');
  await page.locator('.jss124160.jss124147.jss124151.jss124161.jss124148.jss124165.jss126899 > .jss124170').first().fill('08_:__');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').fill('00_:__');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').press('ControlOrMeta+a');
  await page.locator('.jss124160.jss124147.jss124151.jss124166 > .jss124170').fill('0800');
  await page.locator('div:nth-child(3) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('div:nth-child(4) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('div:nth-child(5) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('div:nth-child(6) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('div:nth-child(8) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('div:nth-child(7) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(3) > .jss124911 > .jss124160 > .jss124170').fill('0800');
  await page.locator('.jss123840 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').first().fill('2300');
  await page.locator('div:nth-child(3) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(4) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(5) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(6) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(7) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.locator('div:nth-child(8) > .jss123840.jss123841.jss123848.jss123880 > div:nth-child(5) > .jss124911 > .jss124160 > .jss124170').fill('2300');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-nama-lengkap"]').fill('Gesi [Griffith');
  await page.locator('[data-test="input-email"]').fill('griffithwhales@gmail.com');
  await page.locator('[data-test="input-nomor-hp"]').fill('0890-8979-123131');
  await page.locator('[data-test="input-nama-praktek"]').fill('pat');
  await page.locator('[data-test="input-nama-lengkap"]').fill('Gesi [Griffith | Emory]');
  await page.locator('[data-test="input-jabatan"]').fill('QA');
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('PAT');
  await page.locator('html').getByRole('document').press('Escape');
  await page.goto('https://dev-essensial.assist.id/layanan-tambahan');
  await page.getByRole('textbox', { name: 'Cari nama add on' }).fill('De');
  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('textbox', { name: 'Cari nama add on' }).press('Escape');
  const page3 = await page3Promise;
  await page3.goto('https://dev-adv-report.assist.id/login');
  await page3.locator('div').filter({ hasText: 'Advanced ReportingSelamat' }).nth(2).click();
  await page3.getByRole('heading', { name: 'Pantau Performa Seluruh' }).click();
  await page.goto('https://dev-essensial.assist.id/apotek');
  await page.locator('[data-test="input-barcode"]').fill('PAT-B-01');
  await page.locator('[data-test="input-nama-barang"]').fill('PAT-B-issue');
  await page.locator('[data-test="input-nama-barang"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-nama-barang"]').fill('PAT-B-Tissue');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('PAT');
  await page.getByRole('textbox', { name: 'Jenis' }).fill('Anti');
  await page.locator('[data-test="input-stok-barang"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-stok-barang"]').fill('0300');
  await page.getByRole('textbox', { name: 'Satuan *' }).fill('Kotak');
  await page.locator('[data-test="input-dosage"]').fill('S');
  await page.locator('[data-test="input-batch-no"]').fill('PAT');
  await page.locator('[data-test="input-batch-no"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-batch-no"]').fill('BCH-B0-01');
  await page.locator('[data-test="input-batch-no"]').press('ArrowLeft');
  await page.locator('[data-test="input-batch-no"]').fill('BCH-0-01');
  await page.locator('[data-test="input-batch-no"]').press('Shift+ArrowRight');
  await page.locator('[data-test="input-harga-beli"]').fill('Rp3000,00');
  await page.locator('[data-test="input-harga-otc"]').fill('Rp70.00');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PAT-');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-nameRoom"]').fill('PAT-Hale');
  await page.locator('[data-test="input-jumlahKamar"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-jumlahKamar"]').fill('4');
  await page.locator('[data-test="input-jumlahBed"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-jumlahBed"]').fill('50');
  await page.locator('[data-test="input-price"]').fill('Rp2.0000');
  await page.locator('[data-test="input-kodeKamar"]').fill('PAT-01');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PAT-');
  await page.goto('https://dev-essensial.assist.id/registration');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PAT-');
  await page.goto('https://dev-essensial.assist.id/office');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('marg');
  await page.getByRole('button', { name: 'Filter Data' }).press('Escape');
  await page.goto('https://dev-essensial.assist.id/office');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('mar');
  await page.locator('html').getByRole('document').press('Escape');
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('PAT-');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').fill('1');
  await page.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').press('ArrowDown');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').press('Shift+ArrowDown');
  await page.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('01');
  await page.locator('[data-test="kasir-item-2"] [data-test="quantity-input"]').fill('01');
  await page.locator('[data-test="input-bayar-langsung"]').fill('Rp42.0000');
  await page.locator('[data-test="input-dibayar-oleh-langsung"]').fill('Rando');
  await page.goto('https://dev-essensial.assist.id/office');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('margin');
  await page.locator('html').getByRole('document').press('Escape');
  await page.locator('input[name="invoiceNo"]').fill('INVO-01');
  await page.locator('input[name="invoiceNo"]').press('ArrowLeft');
  await page.locator('input[name="invoiceNo"]').press('ArrowLeft');
  await page.locator('input[name="invoiceNo"]').press('ArrowRight');
  await page.locator('input[name="invoiceNo"]').fill('INVO-Code-01');
  await page.locator('input[name="itemName"]').fill('Sapu');
  await page.getByRole('textbox').nth(3).fill('Kain Pel');
  await page.getByRole('textbox').nth(2).fill('Rp. 3.0000');
  await page.getByRole('textbox').nth(4).fill('Rp. 5.0000');
  await page.getByRole('textbox').nth(5).fill('Cairan Pel');
  await page.locator('div:nth-child(3) > .jss230935.jss230967 > .jss231102 > .jss231137 > .jss231147').fill('Rp. 2.0000');
  await page.locator('textarea[name="freeText"]').fill('Random Nites ');
  await page.locator('textarea[name="freeText"]').press('ArrowLeft');
  await page.locator('textarea[name="freeText"]').press('ArrowLeft');
  await page.locator('textarea[name="freeText"]').press('ArrowLeft');
  await page.locator('textarea[name="freeText"]').press('Shift+ArrowRight');
  await page.locator('textarea[name="freeText"]').fill('Random Notes ');
  await page.locator('textarea[name="freeText"]').press('ControlOrMeta+ArrowRight');
  await page.locator('textarea[name="freeText"]').fill('Random Notes , apkaah tampil di Pengluaran?');
  await page.locator('textarea[name="freeText"]').press('Alt+ArrowLeft');
  await page.locator('textarea[name="freeText"]').press('Alt+ArrowLeft');
  await page.locator('textarea[name="freeText"]').press('Alt+ArrowLeft');
  await page.locator('textarea[name="freeText"]').press('ArrowRight');
  await page.locator('textarea[name="freeText"]').press('ArrowRight');
  await page.locator('textarea[name="freeText"]').press('ArrowRight');
  await page.locator('textarea[name="freeText"]').press('ArrowLeft');
  await page.locator('textarea[name="freeText"]').fill('Random Notes , apakaah tampil di Pengluaran?');
  await page.locator('textarea[name="freeText"]').press('ArrowRight');
  await page.locator('textarea[name="freeText"]').press('ArrowRight');
  await page.locator('textarea[name="freeText"]').fill('Random Notes , apakah tampil di Pengluaran?');
  await page.goto('https://dev-essensial.assist.id/apotek');
});