import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app.assist.id/login');
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#password').click();
  await page.locator('#password').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.getByRole('button', { name: 'close' }).click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.locator('.jss1196').click();
  await page.locator('[data-test="sidebar-item-akreditasi"]').click();
  await page.getByRole('button', { name: 'LENGKAPI' }).first().click();
  await page.getByRole('cell', { name: 'BELUM SELESAI' }).first().click();
  await page.locator('#gambar').click();
  await page.locator('#gambar').setInputFiles('Cat 11.jpg');
  await page.locator('#dokumenBukti').click();
  await page.locator('#dokumenBukti').setInputFiles('Cat 11.jpg');
  await page.locator('div:nth-child(4) > .jss279.jss316 > div > div:nth-child(2) > .jss278 > div:nth-child(2) > ul > li > div > svg:nth-child(5)').click();
  await page.locator('div').filter({ hasText: /^Dokumen Bukti$/ }).nth(1).click();
  await page.locator('#dokumenBukti').click();
  await page.locator('#dokumenBukti').setInputFiles('Cat 05.jpg');
  await page.getByRole('checkbox', { name: 'Selesai' }).check();
  await page.getByRole('button', { name: 'SIMPAN' }).click();
  await page.locator('#kamarmedis-content').getByRole('heading', { name: 'Akreditasi' }).click();
  await page.getByText('Pastikan Faskes Anda Sudah Memenuhi Syarat-syarat AkreditasiInformasi').click();
  await page.locator('[data-test="sidebar-item-layananTambahn"]').click();
  await page.getByRole('button', { name: 'Atur Kartu & Url' }).click();
  await page.locator('div').filter({ hasText: /^Telekonsultasi$/ }).first().click();
  await page.getByText('Diagnostic Partner').click();
  await page.locator('div').filter({ hasText: /^Add Ons$/ }).first().click();
  await page.getByText('Capaian Minggu Ini: 0%').click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.getByText('Atur fungsional assist.id per modulnyaCloseNext').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.getByRole('button', { name: 'Hak Akses' }).click();
  await page.getByRole('button', { name: 'Info Tenaga Medis' }).click();
  await page.getByRole('button', { name: 'Katalog Harga Prosedur' }).click();
  await page.getByRole('button', { name: 'Kamar Inap' }).click();
  await page.getByRole('button', { name: 'Printing Template' }).click();
  await page.getByRole('button', { name: 'Data Entry' }).click();
  await page.getByRole('button', { name: 'Surat Menyurat' }).click();
  await page.getByRole('button', { name: 'Surat Menyurat' }).click();
  await page.getByRole('button', { name: 'Billing !' }).click();
  await page.getByText('Tambah Vital SignClinica Lite').click();
  await page.locator('[data-test="sidebar-item-pertanyaan"]').click();
  await page.locator('div').filter({ hasText: 'Bantuan & SaranBuat' }).nth(5).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="sidebar-item-registrasi"]').click();
  await page.locator('.jss798.jss800').first().click();
  await page.getByText('Condition (Minggu ini /').click();
  await page.locator('[data-test="sidebar-item-rawat-jalan"]').click();
  await page.locator('[data-test="sidebar-item-registrasi"]').click();
  await page.locator('div').filter({ hasText: 'Rawat Jalan PoliList' }).nth(5).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.getByRole('button', { name: 'Hak Akses' }).click();
  await page.getByRole('button', { name: 'Last Page' }).click();
  await page.locator('div').filter({ hasText: 'Hak Akses+ Tambah Tipe' }).nth(5).click();
  await page.getByRole('button', { name: '+ Tambah Tipe Akses' }).click();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('textbox', { name: 'Nama Hak Akses *' }).click();
  await page.getByRole('textbox', { name: 'Nama Hak Akses *' }).fill('All Access \'26');
  await page.getByRole('checkbox', { name: 'Dashboard', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Outpatient' }).check();
  await page.getByRole('checkbox', { name: 'Dashboard', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Emr', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Pharmacy' }).check();
  await page.getByRole('checkbox', { name: 'Cashier' }).check();
  await page.getByRole('checkbox', { name: 'Setting', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Profile', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Report' }).check();
  await page.getByRole('checkbox', { name: 'Registration' }).check();
  await page.getByRole('checkbox', { name: 'Teleconsult', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Pks', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Bantuan Dan Saran' }).check();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.getByRole('textbox', { name: 'Cari staff' }).click();
  await page.getByRole('textbox', { name: 'Cari staff' }).fill('gesi');
  await page.locator('.jss5079 > .jss278 > div > .jss478').first().click();
  await page.getByRole('button', { name: 'Owner' }).click();
  await page.getByRole('option', { name: 'All Access \'' }).click();
  await page.getByRole('textbox', { name: 'Nama Praktek' }).click();
  await page.getByRole('textbox', { name: 'Nama Praktek' }).fill('');
  await page.getByRole('textbox', { name: 'Nama Praktek' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Nama Praktek' }).fill(' ');
  await page.getByRole('menuitem', { name: 'CL-Felix McCann' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(6) > .jss278 > div > .jss478').first().click();
  await page.locator('#tanggal-lahir').click();
  await page.getByRole('heading', { name: '2026' }).click();
  await page.getByRole('button', { name: '1982' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Owner' }).click();
  await page.locator('#menu-').getByText('All Access \'').click();
  await page.getByRole('textbox', { name: 'Nama Praktek' }).click();
  await page.getByRole('textbox', { name: 'Nama Praktek' }).fill(' ');
  await page.getByRole('menuitem', { name: 'CL-Felix McCann' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('https://app.assist.id/settings');
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.locator('.jss1260').click();
  await page.locator('.jss55.jss152').click();
  await page.locator('[data-test="sidebar-item-office"]').click();
  await page.locator('[data-test="sidebar-item-office"]').click();
  await page.getByRole('button', { name: 'Laporan', description: 'Semua laporan yang terkait dengan operational dan keuangan, dan laporan tersebut bisa diexport ke Excel / PDF dan bisa diprint', exact: true }).click();
  await page.getByRole('textbox', { name: 'Cari Laporan' }).click();
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('komisi');
  await page.locator('button').filter({ hasText: 'Keuangan' }).click();
  await page.getByRole('textbox', { name: 'Cari Laporan' }).click();
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('komisi');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).press('Escape');
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '- Clinica Assist [Clinica] (QA)' }).click();
  await page.locator('div').nth(1).click();
  await page.locator('html').click();
  await page.goto('https://app.assist.id/');
  await expect(page.getByRole('dialog').getByRole('button')).toBeVisible();
  await page.getByRole('dialog').getByRole('button').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.locator('.jss784').click();
  await page.locator('.jss784').click();
  await page.goto('https://app.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('C-');
  await page1.locator('html').getByRole('document').click();
  await page1.getByRole('dialog').getByRole('button').click();
  await page1.getByRole('button', { name: 'Akun' }).click();
  await page1.getByRole('button', { name: 'Akun' }).click();
  await page1.getByRole('button', { name: 'Pasien' }).click();
  await page1.locator('.jss55.jss961').click();
  await page1.locator('div').filter({ hasText: /^ANTENG, Tanggal Lahir: 22-05-1905$/ }).click();
  await page1.getByRole('button', { name: 'Data Pasien' }).click();
  await page1.getByRole('textbox', { name: 'Search' }).click();
  await page1.getByRole('textbox', { name: 'Search' }).fill('C-');
  await page1.getByRole('textbox', { name: 'Search' }).press('Enter');
  await page1.locator('.jss56.jss91 > button').click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('CC-');
  await page.locator('[data-test="input-complaint"]').fill('Random Cek Prod');
  await page.goto('https://app.assist.id/registration');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('CC-');
  await page.locator('[data-test="input-complaint"]').fill('Add random Appt Ranap');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('CC-');
  await page1.locator('[data-test="sidebar-item-settings"]').click();
  await page1.getByRole('button', { name: 'Info Tenaga Medis' }).click();
  await page1.getByRole('textbox', { name: 'Search Name, STR or SIP' }).click();
  await page1.getByRole('textbox', { name: 'Search Name, STR or SIP' }).fill('c-');
  await page1.getByRole('textbox', { name: 'Search Name, STR or SIP' }).press('Enter');
  await page1.getByRole('button', { name: 'Edit Profil' }).click();
  await page1.getByRole('checkbox', { name: 'Jumat' }).check();
  await page1.getByRole('button', { name: 'Simpan' }).click();
  await page.goto('https://app.assist.id/registration');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('CC-');
  await page.locator('[data-test="input-complaint"]').fill('A');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('CC-');
  await page.locator('[data-test="input-complaint"]').fill('Add random ranap peraslinan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Cc-');
  await page.locator('[data-test="input-complaint"]').fill('random coba red snack slot penuh');
  await page.locator('[data-test="input-complaint"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('ControlOrMeta+Shift+ArrowRight');
  await page.locator('[data-test="input-complaint"]').fill('random coba red snack slot terisi');
  await page.goto('https://app.assist.id/settings');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('Cc-');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('Asr-');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('Asr');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('');
  await page.getByRole('textbox').first().fill('CC-Plasmapheresis');
  await page.getByRole('textbox', { name: 'Nama Praktek' }).fill('C-');
  await page.getByRole('textbox').nth(1).press('Shift+ArrowLeft');
  await page.getByRole('textbox').nth(1).press('Shift+ArrowRight');
  await page.getByRole('textbox').nth(1).fill('Rp20.0000');
  await page.getByRole('textbox', { name: 'Nama Praktek' }).nth(1).fill('C-');
  await page.locator('div:nth-child(2) > div > div:nth-child(2) > div:nth-child(2) > .jss283082 > .jss283117 > .jss283127').press('Shift+ArrowLeft');
  await page.locator('.jss283117.jss283104.jss283108.jss283126.jss283111.jss283119 > .jss283127').fill('Rp50.0000');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('cc');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('cc-');
  await page.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page1.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page1.getByRole('textbox', { name: 'Cari staff' }).click();
  await page1.getByRole('textbox', { name: 'Cari staff' }).fill('gesi');
  await page1.getByRole('textbox', { name: 'Cari staff' }).press('Enter');
  await page1.getByRole('button', { name: 'Tambah Staff' }).click();
  await page1.getByRole('textbox', { name: 'Nama Lengkap' }).click();
  await page1.getByRole('textbox', { name: 'Nama Lengkap' }).fill('Gesi []');
  await page1.getByRole('textbox', { name: 'Nama Lengkap' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Nama Lengkap' }).fill('Gesi [Acc23]');
  await page1.locator('#tanggal-lahir').click();
  await page1.getByRole('heading', { name: '2026' }).click();
  await page1.getByRole('button', { name: '1982' }).click();
  await page1.getByRole('button', { name: '14' }).click();
  await page1.getByRole('button', { name: 'OK' }).click();
  await page1.getByRole('button', { name: 'Pilih Tipe Akses' }).click();
  await page1.locator('div').filter({ hasText: /^Owner$/ }).nth(2).click();
  await page1.getByRole('textbox', { name: 'Jabatan' }).click();
  await page1.getByRole('textbox', { name: 'Jabatan' }).fill('QA');
  await page1.getByText('Nama Lengkap *Tanggal Lahir *Jabatan *Tipe Akses *OwnerAlamat Email *Nomor Hp *').click();
  await page1.getByRole('textbox', { name: 'Alamat Email' }).click();
  await page1.locator('div').filter({ hasText: 'Jabatan *' }).nth(4).click();
  await page1.getByRole('textbox', { name: 'Alamat Email' }).click();
  await page1.getByRole('textbox', { name: 'Alamat Email' }).fill('anisasecondacc23@gmail.com');
  await page1.getByRole('textbox', { name: 'Nomor Pegawai' }).click();
  await page1.getByRole('textbox', { name: 'Nomor Hp' }).click();
  await page1.getByRole('textbox', { name: 'Nomor Hp' }).fill('0808-1909-8123');
  await page1.getByRole('textbox', { name: 'Nama Praktek' }).click();
  await page1.getByRole('textbox', { name: 'Nama Praktek' }).fill(' ');
  await page1.locator('div').filter({ hasText: 'Nomor Pegawai' }).nth(4).click();
  await page1.locator('div').filter({ hasText: 'Simpan' }).nth(2).click();
  await page1.getByRole('button', { name: 'Simpan' }).click();
  await page1.getByRole('button', { name: 'Ok' }).click();
  await page1.getByRole('heading', { name: 'Manajemen Staff' }).click();
  await page1.locator('#mainLayoutContainer').click();
  await page1.locator('div').filter({ hasText: /^Filter$/ }).first().click();
  await page1.getByRole('button', { name: 'Hak Akses' }).click();
  await page1.getByRole('button', { name: 'Last Page' }).click();
  await page1.getByRole('button', { name: 'Previous Page' }).click();
  await page1.locator('div').filter({ hasText: /^5$/ }).first().click();
  await page1.locator('.jss2686').click();
  await page1.getByRole('button', { name: '+ Tambah Tipe Akses' }).click();
  await page1.getByRole('button', { name: 'Nothing' }).click();
  await page1.getByRole('option', { name: 'Nothing' }).press('ControlOrMeta+f');
  await page1.getByRole('option', { name: 'Nothing' }).click();
  await page1.locator('.jss2691.jss2692').click();
  await page1.getByRole('textbox', { name: 'Nama Hak Akses *' }).fill('All Access \'26');
  await page1.getByRole('textbox', { name: 'Cari staff' }).fill('gesi');
  await page1.getByRole('textbox', { name: 'Nama Praktek' }).fill('C-');
  await page1.goto('https://app.assist.id/settings');
  await page1.locator('html').getByRole('document').click();
  await page1.getByRole('dialog').getByRole('button').click();
  await page1.locator('div').filter({ hasText: /^General Settings$/ }).nth(2).click();
  await page1.getByText('Bridging Satu SehatBridging').click();
  await page1.locator('div').filter({ hasText: 'General SettingsManajemen' }).nth(5).click();
  await page1.getByText('General SettingsBridging Satu').click();
  await page1.locator('div').filter({ hasText: 'General SettingsBridging Satu' }).nth(5).click();
  await page1.getByText('Bridging Satu SehatBridging').click();
  await page1.locator('div').filter({ hasText: /^Bridging Antrean Online$/ }).click();
  await page1.getByRole('heading', { name: 'General Settings' }).click();
  await page1.getByText('Bridging Satu SehatBridging').click();
  await page1.getByText('Bridging Satu SehatBridging').click();
  await page1.getByRole('heading', { name: 'Bridging Satu Sehat' }).click();
  await page1.getByRole('heading', { name: 'CenterView' }).click();
  await page1.getByRole('heading', { name: 'CenterView' }).click();
  await page1.getByRole('heading', { name: 'Input Informasi Kredensial' }).click();
  await page1.locator('.jss825').click();
  await page1.locator('#mainLayoutContainer').click();
  await page1.locator('[data-test="sidebar-item-kasir"]').click();
  await page1.getByRole('button', { name: 'Biaya Booking' }).click();
  await page1.locator('#mainLayoutContainer').click();
  await page1.locator('[data-test="sidebar-item-layananTambahn"]').click();
  await page1.locator('div').filter({ hasText: /^Discount$/ }).first().click();
  await page1.getByText('Data DiscountTambah Discount').click();
  await page1.getByRole('button', { name: 'Tambah Discount' }).click();
  await page1.getByRole('textbox').first().click();
  await page1.getByRole('textbox').first().fill('');
  await page1.locator('.jss1663').click();
  await page1.getByRole('textbox').first().fill('Disc Input Ava');
  await page1.getByRole('textbox').nth(1).press('ArrowLeft');
  await page1.getByRole('textbox').nth(1).press('ArrowLeft');
  await page1.getByRole('textbox').nth(1).press('ArrowLeft');
  await page1.getByRole('textbox').nth(1).press('Shift+ArrowLeft');
  await page1.getByRole('textbox').nth(1).fill('Rp. 5.0000,00');
  await page1.getByRole('textbox').nth(3).fill('Desc Random');
  await page1.goto('https://app.assist.id/cashier');
  await page1.locator('[data-test="autocomplete-input"]').fill('CC-');
  await page1.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('Ranspm');
  await page1.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).press('ControlOrMeta+a');
  await page1.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('CC-');
  await page1.goto('https://app.assist.id/emr');
  await page1.locator('[data-test="autocomplete-input"]').fill('Cough');
  await page1.getByRole('textbox', { name: 'Cari fitur' }).fill('pro');
  await page1.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').fill('Cc');
  await page1.locator('[data-test="autocomplete-input"]').fill('Cough');
  await page1.goto('https://app.assist.id/settings');
  await page1.getByRole('textbox', { name: 'Cari staff' }).fill('ges');
  await page1.goto('https://app.assist.id/settings');
  await page1.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('c-');
  await page1.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page1.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('cci-');
  await page1.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page1.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('cc');
  await page1.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
  await page1.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).fill('cc-');
  await page1.getByRole('textbox', { name: 'Cari Prosedur/Tindakan' }).press('Enter');
});