import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('div').nth(1).click();
  await page.locator('body').press('Escape');
  await page.locator('#username').click();
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#username').press('Tab');
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: 'Tambah Akun' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('Hart []');
  await page.getByRole('textbox').press('ArrowLeft');
  await page.getByRole('textbox').fill('Hart [Privata V2]');
  await page.getByRole('textbox').press('ArrowRight');
  await page.getByRole('textbox').press('Enter');
  await page.getByRole('radio', { name: 'Dibawah satu tahun.' }).check();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('-11');
  await page.getByRole('spinbutton').press('Enter');
  await page.getByRole('button').nth(3).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').press('ArrowRight');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-12');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-13');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-14');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-15');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-16');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-17');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-18');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-19');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-20');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-21');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-22');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-23');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-24');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-25');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-26');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-27');
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-28');
  await page.getByRole('radio', { name: 'Tidak' }).check();
  await page.locator('#q3 > .jss1213.jss1241').click();
  await page.locator('.jss423.jss1474').click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').press('ArrowDown');
  await page.getByRole('spinbutton').fill('-29');
  await page.locator('div').filter({ hasText: 'InformasiNama fasilitas' }).nth(1).click();
  await page.getByText('Verifikasi2Informasi').click();
  await page.locator('div').filter({ hasText: 'InformasiNama fasilitas' }).nth(1).click();
  await page.locator('.jss423.jss1474').click();
  await page.getByRole('radio', { name: 'Belum Akreditasi' }).check();
  await page.getByRole('radio', { name: 'Instalasi farmasi' }).check();
  await page.getByRole('radiogroup').filter({ hasText: 'IyaTidak' }).getByLabel('Tidak').check();
  await page.locator('input[name="namaJalan"]').fill('Jl Hart no 1234');
  await page.locator('input[name="npwpName"]').fill('NPWP Hart');
  await page.locator('input[name="npwpName"]').press('Tab');
  await page.locator('input[name="npwp"]').fill('23424234');
  await page.locator('input[name="npwpAddress"]').fill('NPWP Hart Alamaat');
  await page.locator('input[name="npwpAddress"]').press('ArrowLeft');
  await page.locator('input[name="npwpAddress"]').fill('NPWP Hart Alamat');
  await page.goto('https://dev-essensial.assist.id/');
  await page1.locator('body').click();
  await page1.goto('https://uat-panela.assist.id/login');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page1.locator('div').nth(4).click();
  await page1.getByRole('textbox', { name: 'Masukkan username anda' }).fill('annisa.ghaisani@assist.id');
  await page1.getByRole('textbox', { name: 'Masukkan username anda' }).click();
  await page1.getByRole('textbox', { name: 'Masukkan password anda' }).click();
  await page1.getByRole('textbox', { name: 'Masukkan password anda' }).fill('12345678');
  await page1.getByRole('textbox', { name: 'Masukkan password anda' }).press('Enter');
  await page1.getByRole('button', { name: 'Sign In' }).click();
  await page1.getByRole('button', { name: 'Berlangganan' }).click();
  await page1.getByRole('button', { name: 'Solmet' }).click();
  await page1.getByRole('button', { name: 'RME' }).click();
  await page1.getByRole('textbox', { name: 'Pencarian', exact: true }).click();
  await page1.getByRole('textbox', { name: 'Pencarian', exact: true }).fill('hart');
  await page1.getByRole('textbox', { name: 'Pencarian', exact: true }).press('Enter');
  await page1.getByRole('button', { name: 'Filter', exact: true }).click();
  await page.goto('https://app.sandbox.midtrans.com/snap/v4/redirection/4cba6bcf-3175-4e87-81d0-94381221fef4#/payment-list');
  await page.locator('#app').click();
  await page2.goto('https://simulator.sandbox.midtrans.com/bca/va/index');
  await page.getByRole('link', { name: 'banklogo BCA virtual account' }).click();
  await page.getByText('Copy').click();
  await page2.locator('#inputMerchantId').click();
  await page2.locator('#inputMerchantId').fill('22646207661953594876580');
  await page2.getByRole('button', { name: 'Inquire' }).click();
  await page2.getByRole('button', { name: 'Pay' }).click();
  await page.getByRole('button', { name: 'Check status' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page1.getByRole('button', { name: 'Filter', exact: true }).click();
  await page1.getByLabel('simple table').getByRole('button').filter({ hasText: /^$/ }).click();
  await page1.getByRole('menuitem', { name: 'Ubah Masa Berlangganan' }).click();
  await page1.locator('div').filter({ hasText: 'Ubah Masa Berlangganan Faskes' }).nth(1).press('Escape');
  await page1.getByLabel('simple table').getByRole('button').filter({ hasText: /^$/ }).click();
  await page1.getByText('Ubah Produk').click();
  await page1.locator('div').filter({ hasText: 'Ubah Produk Faskes Hart [' }).nth(1).click();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('button', { name: 'Nanti Saja' }).click();
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).click();
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).fill('nanti saja');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByText('🎉 Segera Aktifkan akun Anda untuk nikmati fitur tanpa hambatanGo Live').click();
  await page.goto('https://dev-essensial.assist.id/wizard');
  await page.getByRole('textbox').fill('[]');
  await page.getByRole('textbox').press('ArrowLeft');
  await page.getByRole('textbox').fill('[Clinica Lite V2]');
  await page.getByRole('textbox').press('ControlOrMeta+ArrowLeft');
  await page.getByRole('textbox').press('ControlOrMeta+ArrowLeft');
  await page.getByRole('textbox').fill('Wall [Clinica Lite V2]');
  await page.getByRole('spinbutton').fill('4');
  await page.getByRole('spinbutton').press('Enter');
  await page.locator('input[name="kodePos"]').fill('325252');
  await page.locator('input[name="namaJalan"]').fill('Jl Wall no 354325');
  await page.locator('input[name="npwpName"]').fill('NPWP Wall w4r43rwef');
  await page.locator('input[name="npwp"]').fill('23423423424');
  await page.locator('input[name="npwp"]').press('Tab');
  await page.locator('input[name="npwpAddress"]').fill('Alamat NPWP Wall');
  await page.goto('https://dev-essensial.assist.id/');
  await page.locator('html').getByRole('document').press('Escape');
  await page.locator('body').press('Escape');
  await page.locator('body').press('Escape');
  await page.goto('https://dev-essensial.assist.id/');
  await page.getByRole('checkbox', { name: 'Dengan mencentang persetujuan' }).check();
  await page.getByRole('button', { name: 'Setuju' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.locator('.jss915').click();
  await page.locator('.jss915').click();
  await page1.locator('div').filter({ hasText: 'Ubah Produk Faskes Hart [' }).nth(1).click();
  await page1.locator('div').filter({ hasText: 'Ubah Produk Faskes Hart [' }).nth(1).click();
  await page1.locator('div').filter({ hasText: 'Ubah Produk Faskes Hart [' }).nth(1).click();
  await page1.getByRole('button', { name: 'Batalkan' }).click();
  await page1.getByRole('textbox', { name: 'Pencarian', exact: true }).click();
  await page1.getByRole('textbox', { name: 'Pencarian', exact: true }).press('ControlOrMeta+a');
  await page1.getByRole('textbox', { name: 'Pencarian', exact: true }).fill('wall');
  await page1.getByRole('textbox', { name: 'Pencarian', exact: true }).press('Enter');
  await page1.getByRole('button', { name: 'Filter', exact: true }).click();
  await page.goto('https://app.sandbox.midtrans.com/snap/v4/redirection/ebea2df8-1335-40c6-829f-190b92233865#/payment-list');
  await page.getByRole('link', { name: 'banklogo BCA virtual account' }).click();
  await page.getByText('Copy').click();
  await page2.getByRole('link', { name: 'Simulate another BCA VA' }).click();
  await page2.locator('#inputMerchantId').click();
  await page2.locator('#inputMerchantId').fill('22646207644486731604069');
  await page2.getByRole('button', { name: 'Inquire' }).click();
  await page2.getByRole('button', { name: 'Pay' }).click();
  await page.getByRole('button', { name: 'Check status' }).click();
  await page.goto('https://dev-essensial.assist.id/?order_id=INV0000007267&status_code=200&transaction_status=settlement');
  await page.getByRole('button', { name: 'Nanti Saja' }).click();
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).click();
  await page.getByRole('textbox', { name: 'Tulis Alasan Anda' }).fill('nanti saja');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.getByRole('button', { name: 'Billing !' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page1.getByRole('button', { name: 'Filter', exact: true }).click();
  await page1.getByLabel('simple table').getByRole('button').filter({ hasText: /^$/ }).click();
  await page1.getByText('Ubah Produk').click();
  await page1.getByText('clinicaLite').click();
  await page1.getByRole('textbox', { name: 'Masukkan alasan ubah produk' }).click();
  await page1.getByRole('textbox', { name: 'Masukkan alasan ubah produk' }).fill('testing v2');
  await page1.getByRole('button', { name: 'Ubah' }).click();
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.getByRole('button', { name: 'Billing !' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.locator('.jss1038').click();
  await page.locator('div').filter({ hasText: /^Tinjauan TagihanRequest Faktur Pajak!$/ }).first().click();
  await page.getByRole('button', { name: 'Tambah Berlangganan' }).click();
  await page.getByRole('button', { name: 'Tahun' }).click();
  await page.getByRole('option', { name: '1 Bulan' }).click();
  await page.locator('#alert-dialog-title').getByText('Clinica Lite').click();
  await page.getByRole('columnheader', { name: 'Harga' }).click();
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-nama"]').fill('WL-Issac Issac');
  await page.locator('[data-test="input-nama"]').press('ControlOrMeta+z');
  await page.locator('[data-test="input-nama"]').fill('WL-Issac');
  await page.locator('[data-test="input-telepon"]').fill('081371075995');
  await page.locator('[data-test="input-email"]').fill('annisa.ghaisani@assist.id');
  await page.locator('[data-test="input-noKTP"]').fill('23535432343242');
  await page.getByRole('button', { name: 'Upload Photo Profile' }).setInputFiles('A Cat 07.png');
  await page.locator('[data-test="input-registrasiNomor"]').fill('w534534543');
  await page.locator('[data-test="input-registrasiSIPNomor"]').fill('34535345');
  await page.locator('.jss570.jss557.jss561.jss571.jss558.jss575.jss1942 > .jss580').first().fill('08:00_');
  await page.locator('.jss570.jss557.jss561.jss571.jss558.jss575.jss1942 > .jss580').first().press('ControlOrMeta+a');
  await page.locator('.jss570.jss557.jss561.jss572 > .jss580').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1273 > .jss570 > .jss580').fill('08:00');
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1273 > .jss570 > .jss580').fill('08:00');
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1273 > .jss570 > .jss580').fill('08:00');
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1273 > .jss570 > .jss580').fill('08:00');
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1273 > .jss570 > .jss580').fill('08:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss1273 > .jss570 > .jss580').fill('08:00');
  await page.locator('.jss55 > div:nth-child(5) > .jss1273 > .jss570 > .jss580').first().fill('20:00_');
  await page.locator('.jss55 > div:nth-child(5) > .jss1273 > .jss570 > .jss580').first().press('ControlOrMeta+a');
  await page.locator('.jss570.jss557.jss561.jss572 > .jss580').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1273 > .jss570 > .jss580').fill('20:00');
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1273 > .jss570 > .jss580').fill('20:00');
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1273 > .jss570 > .jss580').fill('20:00');
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1273 > .jss570 > .jss580').fill('20:00');
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1273 > .jss570 > .jss580').fill('20:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss1273 > .jss570 > .jss580').fill('20:00');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-nama"]').fill('WL-Andres');
  await page.locator('[data-test="input-nama"]').press('Tab');
  await page.getByRole('button', { name: 'Laki-laki' }).press('Tab');
  await page.locator('[data-test="input-telepon"]').press('Tab');
  await page.locator('[data-test="input-email"]').press('Tab');
  await page.getByRole('button', { name: 'Upload Photo Profile' }).setInputFiles('A Cat 05.png');
  await page.locator('[data-test="input-registrasiNomor"]').fill('23e242');
  await page.locator('[data-test="input-registrasiSIPNomor"]').fill('23424');
  await page.locator('[data-test="autocomplete-input"]').fill('Sp');
  await page.locator('.jss570.jss557.jss561.jss571.jss558.jss575.jss20799 > .jss580').first().fill('08:00_');
  await page.locator('.jss570.jss557.jss561.jss571.jss558.jss575.jss20799 > .jss580').first().press('ControlOrMeta+a');
  await page.locator('.jss570.jss557.jss561.jss572 > .jss580').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss20533 > .jss570 > .jss580').fill('08:00');
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss20533 > .jss570 > .jss580').fill('08:00');
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss20533 > .jss570 > .jss580').fill('08:00');
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss20533 > .jss570 > .jss580').fill('08:00');
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss20533 > .jss570 > .jss580').fill('08:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(3) > .jss20533 > .jss570 > .jss580').fill('08:00');
  await page.locator('.jss55 > div:nth-child(5) > .jss20533 > .jss570 > .jss580').first().fill('20:000');
  await page.locator('.jss55 > div:nth-child(5) > .jss20533 > .jss570 > .jss580').first().press('ControlOrMeta+a');
  await page.locator('.jss570.jss557.jss561.jss572 > .jss580').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss20533 > .jss570 > .jss580').fill('20:00');
  await page.locator('div:nth-child(4) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss20533 > .jss570 > .jss580').fill('20:00');
  await page.locator('div:nth-child(5) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss20533 > .jss570 > .jss580').fill('20:00');
  await page.locator('div:nth-child(6) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss20533 > .jss570 > .jss580').fill('20:00');
  await page.locator('div:nth-child(7) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss20533 > .jss570 > .jss580').fill('20:00');
  await page.locator('div:nth-child(8) > .jss55.jss56.jss63.jss95 > div:nth-child(5) > .jss20533 > .jss570 > .jss580').fill('20:00');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Belen');
  await page.locator('[data-test="input-nama-pasien"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('[data-test="input-nama-pasien"]').fill('BelenWL');
  await page.locator('[data-test="input-nama-pasien"]').press('ControlOrMeta+ArrowRight');
  await page.locator('[data-test="input-nama-pasien"]').fill('Belen');
  await page.locator('[data-test="input-nama-pasien"]').press('ControlOrMeta+ArrowDown');
  await page.locator('[data-test="input-nama-pasien"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('[data-test="input-nama-pasien"]').fill('WL-Belen');
  await page.locator('[data-test="input-nama-pasien"]').press('ControlOrMeta+ArrowRight');
  await page.locator('[data-test="input-tempat-lahir"]').fill('Fagetelu');
  await page.locator('input[name="address"]').fill('Jl Fagetelu no 1234');
  await page.locator('input[name="postcode"]').fill('35345');
  await page.locator('[data-test="input-no-ktp"]').fill('25436245');
  await page.locator('[data-test="input-nama-ibu"]').fill('Fagetelu');
  await page.locator('[data-test="input-nama-ibu"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-nama-ibu"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-nama-ibu"]').fill('Fagetelu Ibu');
  await page.locator('[data-test="input-nama-ibu"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('[data-test="input-no-telepon"]').fill('081371075995');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.locator('[data-test="input-nama-pasien"]').fill('WL-Dominik');
  await page.locator('[data-test="input-tempat-lahir"]').fill('Trodena');
  await page.locator('input[name="address"]').fill('Jl Trodena no 3424');
  await page.locator('[data-test="input-nama-ibu"]').fill('Dominik Ibu');
  await page.locator('input[name="postcode"]').fill('7987908');
  await page.goto('https://dev-essensial.assist.id/registration');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('WL-');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="btn-addRoom"]').click();
  await page.getByRole('heading', { name: 'Tambah Kamar' }).click();
  await page.locator('[data-test="input-nameRoom"]').click();
  await page.locator('[data-test="input-nameRoom"]').click();
  await page.locator('[data-test="input-nameRoom"]').fill('WR-Room-Trinity');
  await page.locator('#select-type').click();
  await page.locator('#select-type').click();
  await page.getByRole('option', { name: 'VIP', exact: true }).click();
  await page.getByText('Jumlah Kamar *').click();
  await page.locator('[data-test="input-jumlahKamar"]').click();
  await page.locator('[data-test="input-jumlahKamar"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-jumlahKamar"]').fill('40');
  await page.locator('[data-test="input-jumlahBed"]').click();
  await page.locator('[data-test="input-jumlahBed"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-jumlahBed"]').fill('50');
  await page.locator('[data-test="input-jumlahKamar"]').click();
  await page.getByText('Nama Kamar *Tipe Kamar *').click();
  await page.getByText('Nama Kamar *Tipe Kamar *').click();
  await page.locator('[data-test="input-jumlahBed"]').click();
  await page.locator('[data-test="input-jumlahBed"]').fill('10');
  await page.locator('[data-test="input-jumlahKamar"]').click();
  await page.locator('[data-test="input-jumlahKamar"]').fill('20');
  await page.locator('[data-test="input-price"]').click();
  await page.locator('[data-test="input-price"]').fill('Rp50.0000');
  await page.locator('[data-test="input-kodeKamar"]').click();
  await page.locator('[data-test="input-kodeKamar"]').fill('WRRT01');
  await page.locator('[data-test="input-isPriceLock"]').check();
  await page.getByText('Empat bed pasien').click();
  await page.getByText('Empat bed pasien').click();
  await page.getByText('Satu bed pasien').check();
  await page.locator('div').filter({ hasText: /^Meja$/ }).click();
  await page.locator('label').filter({ hasText: 'Lemari' }).click();
  await page.locator('label').filter({ hasText: 'TV LCD' }).click();
  await page.getByText('Enam bed pasien').click();
  await page.locator('label').filter({ hasText: 'Kamar mandi' }).click();
  await page.getByText('Overbed Table').click();
  await page.locator('div').filter({ hasText: 'Tambah KamarNama Kamar *Tipe' }).nth(2).click();
  await page.locator('[data-test="btn-submitAddRoom"]').click();
  await page.locator('[data-test="btn-addRoom"]').click();
  await page.locator('[data-test="input-nameRoom"]').click();
  await page.locator('[data-test="input-nameRoom"]').fill('WL-Room-');
  await page.locator('[data-test="input-nameRoom"]').click();
  await page.locator('[data-test="input-nameRoom"]').click();
  await page.locator('[data-test="input-nameRoom"]').fill('WL-Room-Wiley');
  await page.locator('#select-type').click();
  await page.getByRole('option', { name: 'VVIP' }).click();
  await page.locator('[data-test="input-jumlahKamar"]').click();
  await page.locator('[data-test="input-jumlahKamar"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-jumlahKamar"]').fill('5');
  await page.locator('[data-test="input-jumlahBed"]').click();
  await page.locator('[data-test="input-jumlahBed"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-jumlahBed"]').fill('3');
  await page.locator('[data-test="input-price"]').click();
  await page.locator('[data-test="input-price"]').fill('Rp55.0000');
  await page.locator('[data-test="input-kodeKamar"]').click();
  await page.locator('[data-test="input-kodeKamar"]').fill('WLRW-02');
  await page.locator('label').filter({ hasText: 'Dua bed pasien' }).click();
  await page.getByText('Bed penunggu').click();
  await page.getByText('Bed penunggu').click();
  await page.locator('[data-test="checkbox-facilities-Telepon"]').check();
  await page.locator('[data-test="checkbox-facilities-Meja"]').check();
  await page.locator('label').filter({ hasText: 'Alat dapur' }).click();
  await page.locator('label').filter({ hasText: 'Sofabed' }).click();
  await page.locator('label').filter({ hasText: 'TV tabung' }).click();
  await page.locator('[data-test="input-isPriceLock"]').check();
  await page.locator('[data-test="btn-submitAddRoom"]').click();
  await page.locator('[data-test="sidebar-item-rawat-jalan"]').click();
  await page.locator('[data-test="sidebar-item-registrasi"]').click();
  await page.getByRole('button', { name: 'Pendaftaran Baru' }).click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('WL-');
  await page.getByRole('button', { name: 'WL-Dominik 03-06-2004,' }).click();
  await page.getByRole('button', { name: 'Rawat Jalan' }).click();
  await page.getByRole('option', { name: 'Rawat Inap', exact: true }).click();
  await page.locator('.jss128964.jss128965.jss129004.jss128926 > div > .jss129413 > .jss129414').first().click();
  await page.getByRole('option', { name: 'WL-Room-Wiley' }).click();
  await page.locator('.jss144127').click();
  await page.getByRole('option', { name: 'dr. WL-Issac' }).click();
  await page.locator('div').filter({ hasText: '+ Rencana Tindakan' }).nth(5).click();
  await page.locator('[data-test="input-complaint"]').click();
  await page.locator('[data-test="input-complaint"]').fill('random app ranap');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('.jss55.jss56.jss63.jss73.jss106 > .jss55').click();
  await page.locator('div').filter({ hasText: 'Faktur Pajak tidak dapat' }).nth(4).click();
  await page.locator('[data-test="menu-antricepat"]').click();
  await page.locator('[data-test="menu-rawat-inap"]').click();
  await page.locator('.jss56.jss91').click();
  await page.locator('[data-test="menu-rawat-inap-persalinan"]').click();
  await page.getByRole('button', { name: 'Pendaftaran Baru' }).click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('WL-');
  await page.getByRole('button', { name: 'WL-Belen 03-06-1997,' }).click();
  await page.locator('.jss168562.jss168563.jss168602.jss168524 > div:nth-child(5)').click();
  await page.getByRole('option', { name: 'dra. WL-Andres Sp.AKAH' }).click();
  await page.getByRole('button', { name: 'Rawat Jalan' }).click();
  await page.getByRole('option', { name: 'Rawat Inap Persalinan' }).click();
  await page.locator('div').filter({ hasText: 'Nomor HP' }).nth(5).click();
  await page.locator('#select-room').click();
  await page.getByRole('option', { name: 'WR-Room-Trinity' }).click();
  await page.locator('.jss168712.jss168699.jss168703.jss168713.jss168700.jss168720').first().click();
  await page.locator('[data-test="input-complaint"]').fill('random add ranap persalinan');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('[data-test="menu-kunjungan-sehat"]').click();
  await page.locator('[data-test="menu-rawat-inap-persalinan"]').click();
  await page.locator('.jss56.jss91').click();
  await page.getByRole('cell').filter({ hasText: /^$/ }).click();
  await page.locator('[data-test="menu-rawat-jalan-poli"]').click();
  await page.getByText('Confirmed').click();
  await page.getByRole('button', { name: 'confirmed' }).click();
  await page.getByRole('button', { name: 'waiting' }).click();
  await page.getByRole('button', { name: 'waiting' }).click();
  await page.getByRole('button', { name: 'engaged' }).click();
  await page.getByRole('button', { name: 'Lihat Rekam Medis' }).click();
  await page.locator('html').click();
  await expect(page.locator('.jss1858')).toBeVisible();
  await page.locator('.jss1858').click();
  await page.locator('.jss1858').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.locator('[data-test="emrAddBtn"]').click();
  await page.locator('[data-test="emrAddBtn"]').click();
  await page.locator('.jss2360').click();
  await page.locator('.jss464 > .jss357').first().click();
  await page.locator('section:nth-child(2) > .jss304.jss308 > .jss304 > .jss357.jss1996 > .jss357.jss459.jss2001 > span > .jss357').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.locator('[data-test="emrAddBtn"]').click();
  await page.locator('[data-test="autocomplete-input"]').fill('Fever');
  await page.getByRole('button', { name: 'A01.0 Typhoid fever' }).click();
  await page.locator('[data-test="btn-simpan-diagnosa"]').click();
  await page.locator('.jss2402').click();
  await page3.goto('https://dev-essensial.assist.id/emr');
  await page3.locator('[data-test="sidebar-item-apotek"]').click();
  await page3.locator('[data-test="sidebar-item-apotek"]').click();
  await page3.getByRole('button', { name: 'Tambah Data Obat' }).click();
  await page3.locator('input[name="barcode"]').click();
  await page3.locator('input[name="barcode"]').fill('');
  await page3.locator('input[name="medName"]').click();
  await page3.locator('input[name="medName"]').fill('WL-OB-Domperidone');
  await page3.getByRole('textbox', { name: 'Nama Brand Farmasi' }).click();
  await page3.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('WLM');
  await page3.getByRole('button', { name: 'new' }).click();
  await page3.locator('#select-kategoriObat').click();
  await page3.getByRole('option', { name: 'Obat Keras' }).click();
  await page3.getByRole('textbox', { name: 'Jenis' }).click();
  await page3.getByRole('textbox', { name: 'Jenis' }).fill('Anti');
  await page3.getByRole('menuitem', { name: 'Antipirai' }).click();
  await page3.getByRole('textbox', { name: 'Satuan *' }).fill('Sace');
  await page3.getByRole('textbox', { name: 'Satuan *' }).press('ControlOrMeta+a');
  await page3.getByRole('textbox', { name: 'Satuan *' }).fill('');
  await page3.getByRole('textbox', { name: 'Satuan *' }).press('ArrowDown');
  await page3.getByRole('textbox', { name: 'Satuan *' }).press('Enter');
  await page3.locator('input[name="dosage"]').fill('20 mg');
  await page3.locator('input[name="stockTotalObat"]').press('Shift+ArrowLeft');
  await page3.locator('input[name="stockTotalObat"]').fill('0300');
  await page3.locator('input[name="batchNo"]').fill('BCH-01');
  await page3.locator('input[name="buyFee"]').fill('Rp2000,00');
  await page3.locator('input[name="sellOtcFee"]').fill('Rp5000');
  await page3.locator('input[name="medName"]').fill('WL-OB-');
  await page3.locator('input[name="medName"]').press('ControlOrMeta+b');
  await page3.locator('input[name="medName"]').fill('WL-OB-Pravastatin');
  await page3.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('WLM');
  await page3.getByRole('textbox', { name: 'Jenis' }).fill('Anti');
  await page3.locator('div').filter({ hasText: /^Harga OTC \(Rp\)$/ }).nth(2).click();
  await page3.getByRole('textbox', { name: 'Satuan *' }).click();
  await page3.getByRole('textbox', { name: 'Satuan *' }).fill('Sac');
  await page3.getByText('Sachet', { exact: true }).click();
  await page3.locator('#downshift-35-item-0 div').filter({ hasText: /^Sachet$/ }).click();
  await page3.locator('input[name="dosage"]').click();
  await page3.locator('input[name="dosage"]').fill('10 mg');
  await page3.locator('input[name="stockTotalObat"]').click();
  await page3.locator('input[name="stockTotalObat"]').fill('0400');
  await page3.locator('input[name="expiredDate"]').click();
  await page3.getByRole('heading', { name: 'Rab, Jun' }).click();
  await page3.getByRole('heading', { name: '2026' }).click();
  await page3.getByRole('button', { name: '2030' }).click();
  await page3.getByRole('button', { name: 'OK' }).click();
  await page3.locator('input[name="batchNo"]').click();
  await page3.locator('input[name="batchNo"]').fill('BCH-02');
  await page3.locator('input[name="buyFee"]').click();
  await page3.locator('input[name="buyFee"]').fill('Rp4000,00');
  await page3.locator('input[name="sellOtcFee"]').click();
  await page3.locator('input[name="sellOtcFee"]').fill('Rp6000');
  await page3.getByRole('button', { name: 'Simpan' }).click();
  await page3.locator('[data-test="sidebar-item-pks"]').click();
  await page3.locator('[data-test="sidebar-item-settings"]').click();
  await page3.locator('div').filter({ hasText: 'General SettingsManajemen' }).nth(5).click();
  await page3.getByRole('button', { name: 'Tambah Prosedur' }).click();
  await page3.locator('div').filter({ hasText: /^Catatan$/ }).first().click();
  await page3.locator('[data-test="input-catatan-0"]').fill('WL-P');
  await page3.locator('[data-test="input-catatan-0"]').press('ControlOrMeta+a');
  await page3.locator('[data-test="input-catatan-0"]').fill('');
  await page3.locator('[data-test="input-namaProsedur-0"]').click();
  await page3.locator('[data-test="input-namaProsedur-0"]').fill('WL-P-Mastectomy');
  await page3.locator('[data-test="input-hargaProsedur-0"]').fill('Rp30.0000');
  await page3.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').fill('WL-');
  await page3.locator('[data-test="parent-autocomplete-namaPraktek-0"]').click();
  await page3.locator('[data-test="parent-autocomplete-namaPraktek-0"]').click();
  await page3.locator('[data-test="parent-autocomplete-namaPraktek-0"]').click();
  await page3.locator('[data-test="parent-autocomplete-namaPraktek-0"] [data-test="autocomplete-input"]').fill('WL');
  await page3.getByText('WL-Andres').click();
  await page3.locator('[data-test="input-namaProsedur-1"]').click();
  await page3.locator('[data-test="input-namaProsedur-1"]').fill('WL-P Plasmapheresis');
  await page3.locator('[data-test="input-namaProsedur-1"]').press('ControlOrMeta+z');
  await page3.locator('[data-test="input-namaProsedur-1"]').fill('WL-P');
  await page3.locator('[data-test="input-namaProsedur-1"]').press('ControlOrMeta+ArrowLeft');
  await page3.locator('[data-test="input-namaProsedur-1"]').press('ArrowRight');
  await page3.locator('[data-test="input-namaProsedur-1"]').press('ControlOrMeta+ArrowRight');
  await page3.locator('[data-test="input-namaProsedur-1"]').fill('WL-P-Plasmapheresis');
  await page3.locator('[data-test="input-hargaProsedur-1"]').click();
  await page3.locator('[data-test="input-hargaProsedur-1"]').fill('Rp40.0000');
  await page3.locator('[data-test="parent-autocomplete-namaPraktek-1"]').getByRole('textbox', { name: 'Nama Praktek' }).click();
  await page3.locator('[data-test="parent-autocomplete-namaPraktek-1"]').getByRole('textbox', { name: 'Nama Praktek' }).fill('WL-');
  await page3.locator('[data-test="parent-autocomplete-namaPraktek-1"]').getByText('WL-Issac').click();
  await page3.locator('[data-test="parent-autocomplete-namaPraktek-1"]').getByRole('textbox', { name: 'Nama Praktek' }).fill('WL-');
  await page3.locator('[data-test="parent-autocomplete-namaPraktek-1"]').getByText('WL-Andres').click();
  await page3.getByRole('button', { name: 'Simpan' }).click();
  await page3.locator('.jss55.jss56.jss63.jss73.jss106 > .jss55.jss56').click();
  await page3.locator('[data-test="sidebar-item-emr"]').click();
  await page3.locator('section:nth-child(2) > .jss287.jss291 > .jss287 > .jss340.jss5204 > .jss340.jss452.jss5209 > span > .jss340').click();
  await page3.locator('[data-test="emrAddBtn"]').click();
  await page3.getByRole('textbox', { name: 'Cari fitur' }).fill('pro');
  await page3.getByText('Tambah Prosedur').click();
  await page3.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').fill('WL-');
  await page3.getByText('WL-P-Plasmapheresis').click();
  await page3.getByText('WL-P-Plasmapheresis').click();
  await page3.getByText('WL-P-Plasmapheresis').click();
  await page3.getByText('Rp400.000').click();
  await page3.locator('[data-test="autocomplete-input"]').click();
  await page3.locator('[data-test="input-notes-0-procedure"]').click();
  await page3.locator('[data-test="input-notes-0-procedure"]').fill('add random cek Kasir');
  await page3.getByRole('button', { name: 'AI' }).click();
  await page3.getByRole('button', { name: 'AI' }).click();
  await page3.locator('#coachmark-popper > .jss5576').click();
  await page3.locator('[data-test="button-submit-procedure"]').click();
  await page3.locator('[data-test="button-confirm-dialog-procedure"]').click();
  await page3.locator('.jss4975.jss4978.jss5586').click();
  await page3.locator('.jss4975.jss4978.jss5586').click();
  await page3.getByRole('button').click();
  await page3.getByRole('textbox', { name: 'Cari fitur' }).click();
  await page3.getByRole('textbox', { name: 'Cari fitur' }).fill('rese');
  await page3.getByRole('menuitem', { name: 'Tambah Resep' }).click();
  await page3.locator('[data-test="container-medicine-autocomplete-0-prescription"] [data-test="autocomplete-input"]').fill('Wl');
  await page3.getByRole('button', { name: 'WL-OB-Domperidone (20 mg) WLM' }).click();
  await page3.locator('[data-test="input-quantity-0-prescription"]').click();
  await page3.locator('[data-test="input-quantity-0-prescription"]').fill('02');
  await page3.getByText('Signatura (Keterangan)Ketik').click();
  await page3.locator('[data-test="input-cigna-0-prescription"]').fill('-');
  await page3.locator('[data-test="button-submit-prescription"]').click();
  await page3.getByRole('button', { name: 'Iya' }).click();
  await page3.locator('.jss5576').click();
  await page3.getByRole('button', { name: 'Engaged', exact: true }).click();
  await page3.getByRole('button', { name: 'Engaged', exact: true }).click();
  await page3.goto('https://dev-essensial.assist.id/cashier');
  await page3.locator('[data-test="autocomplete-input"]').fill('');
  await page3.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('wl-');
  await page3.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page3.locator('[data-test="kasir-item-0"] [data-test="quantity-input"]').fill('1');
  await page3.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page3.locator('[data-test="kasir-item-1"] [data-test="quantity-input"]').fill('01');
  await page3.locator('[data-test="input-bayar-langsung"]').press('Shift+ArrowLeft');
  await page3.locator('[data-test="input-bayar-langsung"]').fill('Rp31.0000');
  await page3.locator('[data-test="input-dibayar-oleh-langsung"]').fill('random');
  await page3.goto('https://dev-essensial.assist.id/profile');
  await page3.locator('[data-test="input-nomor-telepon"]').fill('076112322');
  await page3.locator('[data-test="input-nitku"]').fill('NITKU sample');
  await page3.locator('[data-test="input-deskripsi"]').fill('Deskr');
  await page3.locator('[data-test="input-visi"]').fill('Visi 01\nVisi 02');
  await page3.locator('[data-test="input-misi"]').fill('Misi 01\nMisi 02');
  await page3.getByRole('textbox', { name: 'Pribadi, Contoh: Tunai' }).fill(' ');
  await page3.getByRole('textbox', { name: 'Perusahaan' }).fill('Pt');
  await page3.locator('[data-test="autocomplete-metode-pembayaran-asuransi"] [data-test="autocomplete-input"]').fill('As');
  await page3.getByRole('textbox', { name: 'Perusahaan' }).fill('Pt');
  await page3.locator('[data-test="autocomplete-metode-pembayaran-asuransi"] [data-test="autocomplete-input"]').fill('');
  await page3.locator('[data-test="autocomplete-metode-pembayaran-debit"] [data-test="autocomplete-input"]').fill('De');
  await page3.locator('[data-test="autocomplete-metode-pembayaran-kredit"] [data-test="autocomplete-input"]').fill('Kre');
  await page3.locator('[data-test="autocomplete-metode-pembayaran-debit"] [data-test="autocomplete-input"]').fill('De');
  await page3.locator('[data-test="autocomplete-metode-pembayaran-kredit"] [data-test="autocomplete-input"]').fill('Kre');
  await page3.goto('https://dev-essensial.assist.id/office');
  await page3.locator('[data-test="input-nama-pasien"]').fill('WL-Moran');
  await page3.locator('[data-test="input-tempat-lahir"]').fill('Barchfeld');
  await page3.locator('[data-test="input-nama-ibu"]').fill('Barchfeld');
  await page3.locator('[data-test="input-nama-ibu"]').press('ControlOrMeta+Shift+ArrowRight');
  await page3.locator('[data-test="input-nama-ibu"]').fill('Moran Ibu');
  await page3.locator('input[name="address"]').fill('Jl Barchfeld no 233');
  await page3.locator('input[name="postcode"]').fill('23424');
  await page3.goto('https://dev-essensial.assist.id/settings');
  await page3.locator('[data-test="input-nama-lengkap"]').fill('Gesi [Acc24');
  await page3.locator('[data-test="input-nomor-hp"]').fill('0812-3131-241234');
  await page3.locator('[data-test="input-jabatan"]').fill('QA');
  await page3.locator('[data-test="input-email"]').fill('anisasecondacc24@gmail.com');
  await page3.goto('https://dev-essensial.assist.id/accreditation');
  await page3.getByRole('button', { name: 'Choose File' }).setInputFiles('Data Katalog Harga Prosedur.xlsx');
  await page3.goto('https://dev-essensial.assist.id/accreditation');
  await page3.getByRole('button', { name: 'Choose File' }).setInputFiles('A Cat 04.png');
});