import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#username').press('Tab');
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.getByRole('button').first().click();
  await page.locator('div').filter({ hasText: 'Ganti Password Akun Anda Dulu' }).nth(3).click();
  await page.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.locator('.jss1158').click();
  await page.locator('[data-test="sidebar-item-office"]').click({
    button: 'right'
  });
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '000101 - Klinik Assist.id [' }).click();
  await page.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.locator('[data-test="sidebar-item-office"]').click({
    button: 'right'
  });
  await page.locator('[data-test="sidebar-item-rawat-jalan"]').click();
  await page.locator('.jss2753.jss2965').first().click();
  await page.getByRole('menuitem', { name: 'dr. Alexander' }).press('ControlOrMeta+f');
  await page.getByRole('menuitem', { name: 'Arnold Maxto' }).click();
  await page.locator('.jss3024').click();
  await page2.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click();
  await page2.getByRole('button', { name: 'Laporan', description: 'Semua laporan yang terkait dengan operational dan keuangan, dan laporan tersebut bisa diexport ke Excel / PDF dan bisa diprint', exact: true }).click();
  await page2.getByRole('button', { name: 'Pasien' }).click();
  await page2.getByRole('button', { name: 'Data Pasien' }).click();
  await page2.getByRole('button', { name: 'Next Page' }).click();
  await page2.getByRole('button', { name: 'Next Page' }).dblclick();
  await page2.getByRole('button', { name: 'Next Page' }).click();
  await page2.getByRole('button', { name: 'Next Page' }).click();
  await page2.getByRole('button', { name: 'Next Page' }).dblclick();
  await page2.getByRole('button', { name: 'Next Page' }).click();
  await page2.getByRole('button', { name: 'Next Page' }).dblclick();
  await page2.getByRole('button', { name: 'Next Page' }).click();
  await page2.getByRole('button', { name: 'Next Page' }).click();
  await page2.getByRole('button', { name: 'Next Page' }).dblclick();
  await page2.locator('[data-test="search-input"]').click();
  await page2.locator('[data-test="search-input"]').fill('pro');
  await page2.locator('[data-test="search-input"]').press('Enter');
  await page2.locator('[data-test="search-input"]').fill('pro-');
  await page2.locator('[data-test="search-input"]').press('Enter');
  await page2.locator('.jss56.jss91 > button').click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Pro-');
  await page.locator('[data-test="input-complaint"]').fill('CEk Diag Partner');
  await page.locator('[data-test="input-complaint"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('ArrowRight');
  await page.locator('[data-test="input-complaint"]').press('ArrowRight');
  await page.locator('[data-test="input-complaint"]').press('Shift+ArrowRight');
  await page.locator('[data-test="input-complaint"]').fill('Cek Diag Partner');
  await page2.locator('[data-test="sidebar-item-layananTambahn"]').click();
  await page2.locator('div').filter({ hasText: /^Diagnostic Partner$/ }).first().click();
  await page2.goto('https://dev-essensial.assist.id/layanan-tambahan');
  await page.goto('https://dev-essensial.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('rujukan');
  await page.getByRole('textbox', { name: 'Cari Cabang Prodia' }).fill('ciden');
  await page.getByRole('textbox', { name: 'Diagnosa' }).fill('Diagnosa ');
  await page.getByRole('textbox', { name: 'Diagnosa' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Diagnosa' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Diagnosa' }).fill('Diag Rujukan Pasien');
  await page.getByRole('textbox', { name: 'Catatan' }).fill('Sample Rujukan Tipe Pasien');
  await page.getByRole('textbox', { name: 'Cari Kota/Kabupaten' }).fill('');
  await page.goto('https://dev-essensial.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari Pasien / No MR / No Ktp' }).fill('Heaven');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('rujuka');
  await page.getByRole('textbox', { name: 'Cari Cabang Prodia' }).fill('cideng');
  await page.getByRole('textbox', { name: 'Cari Pasien / No MR / No Ktp' }).fill('Heaven');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('rujuk');
  await page.getByRole('textbox', { name: 'Cari Cabang Prodia' }).fill('ciden');
  await page.getByRole('textbox', { name: 'Diagnosa' }).fill('Diag sample');
  await page.getByRole('textbox', { name: 'Catatan' }).fill('Tipe 01 Pasien');
  await page.getByRole('textbox', { name: 'Cari Cabang Prodia' }).fill('ci');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PRO-Kimora');
  await page.locator('[data-test="input-tempat-lahir"]').fill('Sinmartin');
  await page.locator('input[name="address"]').fill('Jl Sinmartin');
  await page.locator('input[name="postcode"]').fill('4533');
  await page.locator('[data-test="input-no-ktp"]').fill('21432423');
  await page.locator('[data-test="input-no-ktp"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-no-ktp"]').fill('2143242');
  await page.locator('[data-test="input-no-ktp"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-no-ktp"]').fill('');
  await page.locator('[data-test="input-no-telepon"]').fill('081371075995');
  await page.locator('[data-test="input-complaint"]').fill('sample pasien baru Diag Partner');
  await page.goto('https://dev-essensial.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('ruju');
  await page.getByRole('textbox', { name: 'Cari Cabang Prodia' }).fill('Cideng');
  await page.goto('https://dev-essensial.assist.id/registration');
  await page2.locator('html').getByRole('document').click();
  await page2.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click();
  await page2.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click({
    button: 'right'
  });
  await page2.goto('https://dev-essensial.assist.id/emr');
  await page2.locator('#kamarmedis-content > div:nth-child(2)').click();
  await page2.locator('#kamarmedis-content > div:nth-child(2)').click();
  await page2.locator('html').getByRole('document').click();
  await page2.getByRole('button').filter({ hasText: /^$/ }).click();
  await page2.getByRole('button').filter({ hasText: /^$/ }).click();
  await page2.getByRole('menuitem', { name: 'PRO-Heaven Adkins' }).click();
  await page2.getByText('TimelineRecordCPPT').click();
  await page2.locator('[data-test="emrAddBtn"]').click();
  await page2.getByRole('textbox', { name: 'Cari fitur' }).fill('rujuk');
  await page2.getByRole('menuitem', { name: 'Tambah Rujuk Rawat Inap' }).click();
  await page2.getByRole('menuitem', { name: 'Tambah Rujuk Rawat Inap' }).click();
  await page2.getByRole('textbox', { name: 'Cari Cabang Prodia' }).fill('ciden');
});