import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.getByRole('img', { name: 'placeholder' }).click();
  await page.locator('div').nth(4).click();
  await page.getByText('Username/EmailPasswordLoginLupa password?V.3.43.0').click();
  await page.locator('div').filter({ hasText: /^Username\/Email$/ }).click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('[data-test="input-password"]').click();
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.goto('https://dev-essensial.assist.id/');
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: 'Baru (Pemilik)' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('Gael []');
  await page.getByRole('textbox').press('ArrowLeft');
  await page.getByRole('textbox').fill('Gael [Clinica Pro]');
  await page.getByRole('textbox').press('Enter');
  await page.getByRole('radio', { name: 'tahun', exact: true }).check();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('10');
  await page.getByRole('spinbutton').press('Enter');
  await page.getByRole('spinbutton').dblclick();
  await page.getByRole('spinbutton').fill('20');
  await page.getByRole('spinbutton').press('Enter');
  await page.getByRole('radio', { name: 'Iya' }).check();
  await page.getByRole('radio', { name: 'Sudah Akreditasi' }).check();
  await page.getByText('Apakah faskes memiliki apotek?').click();
  await page.getByRole('radio', { name: 'Punya apotek (bisa jual untuk' }).check();
  await page.getByRole('radiogroup').filter({ hasText: 'IyaTidak' }).getByLabel('Iya').check();
  await page.getByRole('radiogroup').filter({ hasText: 'IyaTidak' }).getByLabel('Iya').check();
  await page1.locator('body').click();
  await page.getByText('Upload Logo (Optional)').click();
  await page.getByText('Upload Logo (Optional)Click').click();
  await page.locator('body').setInputFiles('icons8-starfish-96.png');
  await page.locator('div').filter({ hasText: 'InformasiNama fasilitas' }).nth(1).click();
  await page.locator('.jss1712').click();
  await page.locator('input[name="kodePos"]').fill('2343');
  await page.locator('input[name="namaJalan"]').fill('Jl Gael no 25');
  await page.locator('input[name="npwpName"]').fill('NPWP Gael');
  await page.locator('input[name="npwp"]').fill('908098098');
  await page.locator('input[name="npwpAddress"]').fill('Alamat NPWP Gael');
  await page.goto('https://dev-essensial.assist.id/');
  await page.locator('div').filter({ hasText: 'Syarat & KetentuanMohon baca' }).nth(1).press('ControlOrMeta+-');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-jabatan"]').fill('QA');
  await page.locator('[data-test="input-email"]').fill('anisasecondacc23@gmail.com');
  await page.locator('[data-test="input-nomor-hp"]').fill('0800-0000-0000  ');
  await page.locator('[data-test="input-nama-lengkap"]').fill('Gesi [Ac24');
  await page.locator('[data-test="input-nama-lengkap"]').press('ArrowLeft');
  await page.locator('[data-test="input-nama-lengkap"]').press('ArrowLeft');
  await page.locator('[data-test="input-nama-lengkap"]').press('ArrowLeft');
  await page.locator('[data-test="input-nama-lengkap"]').press('ArrowRight');
  await page.locator('[data-test="input-nama-lengkap"]').fill('Gesi [Acc24');
  await page.locator('[data-test="input-email"]').fill('anisasecondacc24@gmail.com');
  await page.locator('[data-test="input-jabatan"]').fill('QA');
  await page.locator('[data-test="input-nomor-hp"]').fill('0800-0000-0000  ');
  await page.locator('[data-test="input-nama-hak-akses"]').fill('All Access \'26 Pro');
  await page.locator('[data-test="input-nama"]').fill('GL-Yasmin');
  await page.getByRole('button', { name: 'Upload Photo Profile' }).setInputFiles('A Cat 01.jpg');
  await page.locator('[data-test="input-telepon"]').fill('08000000000');
  await page.locator('[data-test="input-email"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-email"]').fill('anisasecondacc24@gmail.com');
  await page.locator('[data-test="input-noKTP"]').fill('23424242423');
  await page.locator('[data-test="input-registrasiNomor"]').fill('23rwefwfcw34r2');
  await page.locator('[data-test="input-registrasiSIPNomor"]').fill('2wfrewdtf43');
  await page.locator('[data-test="autocomplete-input"]').fill('Sp');
  await page.locator('.jss2499.jss2486.jss2490.jss2500.jss2487.jss2504.jss5523 > .jss2509').first().fill('08:00_');
  await page.locator('.jss2499.jss2486.jss2490.jss2500.jss2487.jss2504.jss5523 > .jss2509').first().press('ControlOrMeta+a');
  await page.locator('.jss2499.jss2486.jss2490.jss2501 > .jss2509').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(3) > .jss5267 > .jss2499 > .jss2509').fill('08:00');
  await page.locator('div:nth-child(4) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(3) > .jss5267 > .jss2499 > .jss2509').fill('08:00');
  await page.locator('div:nth-child(5) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(3) > .jss5267 > .jss2499 > .jss2509').fill('08:00');
  await page.locator('div:nth-child(6) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(3) > .jss5267 > .jss2499 > .jss2509').fill('08:00');
  await page.locator('div:nth-child(7) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(3) > .jss5267 > .jss2499 > .jss2509').fill('08:00');
  await page.locator('div:nth-child(8) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(3) > .jss5267 > .jss2499 > .jss2509').fill('08:00');
  await page.locator('.jss2055 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').first().fill('22:00_');
  await page.locator('.jss2055 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').first().press('ControlOrMeta+a');
  await page.locator('.jss2499.jss2486.jss2490.jss2501 > .jss2509').press('ControlOrMeta+c');
  await page.locator('div:nth-child(3) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').fill('22:00');
  await page.locator('div:nth-child(4) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').fill('22:00');
  await page.locator('div:nth-child(5) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').fill('22:00');
  await page.locator('div:nth-child(6) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').fill('22:00');
  await page.locator('div:nth-child(7) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').fill('22:00');
  await page.locator('div:nth-child(8) > .jss2055.jss2056.jss2063.jss2095 > div:nth-child(5) > .jss5267 > .jss2499 > .jss2509').fill('22:00');
  await page.getByRole('textbox', { name: 'Nama Praktek' }).fill('GL');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Jayda');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Gl-Jayda');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('Alt+ArrowLeft');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('GL-Jayda');
  await page.locator('[data-test="input-nama-ibu"]').fill('Jayda Ibu');
  await page.locator('[data-test="input-no-telepon"]').fill('9089123');
  await page.locator('[data-test="input-no-telepon"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-no-telepon"]').fill('0808080808080');
  await page.locator('input[name="address"]').fill('Chiguayante');
  await page.locator('input[name="address"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('input[name="address"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('input[name="address"]').fill('Jl Chiguayante');
  await page.locator('input[name="address"]').press('ControlOrMeta+ArrowRight');
  await page.locator('input[name="address"]').fill('Jl Chiguayante no 8234');
  await page.locator('input[name="postcode"]').fill('34535');
  await page.locator('button').filter({ hasText: 'Pilih Foto' }).setInputFiles('A Cat 07.png');
  await page.locator('[data-test="input-complaint"]').fill('Sample random');
  await page.goto('https://dev-essensial.assist.id/registration');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('GL-Horne');
  await page.locator('[data-test="input-tempat-lahir"]').fill('Mora');
  await page.locator('input[name="address"]').fill('JL Mora no 345');
  await page3.locator('[data-test="sidebar-item-settings"]').click();
  await page3.getByText('Bridging Satu SehatBridging').click();
  await page3.getByRole('button', { name: 'Printing Template' }).click();
  await page3.getByRole('button', { name: 'Kamar Inap' }).click();
  await page3.locator('[data-test="btn-addRoom"]').click();
  await page3.locator('html').getByRole('document').click();
  await page3.locator('[data-test="input-nameRoom"]').click();
  await page3.locator('[data-test="input-nameRoom"]').fill('GL-R-Fuldatal');
  await page3.locator('#select-type').click();
  await page3.locator('#select-type').click();
  await page3.locator('.jss1679.jss1680').click();
  await page3.locator('[data-test="input-jumlahKamar"]').fill('90');
  await page3.locator('[data-test="input-jumlahKamar"]').press('Tab');
  await page3.locator('[data-test="input-jumlahBed"]').fill('70');
  await page3.locator('[data-test="input-price"]').fill('Rp20.0000');
  await page3.locator('[data-test="input-kodeKamar"]').fill('GL-F');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Horn');
  await page.goto('https://dev-essensial.assist.id/registration');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Horne');
  await page.locator('[data-test="input-complaint"]').fill('Rananp sample');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('GL-Faulkner');
  await page.locator('[data-test="input-tempat-lahir"]').fill('Unzenberg');
  await page.locator('input[name="address"]').fill('JL Unzenberg no 23423');
  await page.locator('input[name="postcode"]').fill('23423');
  await page.locator('[data-test="input-complaint"]').fill('sample ranap persalinan');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-hargaProsedur-0"]').fill('Rp20.0000');
  await page.locator('[data-test="input-namaProsedur-1"]').fill('GL-Vascular surgery');
  await page.locator('[data-test="input-hargaProsedur-1"]').fill('Rp50.0000');
  await page.goto('https://dev-essensial.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('pro');
  await page.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').fill('GL-');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-packageName-0"]').fill('Paket ');
  await page.locator('[data-test="autocomplete-input"]').fill('GL-');
  await page.locator('[data-test="input-packageName-0"]').fill('Paket Hyste + Vascul');
  await page.locator('[data-test="input-packageName-0"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-packageName-0"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-packageName-0"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-packageName-0"]').fill('Paket [Hyste + Vascul');
  await page.locator('[data-test="input-packageName-0"]').press('ControlOrMeta+ArrowRight');
  await page.locator('[data-test="input-packageName-0"]').fill('Paket [Hyste + Vascul]');
  await page.locator('[data-test="input-procedureQuantity-0-0"]').press('Shift+ArrowRight');
  await page.locator('[data-test="input-procedureQuantity-0-0"]').fill('2');
  await page.locator('[data-test="input-procedureQuantity-0-1"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-procedureQuantity-0-1"]').fill('1');
  await page.locator('[data-test="input-packagePrice-0"]').fill('Rp075.0000');
  await page.locator('[data-test="input-packageDuration-0"]').fill('03.00');
  await page.locator('[data-test="input-defaultCommissionType"]').selectOption('percent');
  await page.locator('[data-test="input-defaultCommissionValue"]').fill('010%');
  await page.locator('[data-test="input-defaultCommissionType"]').selectOption('percent');
  await page.locator('[data-test="input-defaultCommissionValue"]').fill('010%');
  await page.locator('[data-test="input-defaultCommissionType"]').selectOption('price');
  await page.locator('[data-test="input-defaultCommissionValue"]').fill('Rp000.02');
  await page.locator('[data-test="input-defaultCommissionValue"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-defaultCommissionValue"]').fill('Rp20.00');
  await page.locator('[data-test="input-namaKatalogMcu-0"]').fill('GL-M-Tonsillectomy');
  await page.locator('[data-test="input-namaMcu-0"]').fill('Tonsil 01');
  await page.locator('[data-test="input-max-0"]').fill('30');
  await page.locator('[data-test="input-namaMcu-1"]').fill('Tonsil A');
  await page.locator('[data-test="input-keterangan-1"]').fill('Ton 02');
  await page.locator('[data-test="autocomplete-input"]').fill('GL');
  await page.locator('[data-test="input-totalHarga-0"]').press('Shift+ArrowRight');
  await page.locator('[data-test="input-harga-0"]').fill('Rp3.0000');
  await page.locator('[data-test="input-harga-1"]').fill('Rp2.0000');
  await page.locator('[data-test="input-namaKatalogMcu-1"]').fill('GL-MCU-Hysterectomy');
  await page.locator('[data-test="input-namaMcu-0"]').nth(1).fill('Hyste 01');
  await page.locator('[data-test="input-keterangan-0"]').fill('Hyst 01');
  await page.locator('[data-test="input-keterangan-0"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-keterangan-0"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-keterangan-0"]').fill('Hyst 02');
  await page.locator('[data-test="autocomplete-input"]').fill('Gl-');
  await page.goto('https://dev-essensial.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('lab');
  await page.getByRole('textbox', { name: 'Cari fitur' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('order');
  await page.locator('[data-test="input-notes-0-order"]').fill('Random sample');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('hasil');
  await page.locator('[data-test="input-mcu-value-0-0-lab"]').fill('20');
  await page.locator('[data-test="input-notes-lab"]').fill('Random Cek');
  await page3.goto('https://dev-essensial.assist.id/settings');
  await page3.locator('[data-test="input-namaKatalogMcu-0"]').fill('GL-MCU-Intramuscular');
  await page3.locator('[data-test="input-namaMcu-0"]').fill('Intra');
  await page3.locator('[data-test="input-min-0"]').fill('3');
  await page3.locator('[data-test="input-satuan-0"]').fill('Scale');
  await page3.locator('[data-test="autocomplete-input"]').fill('GL');
  await page3.locator('[data-test="input-harga-0"]').fill('Rp30.0000');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('order');
  await page.locator('[data-test="input-notes-0-order"]').fill('Random');
  await page3.goto('https://dev-essensial.assist.id/registration');
  await page3.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('GL Marian');
  await page3.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ControlOrMeta+z');
  await page3.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('GL Mariana');
  await page3.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ControlOrMeta+z');
  await page3.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('GL-Mariana');
  await page3.locator('input[name="address"]').fill('Jl Fuldatal no 234');
  await page3.getByRole('textbox', { name: 'Cari Paket Prosedur' }).fill('Gl- ');
  await page3.getByRole('textbox', { name: 'Cari Paket Prosedur' }).press('ControlOrMeta+a');
  await page3.getByRole('textbox', { name: 'Cari Paket Prosedur' }).fill('Pake');
  await page3.locator('input[name="quantity"]').first().fill('01');
  await page3.getByRole('textbox', { name: 'Cari Prosedur' }).fill('GL-');
  await page3.locator('[data-test="input-complaint"]').fill('Added MCU, lihat sub MEn Lab');
  await page3.goto('https://dev-essensial.assist.id/emr');
  await page3.getByRole('textbox', { name: 'Cari fitur' }).fill('pro');
  await page3.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').fill('GL');
  await page3.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').press('ArrowDown');
  await page3.getByRole('textbox', { name: 'Cari fitur' }).fill('pake');
  await page3.locator('[data-test="autocomplete-input"]').fill('Pake');
  await page3.locator('[data-test="input-quantity-used-0-1-packet-procedure"]').press('Shift+ArrowLeft');
  await page3.locator('[data-test="input-quantity-used-0-1-packet-procedure"]').fill('1');
  await page.goto('https://dev-essensial.assist.id/apotek');
  await page.locator('input[name="medName"]').fill('GL-M-Mebeverine');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('GLM');
  await page.getByRole('textbox', { name: 'Satuan *' }).fill('Pil');
  await page.locator('input[name="dosage"]').fill('10 mg');
  await page.getByRole('textbox', { name: 'Jenis' }).fill('Ant');
  await page.locator('input[name="stockTotalObat"]').press('Shift+ArrowLeft');
  await page.locator('input[name="stockTotalObat"]').fill('300');
  await page.locator('input[name="batchNo"]').fill('MB2343');
  await page.locator('input[name="buyFee"]').fill('Rp2000,00');
  await page.locator('input[name="buyFee"]').press('Tab');
  await page.locator('tr:nth-child(4) > .jss223673 > div > div > div:nth-child(3) > .jss223220 > .jss221149 > .jss221159').fill('Rp3000');
  await page.locator('input[name="sellOtcFee"]').fill('Rp5000');
  await page.locator('[data-test="input-nama-barang"]').fill('GL-B-Kassa');
  await page.getByRole('textbox', { name: 'Nama Brand Farmasi' }).fill('GLM');
  await page.getByRole('textbox', { name: 'Jenis' }).fill('Anti');
  await page.getByRole('textbox', { name: 'Satuan *' }).fill('Lembar');
  await page.locator('[data-test="input-stok-barang"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-stok-barang"]').fill('0350');
  await page.locator('[data-test="input-dosage"]').fill('S');
  await page.locator('[data-test="input-batch-no"]').fill('B=MB-234');
  await page.locator('[data-test="input-batch-no"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-batch-no"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-batch-no"]').press('ArrowLeft');
  await page.locator('[data-test="input-batch-no"]').press('ArrowLeft');
  await page.locator('[data-test="input-batch-no"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-batch-no"]').fill('MB-234');
  await page.locator('[data-test="input-harga-beli"]').fill('Rp30.00,00');
  await page.locator('[data-test="input-harga-otc"]').fill('Rp5000');
  await page.goto('https://dev-essensial.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('bahan');
  await page.locator('[data-test="autocomplete-input"]').fill('GL-');
  await page.locator('[data-test="input-quantity-0-disposable"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-quantity-0-disposable"]').fill('2');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('obat');
  await page.getByRole('textbox', { name: 'Cari fitur' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('rese');
  await page.locator('[data-test="container-medicine-autocomplete-0-prescription"] [data-test="autocomplete-input"]').fill('GL-');
  await page.locator('[data-test="input-quantity-0-prescription"]').fill('01');
  await page.locator('[data-test="input-cigna-0-prescription"]').fill('random');
  await page.getByRole('textbox', { name: 'Nama Racikan' }).fill('');
  await page.locator('[data-test="input-concoction-quantity-1-prescription"]').fill('1');
  await page.locator('[data-test="container-concoction-unit-autocomplete-1-prescription"] [data-test="autocomplete-input"]').fill('Pil');
  await page.locator('[data-test="input-concoction-cigna-1-prescription"]').fill('random');
  await page.getByRole('textbox', { name: 'Nama Obat' }).fill('Gl-');
  await page.locator('input[name="prescriptions.1.materialPrescript.0.numerator"]').fill('2');
  await page.locator('input[name="prescriptions.1.materialPrescript.0.denominator"]').fill('1');
  await page.locator('textarea[name="prescriptions.1.materialPrescript.0.note"]').fill('random');
  await page.locator('[data-test="autocomplete-input"]').fill('Racik');
});
