import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('div').nth(1).click();
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('#username').press('Tab');
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.goto('https://dev-essensial.assist.id/');
  await page.getByText('Klinik Pcare & Antrol Assist.id PIC1Solusi Absensi untuk Klinik dan Fasilitas').click();
  await page.getByRole('button').nth(5).click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '001680 - Wall [Clinica Lite' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.locator('[data-test="sidebar-item-layananTambahn"]').click();
  await page.locator('.jss2660').click();
  await page.locator('div').filter({ hasText: /^Telekonsultasi$/ }).first().click();
  await page.getByText('Riwayat Lengkap di Genggaman:').click();
  await page.getByText('TelekonsultasiKonsultasi').click();
  await page.getByText('TelekonsultasiKonsultasi').click();
  await page.getByText('AssistMe(Online Appointment)TelekonsultasiDiagnostic PartnerGetResepPOS(Point').click();
  await page.getByText('AssistMe(Online Appointment)TelekonsultasiDiagnostic PartnerGetResepPOS(Point').click();
  await page.getByText('(Online Appointment)').click();
  await page.locator('div').filter({ hasText: /^AssistMe\(Online Appointment\)$/ }).first().click();
  await page.locator('div').filter({ hasText: 'AssistMe(Online Appointment)' }).nth(5).click();
  await page.locator('div').filter({ hasText: /^Telekonsultasi$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Diagnostic Partner$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Diagnostic Partner$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Diagnostic Partner$/ }).first().click();
  await page.getByText('POS(Point of Sale)Baru').click();
  await page.locator('div').filter({ hasText: /^Diagnostic Partner$/ }).first().click();
  await page.getByText('Total HargaGratis').click();
  await page.locator('.jss1940.jss1975').click();
  await page.getByText('Bagi Pasien :Diagnosis Lebih').click();
  const page1Promise = page.waitForEvent('popup');
  await page.locator('div').filter({ hasText: /^Syarat dan Ketentuan$/ }).nth(1).click();
  const page1 = await page1Promise;
  await page.locator('.jss3971').click();
  await page.locator('div').filter({ hasText: 'Faktur Pajak tidak dapat' }).nth(4).click();
  await page.locator('div').filter({ hasText: /^GetResep$/ }).first().click();
  await page.locator('.jss1939.jss1940.jss1947.jss1957.jss1990 > .jss1939').click();
  await page.locator('body').press('Escape');
  await page.getByText('Mengurangi Kesalahan Penulisan: Resep digital lebih mudah dibaca dibandingkan').click();
  const page2Promise = page.waitForEvent('popup');
  await page.locator('div').filter({ hasText: /^Syarat dan Ketentuan$/ }).nth(1).click();
  const page2 = await page2Promise;
  await page2.goto('https://drive.google.com/file/d/1mOQE3ywCxhhiBuIyBxIJqxKh7Xd4xFnF/view');
  const page3Promise = page.waitForEvent('popup');
  await page.locator('div').filter({ hasText: /^Syarat dan Ketentuan$/ }).nth(1).click();
  const page3 = await page3Promise;
  await page.getByText('Bagi Fasilitas Kesehatan :').click();
  await page.getByText('5 klinik telah menggunakan').click();
  await page.locator('div').filter({ hasText: /^POS\(Point of Sale\)$/ }).first().click();
  await page.locator('div').filter({ hasText: /^POS\(Point of Sale\)$/ }).first().click();
  const page4Promise = page.waitForEvent('popup');
  await page.locator('div:nth-child(2) > svg').click();
  const page4 = await page4Promise;
  await page.locator('.jss4145 > .jss2227').click();
  await page.getByRole('button', { name: 'Bagaimana cara menggunakan' }).click();
  await page.locator('div:nth-child(2) > .jss2171 > .jss2224.jss4130 > .jss2224.jss2367.jss4135 > span > .jss2224').click();
  await page.locator('.jss2224.jss4130.jss4241 > .jss2224.jss2367.jss4135 > span > .jss2224').first().click();
  await page.getByRole('heading', { name: 'Frequently Asked Questions' }).getByRole('button').click();
  await page4.getByText('Hi, saya Gesi [Tidak Connect').dblclick();
  await page4.getByText('Hi, saya Gesi [Tidak Connect').click();
  await page4.getByText('Hi, saya Gesi [Tidak Connect').click();
  await page4.locator('._9vd6._9t33._9bir._9bj3._9bhj > div').first().click();
  await page4.getByText('Hi, saya Gesi [Tidak Connect').click();
  await page.locator('div').filter({ hasText: /^Add Ons$/ }).first().click();
  await page.locator('section').filter({ hasText: 'Fitur untuk menerima pembayaran di muka yang dapat digunakan oleh pasien untuk' }).click();
  await page.locator('[data-test="sidebar-item-settings"]').click();
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.locator('[data-test="button-add-staff"]').click();
  await page.getByText('Nama Lengkap *Tanggal Lahir *Jabatan *Tipe Akses *Pilih Tipe AksesAlamat Email').click();
  await page.locator('div').filter({ hasText: 'Nama Lengkap *' }).nth(5).click();
  await page.locator('div').filter({ hasText: 'Nama Lengkap *' }).nth(5).click();
  await page.locator('[data-test="input-nama-lengkap"]').click();
  await page.locator('[data-test="input-nama-lengkap"]').fill('Gesi [Griffith]');
  await page.locator('[data-test="input-email"]').click();
  await page.locator('[data-test="input-email"]').fill('griffithwhales@gmail.com');
  await page.locator('[data-test="input-jabatan"]').click();
  await page.locator('[data-test="input-jabatan"]').fill('QA');
  await page.getByRole('button').nth(1).click();
  await page.getByRole('heading', { name: '2026' }).click();
  await page.getByRole('button', { name: '2019' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Pilih Tipe Akses' }).click();
  await page.locator('div').filter({ hasText: /^Owner$/ }).nth(3).click();
  await page.getByText('Nama Lengkap *Tanggal Lahir *Jabatan *Tipe Akses *OwnerAlamat Email *Nomor Hp *').click();
  await page.locator('[data-test="input-nomor-hp"]').click();
  await page.locator('[data-test="input-nomor-hp"]').fill('0892-34324-     ');
  await page.locator('[data-test="button-simpan-staff"]').click();
  await page.locator('[data-test="input-nomor-hp"]').click();
  await page.locator('[data-test="input-nomor-hp"]').fill('0892-3432-4234  ');
  await page.locator('[data-test="button-simpan-staff"]').click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(6) > .jss1939 > div > .jss2224').first().click();
  await page.getByRole('textbox', { name: 'Nomor Hp' }).click();
  await page.getByRole('textbox', { name: 'Nomor Hp' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Nomor Hp' }).fill('0800-0000-0000  ');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('div').filter({ hasText: /^Jumlah baris per halaman:51-3 dari 3 data$/ }).first().click();
  await page.getByRole('button', { name: 'Hak Akses' }).click();
  await page.getByText('Melihat login & Complete profile.').nth(2).click();
  await page.locator('div').filter({ hasText: 'General SettingsManajemen' }).nth(5).click();
  await page.getByRole('button', { name: 'Hak Akses' }).click();
  await page.getByText('Hak Akses+ Tambah Tipe Akses').click();
  await page.getByRole('button', { name: '+ Tambah Tipe Akses' }).click();
  await page.locator('[data-test="input-nama-hak-akses"]').fill('All Access \'26');
  await page.locator('[data-test="checkbox-dashboard"]').check();
  await page.locator('[data-test="checkbox-outpatient"]').check();
  await page.locator('[data-test="checkbox-emr"]').check();
  await page.locator('[data-test="checkbox-pharmacy"]').check();
  await page.locator('[data-test="checkbox-cashier"]').check();
  await page.locator('[data-test="checkbox-setting"]').check();
  await page.locator('[data-test="checkbox-profile"]').check();
  await page.locator('[data-test="checkbox-report"]').check();
  await page.locator('[data-test="checkbox-registration"]').check();
  await page.locator('[data-test="checkbox-teleconsult"]').check();
  await page.locator('[data-test="checkbox-pks"]').check();
  await page.locator('[data-test="checkbox-layananTambahan"]').check();
  await page.locator('[data-test="checkbox-bantuanDanSaran"]').check();
  await page.locator('[data-test="button-simpan-hak-akses"]').click();
  await page.getByRole('button', { name: 'Info Tenaga Medis' }).click();
  await page.getByRole('button', { name: 'Hak Akses' }).click();
  await page.getByRole('button', { name: '+ Tambah Tipe Akses' }).click();
  await page.getByRole('button', { name: 'Nothing' }).click();
  await page.locator('.jss6000.jss6001').click();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('cell', { name: '1. Melihat list appointment' }).first().click();
  await page.getByRole('button', { name: 'Manajemen Staff' }).click();
  await page.locator('.jss5910 > .jss1939 > div > .jss2224').first().click();
  await page.getByRole('button', { name: 'Pilih Tipe Akses' }).click();
  await page.getByRole('option', { name: 'All Access \'' }).click();
  await page.getByText('Hapus akun staffSimpan').click();
  await page.getByRole('textbox', { name: 'Nama Praktek' }).click();
  await page.getByRole('textbox', { name: 'Nama Praktek' }).fill('wl');
  await page.getByRole('menuitem', { name: 'WL-Issac' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('tr:nth-child(2) > td:nth-child(6) > .jss1939 > div > .jss2224').first().click();
  await page.locator('#tanggal-lahir').click();
  await page.getByRole('heading', { name: '2026' }).click();
  await page.getByRole('button', { name: '2007' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Owner' }).click();
  await page.locator('div').filter({ hasText: /^All Access '26$/ }).nth(2).click();
  await page.getByRole('textbox', { name: 'Nama Praktek' }).click();
  await page.getByRole('textbox', { name: 'Nama Praktek' }).fill('wl');
  await page.getByRole('menuitem', { name: 'WL-Andres' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(6) > .jss1939 > div > .jss2224').first().click();
  await page.getByRole('button', { name: 'Owner' }).click();
  await page.getByRole('option', { name: 'All Access \'' }).click();
  await page.locator('.jss6147.jss6150.jss7183').click();
  await page.getByRole('textbox', { name: 'Nama Praktek' }).fill('wl');
  await page.getByRole('menuitem', { name: 'WL-Issac' }).click();
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('.jss5910 > .jss1939 > div > .jss2224').first().click();
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).click();
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).fill('Gesi [Acc24 Isaac]');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('tr:nth-child(2) > td:nth-child(6) > .jss1939 > div > .jss2224').first().click();
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('Alt+ArrowLeft');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('Alt+ArrowLeft');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('Alt+ArrowLeft');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('Alt+ArrowLeft');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('Alt+Shift+ArrowRight');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('Alt+Shift+ArrowRight');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).fill('Gesi [Andres | Assist]');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(6) > .jss1939 > div > .jss2224').first().click();
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('Alt+ArrowLeft');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).press('Alt+ArrowRight');
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).fill('Gesi [Griffith Isaac]');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('#mainLayoutContainer').click();
  await page.getByRole('button', { name: 'Printing Template' }).click();
  await page.locator('[data-test="input-subTitle"]').click();
  await page.locator('[data-test="input-phone"]').click();
  await page.locator('[data-test="input-phone"]').fill('12308');
  await page.locator('[data-test="input-phone"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-phone"]').fill('076122228');
  await page.locator('[data-test="input-email"]').click();
  await page.locator('.jss1939.jss8727 > div:nth-child(5)').click();
  await page.locator('.jss2259.jss8702.jss2261').click();
  await page.locator('[data-test="input-email"]').fill('anisasecondacc24@gmail.com');
  await page.locator('div').filter({ hasText: 'General SettingsManajemen' }).nth(5).click();
  await page.locator('body').press('ControlOrMeta+a');
  await page.locator('.jss1939.jss8727 > div:nth-child(5) > .jss8656 > .jss2259').click();
  await page.locator('.jss1939.jss8727 > div:nth-child(5) > .jss8656 > .jss2259').click();
  await page.locator('[data-test="input-email"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-email"]').fill('wall@gmail.com');
  await page.locator('.jss1939.jss8727').click();
  await page.locator('[data-test="input-subTitle"]').click();
  await page.locator('div').filter({ hasText: 'General SettingsManajemen' }).nth(5).click();
  await page.getByText('LogoUpload LogoDrag & drop').click();
  await page.locator('.jss8656.jss8724 > .jss2259 > .jss8695 > .jss8696').click();
  await page.getByRole('option', { name: 'Facebook' }).click();
  await page.locator('div').filter({ hasText: /^\+$/ }).click();
  await page.locator('[data-test="btn-addContact"]').click();
  await page.locator('[data-test="input-facebook"]').fill('Wall Clinic');
  await page.locator('[data-test="input-facebook"]').press('Enter');
  await page.locator('[data-test="input-noteFooter"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-noteFooter"]').fill('Keterangan Footer');
  await page.locator('[data-test="input-noteFooter"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-noteFooter"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-noteFooter"]').press('ControlOrMeta+ArrowRight');
  await page.locator('[data-test="input-noteFooter"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-noteFooter"]').press('ArrowLeft');
  await page.locator('[data-test="input-noteFooter"]').press('ControlOrMeta+Shift+ArrowRight');
  await page.locator('[data-test="input-noteFooter"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-noteFooter"]').fill('Keterangan\n');
  await page.locator('[data-test="input-noteFooter"]').press('ControlOrMeta+z');
  await page.locator('[data-test="input-noteFooter"]').fill('Keterangan Footer');
  await page.locator('[data-test="input-noteFooter"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-signatureLeft"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-signatureLeft"]').fill('Signa Kiri');
  await page.locator('[data-test="input-signatureLeft"]').press('Tab');
  await page.locator('[data-test="input-signatureRight"]').fill('SDonec non massa suscipit tellus.');
  await page.locator('[data-test="input-signatureRight"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-signatureRight"]').fill('Signa Kanan');
  await page.locator('[data-test="parent-autocomplete-cariPasien"] [data-test="autocomplete-input"]').fill('WL-');
  await page.locator('[data-test="input-hari"]').fill('3');
  await page.locator('[data-test="parent-autocomplete-diagnosa-1780548107272"] [data-test="autocomplete-input"]').fill('Feve');
  await page.locator('[data-test="parent-autocomplete-diagnosa-1780548119705"] [data-test="autocomplete-input"]').press('ControlOrMeta+f');
  await page.getByRole('textbox', { name: 'Dokter yang memeriksa' }).fill('Sample');
  await page.locator('[data-test="input-letterNumber"]').fill('w3r2r32');
  await page.goto('https://dev-essensial.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('surat');
  await page.locator('[data-test="input-nama-dokter"]').fill('Jnwfjk');
  await page.locator('[data-test="input-nama-dokter"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-nama-dokter"]').fill('Random Data 01');
  await page.locator('[data-test="input-nama-dokter"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-nama-dokter"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-pemberi-informasi"]').fill('Random Data 01');
  await page.locator('[data-test="input-penerima-informasi"]').fill('Random Data 01');
  await page.locator('[data-test="input-penerima-informasi"]').press('Tab');
  await page.locator('[data-test="input-diagnosis"]').fill('Random Data 01q');
  await page.locator('[data-test="input-diagnosis"]').press('Tab');
  await page.locator('[data-test="input-diagnosis"]').fill('Random Data 01');
  await page.locator('[data-test="input-diagnosis"]').press('Tab');
  await page.locator('[data-test="input-dasar-diagnosis"]').fill('Random Data 01');
  await page.locator('[data-test="input-tindakan-kedokteran"]').fill('Random Data 01');
  await page.locator('[data-test="input-indikasi-tindakan"]').fill('Random Data 01');
  await page.locator('[data-test="input-tata-cara"]').fill('Random Data 01');
  await page.locator('[data-test="input-risiko"]').fill('Random Data 01');
  await page.locator('[data-test="input-tujuan"]').fill('Random Data 01');
  await page.locator('[data-test="input-komplikasi"]').fill('Random Data 01');
  await page.locator('[data-test="input-prognosis"]').fill('Random Data 01');
  await page.locator('[data-test="input-alternatif-resiko"]').fill('Random Data 01');
  await page.locator('[data-test="input-nama-penanggungjawab-section2"]').fill('Random 01');
  await page.locator('[data-test="input-alamat-penanggung-jawab"]').fill('Alamat 02');
  await page.locator('[data-test="input-bukti-diri-ktp"]').fill('Q3');
  await page.locator('[data-test="input-no-tlp-penanggung-jawab"]').fill('Efrew');
  await page.locator('[data-test="input-tindakan-medis-text-2"]').fill('Weff');
  await page.locator('[data-test="input-tindakan-medis-text-1"]').fill('Wfewfw');
  await page.locator('[data-test="input-saksi-name"]').fill('wefwfew');
  await page.getByRole('textbox', { name: 'Masukkan nama' }).fill('random sample');
  await page.goto('https://dev-essensial.assist.id/registration');
  await page.locator('html').getByRole('document').press('Escape');
  await page.locator('#rjHeaderButton').press('Escape');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.locator('[data-test="close-global-tooltip"]').click();
  await page.locator('#add21300').click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('WL-');
  await page.getByRole('button', { name: 'WL-Dominik 03-06-2004,' }).click();
  await page.getByText('KeluhanProsedur Rencana').click();
  await page.locator('[data-test="input-complaint"]').click();
  await page.locator('[data-test="input-complaint"]').fill('k Ad');
  await page.locator('[data-test="input-complaint"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-complaint"]').fill('Cek add surat dari Regis');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('div').filter({ hasText: 'Seluruh Dokterdr. WL-Issac' }).nth(5).click();
  await page.locator('[data-test="autocomplete-input"]').fill('Fev');
  await page.locator('[data-test="input-duration-sakit"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="input-duration-sakit"]').fill('2');
  await page.locator('[data-test="input-duration-sakit"]').press('Enter');
  await page.locator('[data-test="input-duration-sakit"]').fill('3');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.locator('[data-test="sidebar-item-registrasi"]').click();
  await page.locator('[data-test="header-select-button-arrow"]').click();
  await page.getByRole('menuitem', { name: 'Surat Baru' }).click();
  await page.locator('div').filter({ hasText: 'RegistrationWall [Clinica' }).nth(4).click();
  await page.getByRole('button', { name: 'Surat Baru' }).click();
  await page.getByText('+ Diagnosa').click();
  await page.getByText('Tipe Surat *Surat Keterangan SakitTanggal KunjunganNama PasienWL-Dominik').click();
  await page.getByText('Tipe Surat *Surat Keterangan SakitTanggal KunjunganNama PasienWL-Dominik').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('div').filter({ hasText: '2026Kam, Jun' }).nth(2).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Surat Keterangan Sakit' }).click();
  await page.getByRole('option', { name: 'Surat Keterangan Sehat' }).click();
  await page.locator('[data-test="input-height-sehat"]').click();
  await page.locator('[data-test="input-height-sehat"]').fill('156');
  await page.locator('[data-test="input-weight-sehat"]').click();
  await page.locator('[data-test="input-weight-sehat"]').fill('79');
  await page.locator('[data-test="input-temperature-sehat"]').click();
  await page.locator('[data-test="input-temperature-sehat"]').fill('38');
  await page.locator('[data-test="input-sistole-sehat"]').click();
  await page.locator('[data-test="input-sistole-sehat"]').fill('1223');
  await page.locator('[data-test="input-diastole-sehat"]').click();
  await page.locator('[data-test="input-diastole-sehat"]').fill('34');
  await page.locator('[data-test="input-respiratory-sehat"]').click();
  await page.locator('[data-test="input-blood-type-sehat"]').click();
  await page.locator('[data-test="input-blood-type-sehat"]').fill('B+');
  await page.locator('[data-test="input-respiratory-sehat"]').click();
  await page.locator('[data-test="input-blood-type-sehat"]').fill('B+23');
  await page.locator('[data-test="input-respiratory-sehat"]').press('Tab');
  await page.locator('[data-test="input-respiratory-sehat"]').click();
  await page.locator('[data-test="input-respiratory-sehat"]').click();
  await page.locator('[data-test="input-blood-type-sehat"]').click();
  await page.locator('[data-test="input-blood-type-sehat"]').fill('B+');
  await page.locator('[data-test="input-respiratory-sehat"]').click();
  await page.locator('[data-test="input-respiratory-sehat"]').fill('34');
  await page.locator('[data-test="input-pulse-sehat"]').click();
  await page.locator('[data-test="input-pulse-sehat"]').fill('67');
  await page.getByText(',Digital SignatureSimpan').click();
  await page.locator('#select-kesehatanMata').click();
  await page.getByRole('option', { name: 'Parsial' }).click();
  await page.getByRole('button', { name: 'Digital Signature' }).click();
  await page.locator('div').filter({ hasText: /^Digital Signature$/ }).nth(2).click();
  await page.locator('[data-test="button-simpan-sehat"]').click();
  await page.getByRole('cell', { name: '/06/2026, 14:27' }).click();
  await page.locator('div').filter({ hasText: 'Lihat Rekam Medisengaged' }).nth(4).click();
  await page.getByRole('button', { name: 'Lihat Rekam Medis' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('tr:nth-child(2) > td:nth-child(5) > .jss352').click();
  await page.locator('html').getByRole('document').click();
  await page.locator('html').getByRole('document').click();
  await page5.locator('body').click();
  await page.locator('html').getByRole('document').click();
  await page.getByRole('button').first().click();
  await page.locator('[data-test="sidebar-item-pks"]').click();
  await page.locator('[data-test="sidebar-item-pertanyaan"]').click();
  await page.getByRole('button', { name: 'Tambah Pertanyaan' }).click();
  await page.getByRole('menuitem', { name: 'Tambah Pertanyaan' }).click();
  await page.getByRole('textbox', { name: 'Masukkan judul pertanyaan' }).click();
  await page.getByRole('textbox', { name: 'Masukkan judul pertanyaan' }).fill('Sample dari Clin Lite');
  await page.getByRole('heading', { name: 'Modul*' }).click();
  await page.getByText('Judul Pertanyaan*Modul*Pilih').click();
  await page.getByRole('button', { name: 'Pilih Modul' }).click();
  await page.getByText('Pendaftaran / RegistrasiEMRObat dan BHPKasirOfficeIntegration Third').click();
  await page.getByText('Kasir').click();
  await page.getByText('EMR').click();
  await page.getByText('Obat dan BHP').click();
  await page.getByText('Integration Third party').click();
  await page.getByText('Integration Third party').click();
  await page.locator('.jss50289.jss50290').click();
  await page.locator('.jss50289.jss50290').click();
  const page8Promise = page.waitForEvent('popup');
  await page.locator('.ql-editor').fill('random notes');
  const page8 = await page8Promise;
  await page5.locator('div').nth(1).click();
  await page5.getByRole('heading', { name: 'Halo Selamat Datang!' }).click();
  await page5.getByRole('textbox', { name: 'Masukkan username anda' }).click();
  await page5.getByRole('textbox', { name: 'Masukkan username anda' }).fill('annisa.ghaisani@assist.id');
  await page5.getByRole('textbox', { name: 'Masukkan password anda' }).click();
  await page5.getByRole('textbox', { name: 'Masukkan password anda' }).fill('12345678');
  await page5.getByRole('button', { name: 'Sign In' }).click();
  await page5.getByRole('button', { name: 'Tickets' }).click();
  await page5.getByRole('button', { name: 'RME' }).click();
  const page6Promise = page5.waitForEvent('popup');
  await page5.getByRole('button', { name: 'Lihat Detail' }).first().click();
  const page6 = await page6Promise;
  await page6.getByRole('tab', { name: 'Informasi Tiket' }).click();
  await page6.getByRole('tab', { name: 'History' }).click();
  await page6.getByRole('tab', { name: 'Diskusi Eksternal', exact: true }).click();
  await page6.getByRole('tab', { name: 'Diskusi Eksternal Grup' }).click();
  await page6.getByRole('tab', { name: 'Diskusi Internal' }).click();
  await page6.getByRole('tab', { name: 'Informasi Tiket' }).click();
  await page6.locator('body').press('Escape');
  await page.getByRole('button', { name: 'Lihat Detail' }).press('Escape');
  await page.goto('https://dev-essensial.assist.id/settings');
  await page.locator('[data-test="input-namaKatalogMcu-0"]').fill('WL-MCU-Embolectomy');
  await page.locator('[data-test="input-namaMcu-0"]').fill('Embole 01');
  await page.locator('[data-test="input-namaMcu-0"]').press('ControlOrMeta+a');
  await page.locator('[data-test="input-namaMcu-0"]').press('ControlOrMeta+c');
  await page.locator('[data-test="input-namaMcu-1"]').fill('Embole 02');
  await page.locator('[data-test="input-keterangan-1"]').fill('Em 02');
  await page.locator('[data-test="input-max-0"]').fill('90');
  await page.locator('[data-test="input-satuan-0"]').fill('scale');
  await page.locator('[data-test="autocomplete-input"]').fill('WL-');
  await page.locator('[data-test="input-harga-0"]').fill('Rp20.0000');
  await page.locator('[data-test="input-harga-0"]').press('Tab');
  await page.locator('[data-test="input-harga-1"]').fill('Rp35.0000');
  await page.locator('[data-test="input-namaKatalogMcu-1"]').fill('WL-Tonsillectomy');
  await page.locator('[data-test="input-namaKatalogMcu-1"]').press('ControlOrMeta+z');
  await page.locator('[data-test="input-namaKatalogMcu-1"]').fill('WL-MCU Tonsillectomy');
  await page.locator('[data-test="input-namaKatalogMcu-1"]').press('ControlOrMeta+z');
  await page.locator('[data-test="input-namaKatalogMcu-1"]').fill('WL-MCU-Tonsillectomy');
  await page.locator('[data-test="input-namaMcu-0"]').nth(1).fill('Tonsil');
  await page.locator('[data-test="autocomplete-input"]').fill('WL-');
  await page.locator('[data-test="input-min-0"]').fill('3');
  await page.locator('[data-test="input-max-0"]').nth(1).fill('9');
  await page.locator('[data-test="input-min-0"]').fill('1');
  await page.locator('[data-test="input-max-0"]').nth(1).fill('10');
  await page.locator('[data-test="input-satuan-0"]').nth(1).fill('2');
  await page.locator('[data-test="input-totalHarga-1"]').fill('Rp30.0000');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Cory');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('WL-Cory');
  await page.getByRole('textbox', { name: 'Tanggal Lahir *' }).fill('Einig');
  await page.locator('[data-test="input-tempat-lahir"]').fill('Einig');
  await page.locator('[data-test="input-no-ktp"]').fill('980989123131231');
  await page.locator('[data-test="input-nama-ibu"]').fill('Cory Ibu');
  await page.locator('[data-test="input-no-telepon"]').fill('0800000000');
  await page.locator('input[name="address"]').fill('Jl Einig no 23123');
  await page.locator('input[name="postcode"]').fill('23442');
  await page.locator('[data-test="input-complaint"]').fill('Test Laboratorium');
  await page.locator('[data-test="input-complaint"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('Alt+ArrowRight');
  await page.locator('[data-test="input-complaint"]').fill('Test Sub Menu Laboratorium');
  await page.goto('https://dev-essensial.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('lab');
  await page.locator('html').getByRole('document').press('Escape');
  await page.locator('[data-test="emrAddBtn"]').press('Escape');
  await page.getByRole('textbox', { name: 'Alasan Batal' }).fill('salah poli, mau ke lab');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('Cory');
  await page.locator('[data-test="input-complaint"]').fill('cek lab');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('WL-');
  await page.locator('[data-test="input-complaint"]').fill('Book ke MUC tanpa');
  await page.locator('[data-test="input-complaint"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('Alt+ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('Alt+ArrowRight');
  await page.locator('[data-test="input-complaint"]').press('Alt+ArrowRight');
  await page9.locator('[data-test="sidebar-item-registrasi"]').click();
  await page9.locator('[data-test="menu-laboratorium"]').click();
  await page9.locator('#mainLayoutContainer').click();
  await page9.locator('[data-test="menu-rawat-jalan-lab"]').click();
  await page9.locator('[data-test="menu-rawat-jalan-lab"]').click();
  await page9.locator('[data-test="menu-laboratorium"]').click();
  await page9.locator('div').filter({ hasText: 'Laboratorium event Tanggal' }).nth(5).click();
  await page9.locator('body').press('Escape');
  await page9.locator('div').filter({ hasText: 'Laboratorium event Tanggal' }).nth(5).click();
  await page9.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page9.locator('body').press('Escape');
  await page9.locator('[data-test="sidebar-item-rawat-jalan"]').click();
  await page9.getByRole('button').filter({ hasText: /^$/ }).nth(5).dblclick();
  await page9.locator('#add01345').click();
  await page9.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('');
  await page9.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).click();
  await page9.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('WL-Trejo');
  await page9.getByRole('button', { name: 'new' }).click();
  await page9.getByRole('img', { name: 'Profile' }).click();
  await page9.locator('[data-test="input-nama-pasien"]').click();
  await page9.locator('[data-test="input-tempat-lahir"]').click();
  await page9.locator('[data-test="input-tempat-lahir"]').fill('Jarabulus');
  await page9.locator('[data-test="date-tanggal-lahir"]').getByRole('button').click();
  await page9.getByRole('button', { name: '2005' }).click();
  await page9.locator('div').filter({ hasText: '2005Sab, Jun' }).nth(2).click();
  await page9.getByRole('button', { name: 'OK' }).click();
  await page9.locator('#select-education').click();
  await page9.getByRole('option', { name: 'Diploma (D3)' }).click();
  await page9.getByRole('button', { name: 'Diploma (D3)' }).click();
  await page9.getByRole('option', { name: 'SMA' }).click();
  await page9.locator('#select-job').click();
  await page9.getByRole('option', { name: 'Mengurus Rumah Tangga' }).click();
  await page9.locator('#select-bloodType').click();
  await page9.getByRole('option', { name: 'B+', exact: true }).click();
  await page9.getByRole('button', { name: 'B+' }).click();
  await page9.getByRole('option', { name: 'A-' }).click();
  await page9.getByRole('button', { name: 'Tidak Tahu' }).click();
  await page9.getByRole('option', { name: 'Hindu' }).click();
  await page9.getByRole('button', { name: 'Hindu' }).click();
  await page9.getByRole('option', { name: 'Protestan' }).click();
  await page9.locator('#select-status').click();
  await page9.getByRole('option', { name: 'Cerai Hidup' }).click();
  await page9.locator('div:nth-child(2) > .jss16278 > .jss16162 > div').first().click();
  await page9.getByText('Jenis Kelamin *').click();
  await page9.locator('[data-test="input-tempat-lahir"]').dblclick();
  await page9.locator('[data-test="input-tempat-lahir"]').fill('Limache');
  await page9.locator('input[name="address"]').click();
  await page9.locator('input[name="address"]').fill('Jl Limache no 234544');
  await page9.locator('#select-selectedProvince').click();
  await page9.getByRole('option', { name: 'KALIMANTAN TENGAH' }).click();
  await page9.locator('#select-selectedProvince').click();
  await page9.getByRole('option', { name: 'BENGKULU' }).click();
  await page9.locator('#select-selectedKabupaten').click();
  await page9.getByRole('option', { name: 'KAB. KAUR' }).click();
  await page9.locator('#select-selectedKecamatan').click();
  await page9.getByRole('option', { name: 'KAUR UTARA' }).click();
  await page9.locator('#select-selectedKelurahan').click();
  await page9.getByRole('option', { name: 'PADANG MANIS' }).click();
  await page9.locator('input[name="postcode"]').click();
  await page9.locator('input[name="postcode"]').fill('23432434');
  await page9.locator('div').filter({ hasText: /^NIP$/ }).nth(2).click();
  await page9.getByText('Kota / KabupatenKAB. KAURKecamatanKAUR UTARAKelurahanPADANG MANISKode Pos').click();
  await page9.getByRole('button', { name: 'simpan' }).click();
  await page9.locator('.jss2362.jss2349.jss2353.jss2363.jss2350.jss2370').first().click();
  await page9.locator('[data-test="input-complaint"]').fill('random');
  await page9.getByRole('button', { name: 'Umum' }).nth(1).click();
  await page9.getByRole('option', { name: 'Lab' }).click();
  await page9.getByRole('button', { name: 'Pilih MCU' }).click();
  await page9.getByRole('checkbox', { name: 'WL-MCU-Embolectomy' }).check();
  await page9.getByRole('checkbox', { name: 'WL-MCU-Tonsillectomy' }).check();
  await page9.getByRole('button', { name: 'Simpan' }).click();
  await page9.locator('[data-test="input-complaint"]').click();
  await page9.locator('[data-test="input-complaint"]').fill('random Lab MCU');
  await page9.getByRole('button', { name: 'Simpan' }).click();
  await page9.getByRole('row', { name: '13:15 WIT Tambah Pasien' }).click();
  await page9.locator('html').getByRole('document').click();
  await page9.getByRole('button').filter({ hasText: /^$/ }).click();
  await page9.locator('[data-test="sidebar-item-registrasi"]').click();
  await page9.locator('[data-test="menu-laboratorium"]').click();
  await page9.getByRole('cell', { name: 'WL-MCU-Embolectomy' }).click();
  await page9.getByRole('cell').nth(5).click();
  await page9.getByRole('row', { name: 'WL-Cory, MR00000004, 23 Tahun' }).locator('[data-test="icon-list-lab-6a212f8bb626f6942b3b445b"]').click();
  await page9.locator('[data-test="input-mcu-value-0-0-lab"]').click();
  await page9.locator('[data-test="input-mcu-value-0-0-lab"]').fill('23');
  await page9.locator('[data-test="input-notes-lab"]').click();
  await page9.locator('[data-test="input-notes-lab"]').fill('dari Regis');
  await page9.locator('[data-test="autocomplete-input"]').click();
  await page9.locator('[data-test="input-notes-lab"]').fill('dari Regiswl');
  await page9.locator('div').filter({ hasText: /^dari Regiswldari Regiswl$/ }).first().click();
  await page9.locator('div').filter({ hasText: /^dari Regiswldari Regiswl$/ }).first().click();
  await page9.locator('[data-test="input-notes-lab"]').fill('dari Regis');
  await page9.locator('[data-test="autocomplete-input"]').fill('Wl');
  await page9.locator('[data-test="input-notes-lab"]').fill('dari Regis edit');
  await page9.locator('[data-test="input-mcu-value-0-0-lab"]').fill('24');
  await page.getByRole('textbox', { name: 'Cari Pasien / No MR / No Ktp' }).fill('WL-v');
  await page.getByRole('textbox', { name: 'Cari Pasien / No MR / No Ktp' }).press('Escape');
  await page.goto('https://dev-essensial.assist.id/profile');
  await page.getByRole('textbox', { name: 'Perusahaan' }).fill('Pt');
  await page.locator('[data-test="autocomplete-metode-pembayaran-asuransi"] [data-test="autocomplete-input"]').fill('As');
  await page.locator('[data-test="autocomplete-metode-pembayaran-debit"] [data-test="autocomplete-input"]').fill('');
  const downloadPromise = page.waitForEvent('download');
  await page.goto('https://dev-essensial.assist.id/settings');
  const download = await downloadPromise;
  await page.getByRole('button', { name: 'Drag & drop files orbrowse' }).setInputFiles('Import Katalog Harga Prosedur (1).xlsx');
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.getByRole('textbox', { name: 'Cari tindakan/obat/bahan' }).fill('WL-');
  await page.locator('[data-test="quantity-input"]').press('Shift+ArrowRight');
  await page.locator('[data-test="quantity-input"]').fill('1');
  await page.getByRole('textbox', { name: 'Cari tindakan atau obat' }).fill('WL-');
  await page.locator('[data-test="kasir-item-2"] [data-test="quantity-input"]').press('Shift+ArrowLeft');
  await page.locator('[data-test="kasir-item-2"] [data-test="quantity-input"]').fill('1');
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.locator('[data-test="search-kasir-input"]').fill('dominik');
  await page.locator('[data-test="search-kasir-input"]').press('Enter');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('WL-Bryant');
  await page.locator('[data-test="input-nama-ibu"]').fill('Bryant Ibu');
  await page.locator('[data-test="input-no-ktp"]').fill('2324234');
  await page.locator('input[name="address"]').fill('Jl Oroso no 24233');
  await page.locator('[data-test="input-complaint"]').fill('random cek Racikan. diKasir');
  await page.goto('https://dev-essensial.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('racik');
  await page.getByRole('textbox', { name: 'Cari fitur' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('resep');
  await page.locator('[data-test="input-concoction-cigna-0-prescription"]').fill('random dari EMR');
  await page.locator('[data-test="input-concoction-quantity-0-prescription"]').fill('1');
  await page.locator('[data-test="container-concoction-unit-autocomplete-0-prescription"] [data-test="autocomplete-input"]').fill('Pil');
  await page.getByRole('textbox', { name: 'Nama Obat' }).fill('WL-');
  await page.locator('input[name="prescriptions.0.materialPrescript.0.numerator"]').fill('1');
  await page.locator('input[name="prescriptions.0.materialPrescript.0.denominator"]').fill('2');
  await page.getByRole('textbox', { name: 'Nama Obat' }).fill('WL-');
  await page.locator('input[name="prescriptions.0.materialPrescript.1.numerator"]').fill('1');
  await page.locator('input[name="prescriptions.0.materialPrescript.1.denominator"]').fill('4');
  await page.goto('https://dev-essensial.assist.id/rawatJalan');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('WL-');
  await page.locator('[data-test="input-nama-pasien"]').fill('WL-Powell');
  await page.locator('[data-test="input-tempat-lahir"]').fill('Balma');
  await page.locator('[data-test="input-nama-ibu"]').fill('Powell Ibu');
  await page.locator('input[name="address"]').fill('JL Balma no 2323');
  await page.locator('[data-test="input-complaint"]').fill('cari racikan di KAsir');
  await page.locator('[data-test="input-complaint"]').press('ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('ArrowLeft');
  await page.locator('[data-test="input-complaint"]').press('Shift+ArrowDown');
  await page.locator('[data-test="input-complaint"]').fill('cari racikan di Ka ');
  await page.locator('[data-test="input-complaint"]').press('ArrowDown');
  await page.locator('[data-test="input-complaint"]').fill('cari racikan di Ka sir pasien EMR');
  await page.goto('https://dev-essensial.assist.id/emr');
  await page.getByRole('textbox', { name: 'Cari fitur' }).fill('pros');
  await page.locator('[data-test="container-procedure-name-0-procedure"] [data-test="autocomplete-input"]').fill('Wl-');
  await page.locator('[data-test="input-notes-0-procedure"]').fill('random datra');
  await page.goto('https://dev-essensial.assist.id/cashier');
  await page.locator('html').getByRole('document').press('Escape');
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.goto('https://dev-essensial.assist.id/office');
  await page.getByRole('textbox', { name: 'Cari Laporan' }).fill('marg');
});