import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').click();
  await page.locator('#username').click();
  await page.locator('#username').fill('anisasecondacc24@gmail.com');
  await page.locator('[data-test="input-password"]').click();
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.getByRole('button', { name: 'close' }).click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '- Pure Burns [Schedula] (QA)' }).click();
  await page.locator('[data-test="sidebar-item-rawat-jalan"]').click();
  await page.locator('#add00900').click();
  await page.locator('#add00900').click();
  await page.locator('#add10915').click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PB-AI-AntiG-000001');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PB-AI-Play-000001');
  await page.getByRole('button', { name: 'new' }).click();
  await page.getByRole('button').nth(2).click();
  await page.getByRole('button', { name: '1973' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('[data-test="input-tempat-lahir"]').click();
  await page.locator('[data-test="input-tempat-lahir"]').fill('Surabaya');
  await page.locator('input[name="address"]').click();
  await page.locator('input[name="address"]').fill('Jl Surabaya No 245');
  await page.locator('#select-selectedProvince').click();
  await page.getByRole('option', { name: 'KALIMANTAN TENGAH' }).click();
  await page.locator('#select-selectedKabupaten').click();
  await page.getByRole('option', { name: 'KAB. MURUNG RAYA' }).click();
  await page.locator('#select-selectedKecamatan').click();
  await page.getByRole('option', { name: 'SERIBU RIAM' }).click();
  await page.locator('#select-selectedKelurahan').click();
  await page.getByRole('option', { name: 'TAKAJUNG' }).click();
  await page.locator('input[name="postcode"]').click();
  await page.locator('input[name="postcode"]').fill('24123');
  await page.getByRole('button', { name: 'simpan' }).click();
  await page.locator('[data-test="input-complaint"]').click();
  await page.locator('[data-test="input-complaint"]').fill('Test limit 100 kunjungan pasien Schedula');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.locator('#add00945').click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PB-AI-Play-000002');
  await page.getByRole('button', { name: 'new' }).click();
  await page.locator('[data-test="input-tempat-lahir"]').click();
  await page.locator('[data-test="input-tempat-lahir"]').fill('KAlimantan');
  await page.locator('[data-test="input-tempat-lahir"]').press('ControlOrMeta+ArrowLeft');
  await page.locator('[data-test="input-tempat-lahir"]').press('ArrowRight');
  await page.locator('[data-test="input-tempat-lahir"]').press('Shift+ArrowRight');
  await page.locator('[data-test="input-tempat-lahir"]').fill('Kalimantan');
  await page.getByRole('button').nth(2).click();
  await page.getByRole('button', { name: '2011' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('#select-religion').click();
  await page.getByRole('option', { name: 'Hindu' }).click();
  await page.getByRole('button', { name: 'Laki - laki' }).click();
  await page.getByRole('option', { name: 'Perempuan' }).click();
  await page.locator('#select-status').click();
  await page.getByRole('option', { name: 'Cerai Hidup' }).click();
  await page.locator('#select-job').click();
  await page.getByRole('option', { name: 'Psikiater/Psikolog' }).click();
  await page.locator('#select-education').click();
  await page.getByRole('option', { name: 'Sarjana (S1)' }).click();
  await page.getByRole('button', { name: 'Tidak Tahu' }).click();
  await page.getByRole('option', { name: 'B-', exact: true }).click();
  await page.locator('input[name="address"]').click();
  await page.locator('input[name="address"]').fill('Jl Kalimantan no 23');
  await page.locator('#select-selectedProvince').click();
  await page.getByRole('option', { name: 'KALIMANTAN BARAT' }).click();
  await page.locator('#select-selectedKabupaten').click();
  await page.getByRole('option', { name: 'KAB. KUBU RAYA' }).click();
  await page.locator('#select-selectedKecamatan').click();
  await page.getByRole('option', { name: 'SUNGAI AMBAWANG' }).click();
  await page.locator('#select-selectedKelurahan').click();
  await page.getByRole('option', { name: 'PANCAROBA' }).click();
  await page.locator('input[name="postcode"]').click();
  await page.locator('input[name="postcode"]').fill('34666');
  await page.getByRole('button', { name: 'simpan' }).click();
  await page.locator('[data-test="input-complaint"]').click();
  await page.locator('[data-test="input-complaint"]').fill('Test limit 100 kunjungan pasien Schedula');
  await page.getByRole('button', { name: 'Simpan' }).click();
});