import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-essensial.assist.id/login');
  await page.locator('#username').click();
  await page.locator('#username').fill('annisa.ghaisani@assist.id');
  await page.locator('[data-test="input-password"]').click();
  await page.locator('[data-test="input-password"]').fill('12345678');
  await page.locator('[data-test="login-btn"]').click();
  await page.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.locator('[data-test="change-account-button-arrow"]').click();
  await page.getByRole('menuitem', { name: '001652 - Pure Burns [Schedula' }).click();
  await page.goto('https://dev-essensial.assist.id/');
  await page.locator('html').getByRole('document').click();
  await page.getByRole('dialog').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.locator('[data-test="sidebar-item-rawat-jalan"]').click();
  await page.locator('[data-test="sidebar-item-registrasi"]').click();
  await page.getByRole('button', { name: 'Pendaftaran Baru' }).click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PB-');
  await page.getByRole('button', { name: 'PB-AI-Play-000001 22-05-1973' }).click();
  await page.locator('.jss3438.jss3439.jss3478.jss3400 > div:nth-child(5)').click();
  await page.locator('.jss3438.jss3439.jss3478.jss3400 > div:nth-child(5)').click();
  await page.locator('.jss20563').click();
  await page.locator('[data-test="input-complaint"]').click();
  await page.locator('[data-test="input-complaint"]').fill('Random Cek Appt Limit 100 Kunjungan');
  await page.getByRole('button', { name: 'Simpan' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.locator('[data-test="menu-rawat-jalan-poli"]').click();
  await page.getByRole('button', { name: 'Pendaftaran Baru' }).click();
  await page.getByRole('textbox', { name: 'Cari Nama Lengkap Pasien /' }).fill('PB-');
  await page.getByRole('button', { name: 'PB-AI-Play-000001 22-05-1973' }).click();
  await page.locator('#select-doctorName').click();
  await page.getByRole('option', { name: 'BN-Gilbert' }).click();
  await page.locator('[data-test="input-complaint"]').click();
  await page.locator('[data-test="input-complaint"]').fill('Random Cek Appt Limit 100 Kunjungan');
    await page.getByRole('button', { name: 'Simpan' }).click();
});